### ISSUE TITLE
Support channel(s)

### ISSUE THREAD

**Issue by cfoellmann** [Varying-Vagrant-Vagrants/VVV#1023]
I think we should think about some other way to answer "simple" questions like "can't get it working".

The issues here are to hard to track. How about slack or something like it? I would drop in see what is up and reply to a question. A notification would be sent and in a simple conversation the problem could be solved.

Am I right? Or not.

**Comment by LoreleiAurora** [comment]
I like this idea but think Gitter would be a better fit than yer another slack group.

**Comment by jeremyfelt** [comment]
I don't have much experience with Gitter. Are there other examples of smallish open source projects that are using it successfully to provide support?

Because VVV is such a WP focused thing, we _could_ setup a Slack organization and allow anyone with `@chat.wordpress.org` email address to sign up. I'd probably be more likely to be online in Slack just because it's part of my daily workflow, but answering questions is a different story. :see_no_evil: 

Part of me thinks we should hold on this until documentation is in a better spot, then it should be much easier to point toward frequent answers and cut down on the noise. Overall, it's not too noisy in GitHub at this point.

Completely happy to keep hearing other thoughts on this though. :)

**Comment by LoreleiAurora** [comment]
@jeremyfelt do you have any idea if we could get a channel in core slack?
