### ISSUE TITLE
Sync Vagrant between Mac and Windows

### ISSUE THREAD

**Issue by phidomo** [Varying-Vagrant-Vagrants/VVV#1052]
I am syncing the Vagrant folder with OneDrive between my PC and Mac. I defined different VAGRANT_DOTFILE_PATH for each machine. I started working on a project on the PC and then did vagrant halt. On the Mac I do vagrant up and it builds a new VM. However I get these errors: 

==> default: nginx: unrecognized service
==> default: memcached: unrecognized service
==> default: mailcatcher: unrecognized service
==> default: /tmp/vagrant-shell: line 407: php5dismod: command not found
==> /tmp/vagrant-shell: line 29: git: command not found
==> vvv-init.sh: line 5: mysql: command not found
==> vvv-init.sh: line 60: svn: command not found

If I do a clean install of VVV in a different folder then git, mysql, etc. get installed on the VM. But apparently it doesn't when I do vagrant up in the synced folder. How can I force a complete install of the VM on the Mac in the synced folder?

**Comment by jeremyfelt** [comment]
Hi @phidomo, thanks for stopping by.

I'm not sure that syncing a VM between two different operating systems is a good idea. Then `unrecognized service` errors that you're seeing indicate that provisioning has not run, so in the move to the new OS, the box is no longer recognized.

I would find an alternate way to share the files between two machines rather than the VM itself. If you want to pursue the possibility of this further, then I would recommend digging into the Vagrant or VirtualBox projects more to see what's possible as it is likely not a VVV specific solution.
