### ISSUE TITLE
Suggestion: New minimalistic fully automated site creation with 2 lines of YAML

### ISSUE THREAD

**Issue by nextgenthemes** [Varying-Vagrant-Vagrants/VVV#1058]
I already made two suggestion for the new provisioning config in #1044 but I now have a idea to make it even shorter.

This is before I am getting a answer if my assumption is correct that it actually now takes manually creating/editing 3-4 files and a folder just so setup a custom site.

```
sites:
  local.wordpress.dev:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
  custom.site.domain:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
```

What I suggest is VVV should do with this:

1. Create a folder with the sites domain name. Would make way more sense then the current "wordpress-local" ... or whatever folder names to do it like sits commonly done on real webservers. It also seems the current config needs local and vm (callled provision) folders specifically set. I think they should be a default that is based on domain name.
2. Clone the repo set into that folder (already done now).
3. The https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git and the other dev repo should have its setup scripts not create hard coded sites/databases but should rather read the folder they are in and take the folder name and create the database name based on that.
4. Add sites name to hosts if plugin is installed.

This would make:

1. The creating, modifying of [this 3 files](https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default) and creating folders for custom sites obsolete. I think its a annoying precess to copy paste this stuff only to change the database name and folder. My guess is most users who want new sites are very fine with the config you maintain for the default sites so it seems strange to me why its so "complicated" to set up a custom site.
2. Installing the separate VV tool for such a very basic task of creating a new custom site also obsolete. This could also maybe extended to remove/deactivate sites (without deleting files maybe) when they are no longer found in the .yaml when running provision.

**Comment by jeremyfelt** [comment]
Hi @nextgenthemes, thanks for opening a ticket. I've responded to the suggestions inline. Note that since this is a new process, all changes are definitely on the table. It also means I'm not completely familiar with it yet, so we'll see how this goes. :)

There's probably some good background reading to be done in #980 and the various tickets and decisions that were closed as part of the initial effort to create this provisioning system.

> Create a folder with the sites domain name. Would make way more sense then the current "wordpress-local" ... or whatever folder names to do it like sits commonly done on real webservers. It also seems the current config needs local and vm (callled provision) folders specifically set. I think they should be a default that is based on domain name.

The `vm_dir` directory can be used to set the directory inside the virtual machine. I think we need to remain flexible her rather than assuming the directory should match the site name.

> The https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git and the other dev repo should have its setup scripts not create hard coded sites/databases but should rather read the folder they are in and take the folder name and create the database name based on that.

Not every external repository will have the same structure. They may not even need a database at all. Putting the configuration at the site level allows for some nice flexibility, IMO. It may be possible in other iterations to automate a standard site setup a bit, but I do like the idea of starting with, becoming comfortable with, and documenting the basics first.

> Add sites name to hosts if plugin is installed.

Sites may have more than one hostname. Multiple hostnames can be configured with the `hosts` setting for the site in the YAML file. I think this is okay as an explicit configuration.

**Comment by nextgenthemes** [comment]
So i have seen that the `vvv-config.yml` now has a config for hostnames. This was not the case when I initially opened this.

I don't know the reasoning for different hosts for one site setup but I would prefer a simpler one site  one hostname config. Then the folders could also have the hostname and things would be simpler and easier to understand for noobs.

> Not every external repository will have the same structure. They may not even need a database at all. Putting the configuration at the site level allows for some nice flexibility, IMO. It may be possible in other iterations to automate a standard site setup a bit, but I do like the idea of starting with, becoming comfortable with, and documenting the basics first.

I not really get what you are saying here. Its does not matter of the config files set a database or not. What I mean is that VVV just replaces strings during provisioning.

Its already done with `root {vvv_path_to_site}/public_html; ` in `vvv-nginx.conf` so why not just to the same with the database name in https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default/blob/master/provision/vvv-init.sh?

Just just this file as template and replace `wordpress_default` with `{database_name}` or something like that and then let VVV replace the database strings during provisioning.

If I want to have another default site right now I could clone the wordpress-default repo and just replace that strings and add my own repo to the config, but it should be easier.

**Comment by jeremyfelt** [comment]
A template approach is taken in the https://github.com/Varying-Vagrant-Vagrants/custom-site-template repo, which should reduce the burden to creating a new site significantly.
