### ISSUE TITLE
`-provisioner` directories are annoying for tab autocomplete'ing

### ISSUE THREAD

**Issue by JJJ** [Varying-Vagrant-Vagrants/VVV#1068]
## Expected Behavior

When navigating through the file system with your favorite terminal app, it was previously very convenient to type:

`cd /sr%tab%/w%tab%/word%tab%-dev%tab%/s%tab/`

## Current Behavior

Directories like `wordpress-develop` return 2 autocomplete results, requiring an additional `/` keystroke, which after several years of VVV is pretty annoying to need to do.

## Possible Solution

I'd recommend renaming the provisioner directories from `wordpress-develop-provisioner` to `provisioner-wordpress-develop`. This way all of the provisioner directories autocomplete with each other, which I guess is less natural to relate them but more natural is day-to-day usage.

## Context

Maybe I'm being fussy, or lazy, 

## Your Environment

* VVV version: latest master
* Vagrant version: 1.9.1
* VM Provider name: VirtualBox
* VM Provider version: 5.1.12
* Operating System and version: macOS 10.12.2

**Comment by LoreleiAurora** [comment]
Almost immediately after doing this i regreted it :/
Personally i would like to change the structure of each site in www to this:
```
- wordpress-default
  - log
  - provision
  - public_html
```

What are your thoughts on this?

**Comment by JJJ** [comment]
I like your proposed solution a lot better than mine, but wonder what the upgrade path will look like, especially for custom sites installed through tools like VV.

**Comment by LoreleiAurora** [comment]
At the moment VV does not work with the develop branch, and i know myself and @jeremyfelt  both consider changes to develop fair game at the moment as there have been so many breading changes.

But custom sites will still work (im doing it now for custom sites).
Basically the provisioner does a `find ${VM_DIR} -maxdepth 4 -name 'vvv-init.sh'` for each site, so we wouldn't actually be changing anything in this repository, only the repositories for the sites as at present both structures work already.

**Comment by JJJ** [comment]
Good points!

I think it's ultimately up to you and @jeremyfelt to decide, but I'm onboard.

**Comment by jeremyfelt** [comment]
The first way I thought about complicating my opinion of this was around how a single definition in the config file could result in multiple sites and how that would work with the `public_html/` directory. After spending a bit more time on that, I'm probably overthinking it.

As long as we know that existing custom sites will continue to work fine, I'm okay to go down the path of @LoreleiAurora's proposed structure. I still wish there was a better name than `public_html`, only because that has Apache written all over it, but I'm not sure that there is.

To clarify this even further, here's what the `wordpress-develop` directory would result in:

```
- wordpress-develop
    - log
    - provision
    - public_html
        - src/
        - tests/
```

Separately for @JJJ - You might be the first to fully use the new GitHub issue template. If you have any thoughts on whether it was annoying or useful, I'd be happy to hear them. :smile:

**Comment by JJJ** [comment]
Directory structure seems OK to me. `public_html` could also just be `public` or `web` or anything.

Issue template seemed OK, not annoying. Maybe a little wordy, but it was useful to have a known pattern to adhere to. I did delete a section or 2 that didn't seem relevant, since this was more of an opinion than a bug, but I think most issues won't have that same problem.
