### ISSUE TITLE
Set master as the default branch.

### ISSUE THREAD

**Issue by LoreleiAurora** [Varying-Vagrant-Vagrants/VVV#1072]
We should set master as the default branch so new installs do not get bleeding edge undocumented code, that can change frequently during development.

**Comment by jeremyfelt** [comment]
I like `develop` as the default branch, as everything on GitHub is for development. :smile: 

I think one of the objectives of cleaning up our documentation will also be to make it more obvious that other versions can be used. In an ideal world, users would use varyingvagrantvagrants.org to get started rather than GitHub.

At some level, we're in an unusual spot that's causing a bit of pain but will be resolved shortly. We're not often making larger changes that can impact things long term.

Another issue with switching back to `master` is that any new pull requests are automatically opened against that, so it adds another hurdle to the contributor experience.

**Comment by kopepasah** [comment]
Leaving `develop` branch as default is ideal. I feel that it is up to a user to know which version she/he wants to run.

Documentation will definitely help alleviate any confusion.

**Comment by mkjonesuk** [comment]
I'm with @LoreleiAurora - running a bleeding edge caused me a couple of days pain recently. It's not clear in the documentation that you can end up running untested code.

**Comment by kopepasah** [comment]
It is extremely common that `develop` branch is always in flux and, in my opinion, it is up to the user to clone and use the reference (branch|tag) of her/his choice.

In addition, it is not always true that the `master` branch is the latest tagged release (although it is _usually_ stable).

I still lean towards leaving `develop` as the default branch.

If a user wants to clone a specific branch she/he can always append the `--branch` argument when cloning.

**Comment by mkjonesuk** [comment]
@kopepasah how about a warning in the README as a compromise. This section:

![screenshot 2017-01-07 at 16 25 00](https://cloud.githubusercontent.com/assets/1765467/21743233/e5728402-d4f5-11e6-87a5-559ff03e1894.png)

Doesn't make it explicit that cloning develop can lead to unstable results.

**Comment by grappler** [comment]
The git clone command could include checking out the master branch instead.

So have `git clone  -b master git://github.com/Varying-Vagrant-Vagrants/VVV.git vagrant-local` instead.

**Comment by skorasaurus** [comment]
Ditto with @mkjonesuk ; I had the same experience as well and am willing to write the PR as well; as I already had in vagrantvagranthttps://github.com/Varying-Vagrant-Vagrants/VVV/pull/1060

Since the Documentation for newer users is being moved to https://varyingvagrantvagrants.org/ is that being version tracked anywhere?

**Comment by jeremyfelt** [comment]
We're going to address this with improved documentation for the 2.0.0 release. There should be a couple new clear indicators as to what version is being used and a prod to use the master branch if using git and not developing. The `develop` branch will still be the default on GitHub.
