### ISSUE TITLE
Why the vvv-custom.yml requirement in v2?

### ISSUE THREAD

**Issue by khromov** [Varying-Vagrant-Vagrants/VVV#1140]
I've been using VVV for a long time, and set up all my sites with the auto site setup. It is very easy to set up an environment for yourself and other team members by simply cloning your site Git repo with the auto site setup files into the `sites/` folder and running `vagrant provision`.

I am very very confused about the decision to require users of VVV to create and then edit an additional configuration file to accomplish this same thing in v2. I understand you can add more configuration via the new YAML format but that could just as well have been done by placing the `vvv-custom.yml` file inside the actual site folder. 

Would you be open to changing this?

**Comment by jeremyfelt** [comment]
Hi @khromov, thanks for stopping by. This is covered somewhat in the "why is this necessary" section at the bottom of the [migration document](https://varyingvagrantvagrants.org/docs/en-US/migrate-vvv-1/).

To take your example, the old process looked like:

1.) Clone project somewhere inside the `vvv/www/` directory.
2.) `vagrant provision`

At this point the default provisioner for VVV, as well as each site's provisioning script, would run.

In the new process:

1) Add `my-site: https://github.com/user/my-site.git` to `vvv-custom.yml`
2) `vagrant provision`

Similar to the first example, the site repo will be cloned, the default VVV provisioner will run, and each individual site's provisioning script will run.

However, you could also do `vagrant provision --provision-with site-my-site` and only the new site's provisioner would run. You could also add `skip_provisioning: true` to another site's configuration so that when `vagrant provision` runs it does not fire that every time.

The flexibility gained by having a relatively simple configuration file is pretty great. Repos like [custom site template](https://github.com/Varying-Vagrant-Vagrants/custom-site-template) can be used to quickly spin up several sites of different flavors, all sharing the same base repository. It also makes it easier to remove some of the things that VVV includes by default, which speeds up provisioning even more.

I think over time it will make more and more sense. I've been really happy with how much easier it is to manage sites locally. There are probably some things you could add to `Customfile` or the pre/post provisioning process to bring back the old behavior, but I would recommend trying this out for a bit.

**Comment by khromov** [comment]
Great answer @jeremyfelt 

Really happy about being able to provision a single site with  `--provision-with`. I'll keep experimenting with v2. 😄
