### ISSUE TITLE
test1.dev goes to the dashboard

### ISSUE THREAD

**Issue by elebumm** [Varying-Vagrant-Vagrants/VVV#1142]
## Current Behavior
Domains go to dashboard rather than wordpress site. I tried uninstalling and using previous versions of VVV but I am unable to get this to work on my machine. I am new to vagrant so apologies if some things may be obvious.

## Your Environment

* VVV version: 2.0.0
* Vagrant version: 1.9.2
* VM Provider name: VirutalBox 
* VM Provider version: 5.1.14
* Operating System and version: Mac OS Sierra 10.12

**Comment by jeremyfelt** [comment]
Hi @elebumm, thanks for opening an issue. Can you share the contents of your `vvv-custom.yml` file so that we can see if there is a configuration problem?

**Comment by elebumm** [comment]
I am unable to find the `vvv-custom.yml` file. I do have a `vvv-config.yml` file.

**Comment by jeremyfelt** [comment]
Did you [add `test1.dev` as a site](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/) in `vvv-config.yml`?

**Comment by elebumm** [comment]
Yes. Here is the contents of my file:

sites:
  wordpress-default:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-default.git
    hosts:
      - local.wordpress.dev

  wordpress-develop:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    hosts:
      - src.wordpress-develop.dev
      - build.wordpress-develop.dev

  lessthan30:
    repo: https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop.git
    hosts:
      - lessthan30.dev

utilities:
  core:
    - memcached-admin
    - opcache-status
    - phpmyadmin
    - webgrind

**Comment by jeremyfelt** [comment]
Ahh, ok. The vvv-wordpress-develop repository is [hard-coded](https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop/blob/master/provision/vvv-nginx.conf#L11) in what sever names it will respond to.

You should be able to use the [custom site template](https://github.com/Varying-Vagrant-Vagrants/custom-site-template) with better results on the `lessthan30` configuration.

I would also recommend copying `vvv-config.yml` to `vvv-custom.yml` so that any future upstream changes are easier to merge.
