### ISSUE TITLE
Automatically install sites on multisite in custom-site-template

### ISSUE THREAD

**Issue by desrosj** [Varying-Vagrant-Vagrants/VVV#1144]
Was testing `custom-site-template` today, and found one feature that would be nice to have.

Currently, when you configure a multisite for provisioning, only the primary site is created. `multisite.dev` for example.

It would be nice to include a flag that would install sites specified in the configuration on the multisite instance.
`site1.multisite.dev`, `site2.multisite.dev` for example.

Talked through this with @LoreleiAurora, she skipped supporting this on purpose because of complications with unit testing when sites already exist. But if we add a flag, this could be accomplished.

**Comment by tomslominski** [comment]
In the meantime, would it make sense to point out in the readme for `custom-site-template` that this does not happen by default? I just spent a while wondering why my multisite network wasn't being created with additional sites as expected, before I found this and realised that they were not supposed to be created anyway.

**Comment by tomjn** [comment]
I can see this leading to unusual situations, e.g what happens if:

 - the user changes their domains from .local to .dev, does it destroy the entire install and recreate it? Rename the sites? How will it know which map onto what?
 - the user wants multiple domains mapped on to a single site, how do they configure the exception?
 - the user adds the flag and adds multiple sites, but it is not a multisite install, does it convert the site to a multisite install?
 - if a user removes a domain, should it destroy that site?
 - if the user adds a completely new domain that isn't a subdomain

So instead I would suggest the following:

 - This issue as is would change the meaning of the hosts section of the YAML file depending on context which is bad
 - You can already do something similar by not using the config file for extra sites, and instead making `vvv-init.sh` automatically create the nginx template and hosts file so that subdomains are automatically added on reprovision with no config changes necessary, [see here for how to do the Nginx part](https://github.com/Varying-Vagrant-Vagrants/custom-site-template/blob/master/provision/vvv-init.sh#L54), all that needs doing is adding the hosts WP CLI gives you to the hosts file of the VM

**Comment by tomjn** [comment]
Also, see https://github.com/Varying-Vagrant-Vagrants/VVV/blob/57cc18d6555cc9e036e63c0b301ab55a5492c0da/docs/en-US/adding-a-new-site/setup-script.md#L31 which auto-adds a dynamically generated host to the hosts file inside the provisioner

**Comment by benlumia007** [comment]
@tomjn 
assuming we add Multisite already, should this be closed.

**Comment by tomjn** [comment]
I suspect this was talking about multi-network sites, I'm not sure, but the `custom-site-template` was created after this and it supports creating multisites so there's nothing preventing the original ask with what's already available
