### ISSUE TITLE
Installed php 5.2.17 with phpbrew but phpinfo() says php is 7 in the plugin

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1232]
## Expected Behavior

Setting up php version to be 5.2 using phpbrew. 

## Current Behavior

I installed [phpbrew](https://github.com/phpbrew/phpbrew) inside my vagrant - I first typed `vagrant ssh` to access it, then after fixing all errors I got while installing it (installing missing dependencies) I made it work with

`phpbrew -d install 5.2.17 +default +openssl=shared -- --with-openssl-dir=/usr/include/openssl`

And then 

`phpbrew use php-5.2.17`

When I type `php -v` I got

```
PHP 5.2.17 (cli) (built: Jul  6 2017 10:29:50) 
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.2.0, Copyright (c) 1998-2010 Zend Technologies
```

In a plugin I am testing I added `phpinfo()`, and on the front, I can see the info and it says

`PHP Version 7.0.20-2~ubuntu14.04.1+deb.sury.org+1`

## Context

I'd like to change php version so that I can test if the plugin will gracefully exit if the php version of the server is lower than 5.3. 

`version_compare( PHP_VERSION, '5.3', '<' )`

## Your Environment
* VVV version: 2.0.0
* Vagrant version: Vagrant 1.9.4
* VM Provider name: VirtualBox
* VM Provider version: Version 5.1.22 r115126 (Qt5.6.2)
* Operating System and version: macOS Sierra v 10.12.5

**Comment by tomjn** [comment]
adding new PHP versions is done by setting the nginx upstream to the relevant version and adding that to the utilities section of `vvv-custom.yml`

https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/changing-php-version/

```
sites:
  example:
    nginx_upstream: php71

utilities:
  core:
    - php71
```

## PHP 5.2

The problem here is that adding `php52` to the utilities section won't work. The person who maintains the PHP packages has deliberately removed PHP 5.2 prebuilt packages, so there's nothing for VVV's utility provisioners to pull from. You can add it back in, but you'd need to script it to build from source in a custom utility

**Comment by tomjn** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1256 contains documentation for utilities that will help here, take a look at the official utilities repo for how it installs php53+

**Comment by tomjn** [comment]
I'm going to close this out, I would recommend looking at the core utilities and building a custom one. That will show you how to hook up PHP52 to nginx upstream, but it's not something VVV will directly maintain ( we won't stop you though )

**Comment by dingo-d** [comment]
Thanks for the explanation. I ended up installing Local by Flywheel, it's ok for the testing purposes, but this will help as well.
