### ISSUE TITLE
Move VVV docs to separate repo or the vvv.org repo

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1270]
Currently updating the docs is a pain in the arse. You got to cherry pick the commits from `develop` and merge them into `master`, then deploy after the pull request process

Instead, I propose they get moved to the https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org repository, making generating the docs simpler, then deploy automatically on change

I would also suggest adding a set of provisioner files and provisioning that repo in VVV with the URL http://docs.vvv.dev so that there's a browsable version of the VVV docs available on all installs. This would also make updating and testing the docs significantly easier

@jeremyfelt @LoreleiAurora  what're your thoughts?

**Comment by jeremyfelt** [comment]
I think this makes sense. The original thinking (if I recall correctly) was to make it easy to contribute to both in the same place *and* to have the docs versioned along with the core package.

At this point there's probably more value in being able to quickly deploy docs changes rather than trying to manage them as part of the core package. I think the only real catch is that we should continue managing docs issues on this repo and accept only pull requests on a new docs repo.

+1 from me. If there are no objections from @LoreleiAurora, I can work on getting the new repo and deploy setting up properly while doing the next point release stuff.

**Comment by LoreleiAurora** [comment]
+1, The current docs flow isn't really working.

**Comment by jeremyfelt** [comment]
Separated and deployed! 🎉  https://github.com/Varying-Vagrant-Vagrants/varyingvagrantvagrants.org/pull/22
