### ISSUE TITLE
Document the contribution workflow for documentation

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#1277]
VVV's `CONTRIBUTING.md` should make mention of varyingvagrantvagrants.org and how to contribute to the documentation on that site.

**Comment by cinghaman** [comment]
@jeremyfelt is there an updated link for this in documentation https://varyingvagrantvagrants.org/docs/en-US/migrate-vvv-1/ This is a 403 forbidden page

**Comment by tomjn** [comment]
@cinghaman it's https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/migrating-from-vvv-1-4-x/

keep in mind that all the docs are markdown files in a git repo under this org

@jeremyfelt it'd be great if we can get 404's working

**Comment by tomjn** [comment]
@cinghaman also, could you let us know where the link is so I can fix it?

**Comment by cinghaman** [comment]
The link is mentioned on this page: https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/ http://prntscr.com/hn90ox
And when do vvv.test the default page also has a wrong link.
As per docs there is a file vvv-nginx.conf under provision folder, but I don't see it, do we need to create it first?
As i migrated from VVV1 my nginx.conf is inside configs folder and one thing Migration docs is missing is that we need to also update configs/niginx/sites/your-site.conf file with the .test domain along with updating www/your-site/vvv-hosts file as well.
Can you please update that too for anyone else trying to go through the migration docs.

**Comment by tomjn** [comment]
@cinghaman can you create a new issue for this? This issue is for `contributing.md`. I created PR's for most of those

> As i migrated from VVV1 my nginx.conf is inside configs folder and one thing Migration docs is missing is that we need to also update configs/niginx/sites/your-site.conf file with the .test domain along with updating www/your-site/vvv-hosts file as well.

That's not a VVV 2 thing, that's a Google thing, and it impacts all users, including VVV 1 users, not just VVV users. Also you should not be modifying nginx files inside the VM. Making modifications inside the VM to configs etc is a huuge no no

**Comment by cinghaman** [comment]
Hi, @tomjn I was using vv create to make sites on a vagrant and possibly that's why all my site info were being created inside config/nginx-config/sites/my-site.conf, this file used to get created for any new site I would make with vv create the file.

I am already using the new VVV2 method of creating a site now. 

So looks like I won't need to make a issue ticket for that as it was I guess issue the way I created sites using vv create.

Thanks for looking into it.

**Comment by Mte90** [comment]
I think that we can close this ticket, we have a page in the documentation that is a work in progress.
https://varyingvagrantvagrants.org/docs/en-US/contribute/
