### ISSUE TITLE
Provide instructions for VIP Go setup

### ISSUE THREAD

**Issue by paulschreiber** [Varying-Vagrant-Vagrants/VVV#1308]
Automattic provides some instructions for VIP Go setup, but they're not complete, and only cover setting up one site: https://vip.wordpress.com/documentation/vip-go/local-vip-go-development-environment/

I have written a more thorough set of instructions and would like to have them included in the VVV documentation.

**Comment by paulschreiber** [comment]
I think adding a section between 3 and 4 would be the best approach, but am open to other ideas.

**Comment by tomjn** [comment]
The problem here is that we'd need a section for Pantheon then AWS then WP Engine, then every other host under the sun.

As a VIP Wrangler if you have improvements for our own docs we're more than happy to include them, we're currently undergoing a lot of discussion and work around the structure of our docs internally at the moment

As an aside, there is a VIP VVV repo under the Automattic org but it's currently unsupported and could use testing. There is an issue here about pulling it into the VVV org
