### ISSUE TITLE
PhantomJS architecture version

### ISSUE THREAD

**Issue by afercia** [Varying-Vagrant-Vagrants/VVV#1355]
I was testing the VVV generated with https://github.com/Varying-Vagrant-Vagrants/CD-USB-Generator/ for an incoming Contributor Day.

A couple days before I've normally run `npm install` in the directory where I've copied the CD-USB content, e.g. `~/my-dir/www/wordpress-develop/public_html` without errors.

Running `grunt prerelease` from outside the box, I got a "cannot execute binary file" error (I've shortened the paths for better readability):
```
Running "qunit:files" (qunit) task
Testing tests/qunit/compiled.html 
PhantomJS threw an error:ERROR
>> /node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: /node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: cannot execute binary file 0 [ '/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: /node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: cannot execute binary file' ]
Warning: PhantomJS exited unexpectedly with exit code 126. Use --force to continue.```
```

After some investigation, I've checked the phantomjs file:
```
$ file phantomjs 
phantomjs: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.26
```

That didn't look right to me. Linux? I'm on a macbook.

After a `npm rebuild` checked again the phantomjs file:
```
$ file phantomjs
phantomjs: Mach-O 64-bit executable x86_64
```

And finally `grunt qunit:files` ran without errors.

Is this correct? Does VVV comes with a phantomjs-prebuilt Linux version? Why a prebuilt version gets installed? Shouldn't build the proper platform version instead (during the first npm install)?

**Comment by afercia** [comment]
Reference: https://github.com/Medium/phantomjs#cross-platform-repositories

**Comment by jeremyfelt** [comment]
Hi @afercia, thanks for opening a ticket.

I'm not completely confident in this answer, but I have a feeling this has to do with the mix of running `npm` and/or `grunt` tasks inside and outside of the VM.

When `phantomjs` is installed in OSX, a different binary is provided than when `phantomjs` is installed in Ubuntu. When VVV first provisions, `npm install` is run in the context of its environment and will obtain the binaries used for `phantomjs` in Ubuntu. When you exit the VM and run it from your OSX environment, you'll see a binary error. Rebuilding retrieves the OSX binary but will mean that running the task inside the VM will now fail.

`npm rebuild` is probably a good answer for this to meet a workflow that runs `grunt` inside and outside the VM. Otherwise I would recommend picking one environment and using that most of the time.

Aside: You just commented with the docs that probably explain this better than me. :)

**Comment by jeremyfelt** [comment]
> Does VVV comes with a phantomjs-prebuilt Linux version? Why a prebuilt version gets installed? Shouldn't build the proper platform version instead?

To clarify here - VVV does not provision `phantomjs` itself. NPM picks the platform specific dependency while processing `wordpress-develop`'s `package.json` file. I think `grunt-contrib-qunit` is the actual package that requires `phantomjs` in this instance.

I'm going to close this out as I don't think it's a VVV issue. Happy to reopen if necessary though.

**Comment by afercia** [comment]
@jeremyfelt thanks. Yep I was expecting to have all the npm and grunt tasks fully working _outside_ of the VM, since the VVV built with the CD-USB script is meant to be used at contributor days and I think beginners are not so familiar with ssh'ing into the VM and running stuff from there.
Thanks for your explanation. After our conversation on Slack I realize that, on the other hand, in order to run things outside of the VM, the attendees should likely install additional software (node, phpunit) outside of the VM so that's not ideal during a contributor day.

Aside: if the vvv.zip generated by https://github.com/Varying-Vagrant-Vagrants/CD-USB-Generator/  is meant to be a fully-functional ready to use VVV, then the default memory for the VM should be increased as 1024 is definitely not sufficient to run the tests.

**Comment by tomjn** [comment]
@afercia what would you recommend? Are you happy doing a PR for this? VM memory can be configured via `vvv-custom.yml`

**Comment by afercia** [comment]
@tomjn that's what I've done when testing the VVV prepared for the Milano contributor day
```
vm_config:
  memory: 2048
```
My point is that everything should work out of the box during a contributor day, will open a new issue 🙂
