### ISSUE TITLE
directory mapping like VVV1

### ISSUE THREAD

**Issue by jimlongo56** [Varying-Vagrant-Vagrants/VVV#1363]
I previously used VVV1 and could have a folder on my desktop (wp-content) and map that to the wp-content folder in /srv/www/mysite/wp-content.

How would I configure that with VVV2?

For a website build it was a really good git workflow.  All you want is the wp-content folder in your git repo.  You sync that wp-content folder to whatever stable version VVV is provisioned.  And you could reprovision without any worries about losing your work.

Does anyone have any git workflows they want to share, maybe I'm missing something in how VVV2 makes this easy.

**Comment by tomjn** [comment]
## Reprovisioning

> For a website build it was a really good git workflow. All you want is the wp-content folder in your git repo. You sync that wp-content folder to whatever stable version VVV is provisioned. And you could reprovision without any worries about losing your work.

I've never lost code during a reprovision, so I'm unsure what you're doing here that would do that. VVV 2 can even checkout a git repo for you so you don't have to create a folder etc, and all the default sites in VVV are git repos

Eitherway it sounds like you're going to great lengths so that you can put a folder on your desktop. There's no reason you couldn't just clone the folder into the `public_html` of a site using https://github.com/Varying-Vagrant-Vagrants/custom-site-template

You could even fork the custom site template and modify the provisioner script to do the `git clone` for you to save a manual step 

## Mapping Folders

I don't believe VVV1 had any direct support for this at all, perhaps you're thinking of **symlinks**? If synlinks work in VVV1 there's no reason they wouldn't work in VVV2. Eitherway here are some clarifications/options:

### Via `vvv-custom.yml`

You can't map individual subdirectories of a site, though you can change the directory of the entire site, and the folder that gets served by Nginx

e.g. for a site `banana` VVV will use the `www/bannana` subfolder for the site, and `/srv/www/banana` inside the VM. But with the `local_dir` and `vm_dir` keys defined for a site, you can change the folder VVV uses both inside and outside the VM, e.g:

```
sites:
  - banana
    local_dir: /Users/username/Desktop/banana
    vm_dir: /srv/www/banana
```
Keep in mind that this will change the sites folder, as in the entire thing, not a section or sub-portion of the site. VVV will try to load a provisioner script from `/Users/username/Desktop/banana`, checks for a hosts file, Nginx config etc

### Custom Vagrant Files

You can do it this way but it will be more complicated and it moves beyond the area that we can support
