### ISSUE TITLE
enable Tidy for php

### ISSUE THREAD

**Issue by shanebp** [Varying-Vagrant-Vagrants/VVV#1385]
I'm trying to get the Tidy php extension working in my VVV install. 

I've added Tidy, this is the ssh log: 
https://gist.github.com/shanebp/e37c260667e91be1d8d111e306dbcf40

And added `extension=tidy.so` to ` C:\vagrant-local\config\php-config\php7.0-custom.ini`

But it is still not working.  Any suggestions ?

Also tried adding `extension=tidy.so` to   `C:\vagrant-local\config\php-config\php7.0-www.conf`  - still not working.

**Comment by tomjn** [comment]
Note that because you never specified which version of PHP, it assumed the latest and installed the PHP 7.1 version, yet you modified the PHP 7.0 ini

```
The following extra packages will be installed:
  libtidy5 php7.1-common php7.1-tidy
The following NEW packages will be installed:
  libtidy5 php-tidy php7.1-common php7.1-tidy
```

Installing `php7.0-tidy`, or switching the site to PHP 7.1 should resolve it.

As an aside, if you want to install things inside your VM, you're supposed to use a utility. Right now all your installed extras will be nuked when you next rebuild the box. A utility is pretty simple, a git repo with folders containing a `provision.sh` that runs on provision. Use that to update/install your extensions

**Comment by shanebp** [comment]
Thank you.
