### ISSUE TITLE
Unable to access http://vvv.test

### ISSUE THREAD

**Issue by amallory** [Varying-Vagrant-Vagrants/VVV#1390]
## Expected Behavior
I expect to be able to access http://vvv.test in chrome once "vagrant up" has completed. I am not seeing any host file entries in /etc/hosts.

## Current Behavior
getting "vvv.test’s server IP address could not be found." in Chrome when accessing http://vvv.test. In addition /etc/hosts is not showing any entries besides default localhost values. I see no attempt from "vagrant up" to add host entries.  I am not prompted to enter system password to allow updates.

## Context
Been using vvv for some time but haven't used it recently updated VirtualBox and this is a fresh install of VVV.

## Your Environment
* VVV version: 2.1.0
* VVV Git Branch: master
* Vagrant version: 1.9.5
* VM Provider name: VirtualBox
* VM Provider version: 5.1.30
* Operating System and version: OsX 10.12.6

**Comment by tomjn** [comment]
Thanks for reporting :) I would ask to see your vagrant plugin list, but given you're running 1.9.5, I'd like you to;

 - halt the VM
 - download vagrant 2.0.1, and use the uninstall vagrant tool
 - install Vagrant 2.0.1 ( there's a potential issue if you don't use the uninstall tool re: bundler )
 - reinstall the vagrant triggers/hosts updater plugins
 - test again, and pipe the log output to a file so we can see the results if it doesn't work

**Comment by amallory** [comment]
Thank you for the amazingly fast response, appreciate it.

Updating to Vagrant 2.0.1 using the (overlooked the first time) uninstall tool provided with the Vagrant install and installing/updating the triggers and hosts updater plugins did the trick! I'm up and running on the the next challenge... 

Thank you for the assistance @tomjn

**Comment by Kluny** [comment]
I'm having this problem as well. 

**Expected Behavior:**

I expect to be able to access http://vvv.test in chrome once "vagrant up" has completed. 

**Current Behavior:**

Getting "vvv.test’s server IP address could not be found." in Chrome when accessing http://vvv.test. 

**Context**

I used Chassis with Vagrant in November and December but hadn't touched it since just before Christmas. I first installed VVV this morning in a directory that already contained the (working) Chassis build - that may have something to do with the problem, since the Chassis build stopped working as well. 

One thing I didn't try is "reinstall the vagrant triggers/hosts updater plugins" as I don't know what that means. 

**Environment:**

VVV version: 2.1.0
VVV Git Branch: master
Vagrant version: 2.0.1 (did an uninstall and reinstall using the uninstaller tool, after reading this thread)
VM Provider name: VirtualBox
VM Provider version: 5.1.30 (previously I had 5.1.18, but I updated it in case that was the problem)
Operating System and version: OsX 10.12.6

**Comment by tomjn** [comment]
You can't install VVV over the top of Chassis, it'll break both VVV and Chassis. You're going to have to clean up the folder, reinstall Chassis, then install VVV in another folder.

> One thing I didn't try is "reinstall the vagrant triggers/hosts updater plugins" as I don't know what that means.

There should be instructions on the VVV website for installing the vagrant plugins. If you don't have these installed, VVV can't modify your hosts file, hence vvv.test not found.

**Comment by Kluny** [comment]
> There should be instructions on the VVV website for installing the vagrant plugins. If you don't have these installed, VVV can't modify your hosts file, hence vvv.test not found.

Ah, it was steps 1 and 2 on this page - https://make.wordpress.org/core/handbook/tutorials/installing-a-local-server/installing-vvv/

Thanks Tom!

**Comment by Dillweed5446** [comment]
Hi, I'm having the same issue.  vagrant up has run successfully, but I am still unable to access http://vvv.test.  This is my first time trying this.  I've installed the necessary plugins, but I am getting the error vvv.test’s server IP address could not be found.

**Comment by Dillweed5446** [comment]
Hi, I'm having the same type of issue.  I've followed steps 1-4  from https://make.wordpress.org/core/handbook/tutorials/installing-a-local-server/installing-vvv/, but I'm still getting the "vvv.test’s server IP address could not be found" error.  I've made sure that the "vagrant-hostsupdater" plugin has been installed, and vagrant up has been run.  "vagrant up" never asked for a password, not sure if that will affect anything.  This is my first time using this program.

**Comment by tomjn** [comment]
@Dillweed5446 can you open a new issue with all the relevant info? This one got closed in 2017

Also, did you try using the official instructions on the VVV site instead of the .org instructions?

**Comment by Dillweed5446** [comment]
Yes, I'm using the VVV site instructions.  I'll open a new issue.

**Comment by opeaderin** [comment]
hello I'm also having the same problem. My vagrant runs as normal and appears to have no errors, however when i run the test on the browser it displays the error -  server IP address could not be found.
is there some that could please help with this ASAP?

**Comment by tomjn** [comment]
Is this a brand new VVV install or an existing one? Can you provide as much
detail as possible about your operating system and software versions? And
if you can get me a copy of what your terminal/prompt says?

**Comment by opeaderin** [comment]
![image](https://user-images.githubusercontent.com/45354875/71046861-94b18f00-2131-11ea-80c8-765e511cc288.jpg)

**Comment by opeaderin** [comment]
That’s the error i keep receiving the version for vagrant is 2.2.6 and the version of virtual box is 6.1.0

**Comment by opeaderin** [comment]
![image](https://user-images.githubusercontent.com/45354875/71046993-04c01500-2132-11ea-942e-9a2993cf4d34.jpg)

**Comment by opeaderin** [comment]
So I entered some code and found this error
![image](https://user-images.githubusercontent.com/45354875/71048749-27edc300-2138-11ea-91b2-0deea18c5979.jpg)

**Comment by Mte90** [comment]
Vagrant don't support yet virtualbox 6.1, I know that they will release a new version soon with the fix, I had to patch manually to support that version.
Also you don't need the `;` for command inside the prompt, because this can be interpreted as parameter and break the tool behavior.

Also as Tom said, can you reply about if you are using VVV?

> Is this a brand new VVV install or an existing one?

**Comment by opeaderin** [comment]
Sorry I’m not sure what VVV is ?

**Comment by tomjn** [comment]
@opeaderin VVV is this project, this is not generic vagrant support.

Unless you're trying to use VVV, this is not the place for you, if you want to report bugs in `vagrant` you should have gone to https://github.com/hashicorp/vagrant

**Comment by opeaderin** [comment]
Ohh well I’ve actually solved my problem but thankyou very much for the quick replies
