### ISSUE TITLE
Make dashboard modification ready, not just completely override ready

### ISSUE THREAD

**Issue by webmandesign** [Varying-Vagrant-Vagrants/VVV#1391]
## Expected Behavior
When I create a custom dashboard and I would like to only slightly modify the default dashboard, I should not be forced to copy-paste the code from default dashboard file into my custom one. That is not future-compatible anyway.

## Current Behavior
I am only allowed to bypass the default dashboard code with custom one, with no option to only modify the default dashboard.

## Possible Solution
Create a separate `dashboard-default.php` file and include it in the `index.php` when we have no `dashboard-custom.php` file. That way we allow including `dashboard-default.php` within `dashboard-custom.php` and modifying output with search-replace using PHP buffer, for example.

**Comment by tomjn** [comment]
That sounds significantly more complicated than just copying the file. What exactly are you trying to achieve in your modifications?

Keeping in mind that the nature of the dashboard may change in the future, the goal is to have more interactive elements to assist users in the creation of sites, which will place a JS angle on things.

I'd also expect that if the PHP becomes more structured with the intention of templating as this request desires, then it would likely involve either a pure React solution, or moving towards a more modular setup with Silex or another small framework.

**Comment by webmandesign** [comment]
@tomjn Thanks for the reply. I've actually went ahead and created a pull request fixing this issue. Please see https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1392

**Comment by tomjn** [comment]
@webmandesign can you provide an example use case for this? I'm struggling to think of a use case that couldn't just be made as a pull request to this repo or a custom dashboard

**Comment by webmandesign** [comment]
Very _fast and dirty_ example:

I would like to make my sites links HTTPS instead of HTTP, so, using my proposed solution, I can simply put this code into `dashboard-custom.php` file:
```
<?php

ob_start();
include( 'dashboard-default.php' );

echo str_replace( 'http:', 'https:', ob_get_clean() );
```

That way I know the future versions (new layouts) of default dashboard will not get completely overrode with my custom dashboard and I only change what I need.

**Comment by tomjn** [comment]
Ah I wish you'd raised that as a feature request, and I can see now why you might want this, at the same time this could well put a spanner in the works by locking the dashboard into its current implementation.

My hope in the future is to move the individual sections out into modules, so that those uninterested in certain boxes can disable them. With that you could put your own module in and disable the one it replaces

I'd also like to think that in the future you could specify an SSL certificate, and the dashboard would pick up on it and change it to `https`

**Comment by webmandesign** [comment]
Yes, moving sections into separate modules (files) would help too. Maybe we could control the modules display with `.yml` file then? And make it possible to use custom module override PHP files? Probably I'm asking for too much ;) Anyway, my solution works for me perfectly fine.

But I came up with this solution to make modifications both backwards and forwards compatible, as when I updated the VVV now, I've noticed that I miss a lot from current dashboard, when I was overriding it with my custom one only to make the links HTTPS...

So, this is just my proposition on improvement. Obviously, if you plan to do modules in the future, go ahead and close this issue.

Thanks for your time! 👍

**Comment by tomjn** [comment]
@webmandesign you can set the dashboard now via `vvv-custom.yml` in the `develop` branch:

```
dashboard:
  repo: git repo goes here
  branch: master
```

**Comment by webmandesign** [comment]
@tomjn Thank you for working on this!

However, I'm a bit confused now. I understand there is no documentation on this update yet. But it seems to me that there is no way of overriding a single information of the dashboard, only the whole dashboard still.

From what I understand, now you can override the entire dashboard with your own from external repo just by setting it up in `vvv-custom.yml` file. Am I correct here?
_If so, how can I only override a specific single block of the dashboard, for example?_

> My hope in the future is to move the individual sections out into modules, so that those uninterested in certain boxes can disable them. With that you could put your own module in and disable the one it replaces.

I can see this can not be set in `vvv-custom.yml` so I dug deeper ;)

The new dashboard seems to be provisioned/downloaded from https://github.com/Varying-Vagrant-Vagrants/dashboard repo, where blocks are separated. However, I'm unable to find a functionality to override any single block/information there.
_Am I missing something?_

I can also see [you have implemented my solution for dashboard](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/73db7579408a817306c3ad0d00d6fd1ddd994bcb/www/default/index.php) too.
_But I presume this will not make to next VVV release and will be removed in favor of above, right?_

So, if you have time, could you please explain how can I override a single block of the dashboard and yet keep it future-proof, meaning whenever a new dashboard layout/design is implemented, I get that too with VVV update, but my block overrides will still apply (I understand I might also need to update my custom block code, which is obviously better than updating whole dashboard code to new version ;) )?
Surely I understand if you don't explain the mechanism here and leave it for the release, no worries!

**Comment by tomjn** [comment]
> However, I'm a bit confused now. I understand there is no documentation on this update yet. But it seems to me that there is no way of overriding a single information of the dashboard, only the whole dashboard still.

The old dashboard custom code is still there, the repo changes the `dashboard` subfolder.

> From what I understand, now you can override the entire dashboard with your own from external repo just by setting it up in vvv-custom.yml file. Am I correct here?
> If so, how can I only override a specific single block of the dashboard, for example?

See `index.php`:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/www/default/index.php#L8

```
if ( file_exists( 'dashboard-custom.php' ) ) {
	include( 'dashboard-custom.php' );
	exit;
}
include( 'dashboard/dashboard-default.php');
```

Create a `dashboard-custom.php` and make it load all the files the default dashboard does, but with `dashboard/` infront on the `require` statements, and the ones you dislike removed.

> My hope in the future is to move the individual sections out into modules, so that those uninterested in certain boxes can disable them. With that you could put your own module in and disable the one it replaces.

This was done a while ago, each box is implemented by its own PHP file in a `php` subfolder

> I can see this can not be set in vvv-custom.yml so I dug deeper ;)
> 
> The new dashboard seems to be provisioned/downloaded from https://github.com/Varying-Vagrant-Vagrants/dashboard repo, where blocks are separated. However, I'm unable to find a functionality to override any single block/information there.
> Am I missing something?

The dashboard at that location is literally the same dashboard, to create it I filtered the repository down to that subfolder then pushed to a new git repo. The only change is that it's now in a different repository. This should make life easier for those working on improvements to the dashboard, and those who use a completely different dashboard

> I can also see you have implemented my solution for dashboard too.
> But I presume this will not make to next VVV release and will be removed in favor of above, right?

The two coexist, and serve somewhat different purposes.

> So, if you have time, could you please explain how can I override a single block of the dashboard and yet keep it future-proof, meaning whenever a new dashboard layout/design is implemented, I get that too with VVV update, but my block overrides will still apply (I understand I might also need to update my custom block code, which is obviously better than updating whole dashboard code to new version ;) )?

See the above, however, this new functionality provides a new method:

 - fork the dashboard
 - add the official dashboard repo as a git remote
 - create a new branch, and put your changes in there
 - modify `vvv-custom.yml` to use your forked repo and the branch with changes

Then to update:

 - fetch the changes
 - rebase your branch on to the newly updated `master`/`develop`

At that point you might have a merge conflict or two but this should be insignificant if all your doing is commenting out includes to get rid of blocks

> Surely I understand if you don't explain the mechanism here and leave it for the release, no worries!

Happy to help

---

A few notes on the future

The current direction of the dashboard is React based, and that involves a design change. Rather than having everything on the one page, there'll be a sidebar menu, with sites as the first page. I'm undecided if tools should be menu options or on a tools page, but it'll allow the UI to be more focused.

For example, in the future, sites will be listed in a single row, with a filter, and only show the hosts, name and description. You'll need to click an expand/settings/info button to show all the other options.

What's more there's no reason some blocks couldn't become dismissable

To see a WIP preview, try out the `react_dash` branch, it's very WIP at the moment though.

---

Notes on vvv-custom.yml

I could add dashboard options, but it would complicate PHP code, especially when some of those items are moving to React. It also makes no sense if you choose to use a different dashboard, and a support burden if people use those then get surprised when the default dashboards options don't function

---

You can also use a userscript or extension to add CSS to hide the blocks you don't want. It might need IDs adding to the containers, but that sounds like a reasonable thing to add, PR's welcome

**Comment by webmandesign** [comment]
Ah, wou! Thank you for the explanation @tomjn! Now it's all clear to me.

My mistake was I haven't realized the https://github.com/Varying-Vagrant-Vagrants/dashboard was a repo for `dashboard` **subfolder**.

In this case I can see it's perfectly implemented and I can actually do all of my dashboard modifications (and more if I wanted :) ) and stay future-compatible. Very cool!

Thank you!
