### ISSUE TITLE
vmware support: netsensia/ubuntu-trusty64 box is no longer available

### ISSUE THREAD

**Issue by mikejolley** [Varying-Vagrant-Vagrants/VVV#1399]
Looks like this box is no longer available causing a 404 error on first vagrant up.

https://app.vagrantup.com/netsensia/boxes/ubuntu-trusty64

Download URL 404 https://dl.dropboxusercontent.com/u/63777076/VM/netsensia/vagrant/trusty64/NetsensiaTrusty64VagrantVMware.box

I worked around by finding an alternative box with vmware support and editing the vargrantfile.

**Comment by tomjn** [comment]
Which box did you end up using? Would you be ok doing a PR with the vagrant file change?

**Comment by mikejolley** [comment]
@tomjn After commenting, vmware gave me grief so I wasn't able to provision any :( Linux newbie :) 

Ended up going back to virtualbox.

**Comment by codebymikey** [comment]
Available vmware boxes can be seen here: https://app.vagrantup.com/boxes/search?provider=vmware&q=trusty

I ended up using `puphpet/ubuntu1404-x64` and it worked fine.

It is a little annoying that VVV is still restricted to VirtualBox 5.0 though. Especially since VirtualBox `<5.1.24` [doesn't seem to work](https://www.virtualbox.org/ticket/16890) properly on [Windows Insider Builds](https://www.virtualbox.org/ticket/16892).

Also, to avoid specifying `--provider=vmware_workstation` all the time. It'd be nice if the provider could be set in the `vvv-custom.yml` file like this. It should probably be documented in the `vvv-config.yml` file:

```yaml
# Specify the provider to use for VVV.
# It defaults to virtualbox or whatever is set in your 
# VAGRANT_DEFAULT_PROVIDER environment variable
vagrant_provider: vmware_workstation
```

And the patch for the updated `Vagrantfile` is as follows:

```patch
Index: Vagrantfile
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- Vagrantfile	(revision 710f08527730bbeea5b263cd6e6ff1614cb224ea)
+++ Vagrantfile	(revision )
@@ -30,6 +30,11 @@
 
 vvv_config = YAML.load_file(vvv_config_file)
 
+if defined? vvv_config['vagrant_provider'] then
+  # Override or set the VAGRANT_DEFAULT_PROVIDER environment variable.
+  ENV['VAGRANT_DEFAULT_PROVIDER'] = vvv_config['vagrant_provider']
+end
+
 if ! vvv_config['sites'].kind_of? Hash then
   vvv_config['sites'] = Hash.new
 end
@@ -159,12 +164,14 @@
 
   # The VMware Fusion Provider uses a different naming scheme.
   config.vm.provider :vmware_fusion do |v, override|
-    override.vm.box = "netsensia/ubuntu-trusty64"
+    override.vm.box = "puphpet/ubuntu1404-x64"
+    # v.gui = true
   end
 
   # VMWare Workstation can use the same package as Fusion
   config.vm.provider :vmware_workstation do |v, override|
-    override.vm.box = "netsensia/ubuntu-trusty64"
+    override.vm.box = "puphpet/ubuntu1404-x64"
+    # v.gui = true
   end
 
   # Hyper-V uses a different base box.

```

**Comment by tomjn** [comment]
> It is a little annoying that VVV is still restricted to VirtualBox 5.0 though. Especially since VirtualBox <5.1.24 doesn't seem to work properly on Windows Insider Builds.

I'd advise using the latest version, anybody who isn't using the latest who has an issue gets told to use the latest anyway, and it'd be a mammoth task to continuously test all combinations of all platforms and versions of virtualbox.

I would keep in mind that vmware/hyper-v aren't super supported in the sense that at some point someone needed or wanted to use them, but that's no longer the case. Parallels is only supported because @LoreleiAurora has it

Can you create a pull request for those changes?

**Comment by codebymikey** [comment]
> I'd advise using the latest version

Latest version of VVV or VirtualBox? I had the latest version of VirtualBox installed (5.2) but it only just dawned on me that I was running on the `master` branch rather than `develop`.

> Can you create a pull request for those changes?

Will try and create one in a couple hours.

**Comment by tomjn** [comment]
> Latest version of VVV or VirtualBox? I had the latest version of VirtualBox installed (5.2) but it only just dawned on me that I was running on the master branch rather than develop.

All of them, VVV `master` is the current stable release, although `develop` tends to be quite stable and has more fixes. VVV releases require quite a bit of effort I'm told. It's always assumed you're using the latest VirtualBox and Vagrant
