### ISSUE TITLE
Frequency in which VVV writes to hosts file

### ISSUE THREAD

**Issue by cagross** [Varying-Vagrant-Vagrants/VVV#1405]
This is probably more of a question regarding default behavior, rather than an issue.

Vagrant writes to my hosts file every time I run ‘vagrant up,’ and removes those entries from the hosts file whenever I run ‘vagrant halt’ or ‘vagrant suspend.’  Is there a way to keep those entries in the hosts file, rather than adding/removing them on every session?  I seem to remember in the past not having to modify the hosts file on every login, but I could be wrong.

The only reason I ask is because in order to give VVV permission to edit the host file, I need to be sure to first open my command prompt with admin privileges.  I can automate that step if need be, but I'd just like to be sure this is necessary before doing so.

I should note that I do have the vagrant-hostupdater plugin installed.  I'm not sure if that is causing the behavior I'm experiencing, or if I'm seeing default VVV behavior.

Thanks.

## Steps to Reproduce (for bugs)

1.  Run `vagrant up.`
2.  Run `vagrant suspend` or `vagrant halt`.
3.  
4.

## Your Environment

* VVV version:   2.1.0-73-g6a86225
* VVV Git Branch:   Appears to be 'develop.'
* Vagrant version:  2.0.1
* VM Provider name:   VirtualBox
* VM Provider version:  5.2.2 r119230 (Qt5.6.2)
* Operating System and version:  WIndows 10, x64.

**Comment by tomjn** [comment]
Vagrant hosts updater is what modifies the hosts file. VVV doesn't touch it itself, and only does what the hosts updater file requires

Instead, this looks like an XY problem, where you come up with solution Y to problem X, then ask about a problem with Y, rather than how to do X. So I'm going to address X instead, **"How do I avoid having to type a password in/start an admin console every time I vagrant up/halt?"**

The answer is:

 - you either run vagrant as an administrator via `sudo`, or keep the elevated priv console open
 - or you modify the permissions of the hosts file so that elevated priviledges aren't necessary

The latter is easier on non-Windows systems, I don't know how you would do it though.

As for your original question, copy paste the hosts entries out of the hosts file, then paste them back in without the vagrant comments. This leads to new problems however:

 - vagrant will still try to modify the hosts file
 - if succesful you'll end up with duplicates
 - there's no guarantee that the IP it uses will remain the same

As an additional note, you're using vbox 5.2.2 but 5.2.6 is available.

---

Personally, I start VVV then leave it running. It turns itself off when my battery is <5% or I reboot to install an OS update. There's no reason for me to have multiple instances of VVV, and it's lightweight enough that I just leave it on all the time

**Comment by cagross** [comment]
@tomjn OK thanks for that.  I have one follow-up question.  

>> "How do I avoid having to type a password in/start an admin console every time I vagrant up/halt?"

This is indeed the issue I wanted to address--thanks for that.  

>> This leads to new problems however:
>> vagrant will still try to modify the hosts file
>> if succesful you'll end up with duplicates
>> there's no guarantee that the IP it uses will remain the same

OK great--this is actually the information I was trying to ascertain:  the drawbacks of copying/pasting into my hosts file.  I'll move forward with using an elevated command prompt then.

**Comment by tomjn** [comment]
One possible alternative is to use a custom DNS server, but I don't know how you would set that up, it would be separate to VVV

**Comment by tomjn** [comment]
There's also this, which might remove the need for an elevated command prompt:

https://superuser.com/a/1003991/21807

Note that there are security consequences as any app can now write to your hosts file

**Comment by cagross** [comment]
OK thanks for the tips.  I discovered that in Windows, it's quite easy to instruct a shortcut to always open with admin privs.  See [this link](https://technet.microsoft.com/en-us/library/ff431742.aspx) for instructions.  The instructions say they are for Windows 7, but they also apply to Windows 10.
