### ISSUE TITLE
VM Configuration Error

### ISSUE THREAD

**Issue by mglona** [Varying-Vagrant-Vagrants/VVV#1413]
I'm taking up Udacity's Introduction to Programming Nano Degree Program and I'm on the back-end development path. I'm downloading the VM configuration and after a while it threw this error:
"An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 60"

How do I fix this?

Vagrant Version: 2.0.2
OS: macOS 10.12
vm provider: Virtual Box

**Comment by tomjn** [comment]
Can you outline the steps you took that resulted in this? As well as the surrounding logs for context. Without any surrounding context it's difficult to ascertain where that error happened, it could be Vagrant, or it could be a process inside the VM, since OpenSSL is used in a lot of places by a lot of things. It may even be an error on the host machine

**Comment by tomjn** [comment]
A little further googling indicated that this is a certificate authority issue, likely a network dropout or disruption of some sorts. Reprovisioning will probably do the trick, but without further information it isn't possible to help. You provided no logs and it isn't clear at which point this happened as a result

Since I asked for more details in February, and it's April now, with no response, I'm going to mark this as closed. If you're still trying to use this, comment back with the additional info
