### ISSUE TITLE
Custom styling dashboard?

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1440]
I was wondering is it possible to style dashboard per user, the same way you add custom sites? A config file that can change certain backgrounds or even a `custom.css` file of sorts?

Why am I asking about this? I have my sites put in subfolders - personal, client, company etc. and in them, I have all the sites that are related to that category.
So when I open my dashboard I see all the sites ordered probably the way they are ordered in the yaml file. It would be great when I could give each subfolder his color, for easier distinguishability.

Also is it possible to customize the dashboard? Set the ordering, add dividers, add additional links to each box, add items to sidebar etc? Didn't find anything about this in the docs.

**Comment by tomjn** [comment]
You can use your own dashboard by adding the following to `vvv-custom.yml`:

```
dashboard:
  repo: https://github.com/Varying-Vagrant-Vagrants/dashboard.git
  branch: react_dash
```

It's not documented as it was added to `develop` very recently and this is how I would recommend doing it, as you can pull down updates, make your customizations in a new branch, and rebase it onto `master` to bring in the updates

You can also create a custom loader file, the dashboard bootstrap tries to load the main dashboard file from the `dashboard` subfolder, but if you instead create a custom file, it will load that instead. From there you can copy paste the contents of the main dashboard file into it, add the extra `dashboard/` folder to the includes, then remove/add as necessary.

This is the code that loads the dashboard in `www/default/index.php`:
```
if ( file_exists( 'dashboard-custom.php' ) ) {
	include( 'dashboard-custom.php' );
	exit;
}

include( 'dashboard/dashboard-default.php');
```



However, I'm more interested in the need to tag and categorize. Especially given that the future development direction of the dashboard is leaning heavily towards a React UI, so I wonder if doing something like the following would be more useful:

```
  gutenberg:
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template
    skip_provisioning: false
    hosts:
      - gutenberg.test
    tags:
      - core
      - testing
```

Then surfacing those in the dashboard? Perhaps as badges with the tag name inside and an auto-generated colour?

**Comment by tomjn** [comment]
Some extra notes

> Also is it possible to customize the dashboard? Set the ordering, add dividers, add additional links to each box, add items to sidebar etc? Didn't find anything about this in the docs.

 - Filtering of the sites list is planned in the React UI
 - Not sure where you would want to add dividers, but the plan is to add a sidebar menu and move a lot of things onto brand new pages, rather than having it all on the same screen
 - I'm not sure which additional links you'd want to add to boxes, can you ellaborate? I guess a custom dashboard section could be read that takes a label/url pair and adds it under a custom box
 - Adding things to the sidebar can be done via the `dashboard-custom.php` but as I mentioned, that sidebar is going away in the future


As far as documentation is concerned, I intend to document both methods for replacing the dashboard, but I trust anybody working on a custom dashboard knows basic PHP and can surmise the rest from reading the code.

I'd also prefer that people make modifications that are general enough to feed back to VVV, rather than sitting on local machines unshared. You don't need to customise the dashboard if your customisations make it into VVV core

**Comment by dingo-d** [comment]
Thanks for the suggestions and explanations :)

* Dividers would be set between each subfolder inside `www` folder. You could have `wordpress` folder with `defaults`, `develop` and `meta` for instance, then `clients` folder for your clients sites etc. Then the dividers would physically divide the boxes (better visibility). Currently they are stacked one after another.
But if you could customize the UI, and put all on separate tabs/pages then that would be good as well.

* Additional links like login link for instance, or some other useful link (default REST endpoint or something like that).
Label/url pair would be a good way to add this.

<img width="931" alt="screen shot 2018-02-27 at 12 47 46" src="https://user-images.githubusercontent.com/8638515/36727144-7b3f4070-1bbc-11e8-9fc1-35d59eecccba.png">

I'll look into the code you provided and see what I can customize, and if it looks/feels ok, I'll fork and create a PR :)
