### ISSUE TITLE
Set up a test cron job that is calling a file

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1441]
## Expected Behavior
Cron job should run and `debug.log` should be populated by test message.

## Current Behavior
No `debug.log` but I see a mail in vagrant.

## Steps to Reproduce (for bugs)
Have a test php file, say on wordpress-default twentyseventeen theme called `test.php`. With debug enabled

```php
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
```

```php
<?php

function my_test() {
  error_log( print_r( 'TESTING CRON', true ) );
}

my_test();
```

ssh into vagrant and set up a cron job to run every minute:

```sh
vagrant ssh
crontab -e

// Enter in the nano or what ever editor you are using

*/1 * * * * /vagrant/www/wordpress-default/public_html/wp-content/themes/twentyseventeen/test.php >/dev/null
```
Save and wait for one minute.

## Context
I'd like to test if the script that will be run on cron job on the real server works. The `debug.log` is not being created, but I got mail that said:

```sh
Return-Path: <vagrant@vvv>
X-Original-To: vagrant
Delivered-To: vagrant@vvv
Received: by vvv (Postfix, from userid 1000)
	id B77B4609A9; Wed, 28 Feb 2018 11:36:01 +0000 (UTC)
From: root@vvv (Cron Daemon)
To: vagrant@vvv
Subject: Cron <vagrant@vvv> /vagrant/www/wordpress-default/public_html/wp-content/themes/twentyseventeen/test.php >/dev/null
Content-Type: text/plain; charset=ANSI_X3.4-1968
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/vagrant>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=vagrant>
Message-Id: <20180228113601.B77B4609A9@vvv>
Date: Wed, 28 Feb 2018 11:36:01 +0000 (UTC)

/bin/sh: 1: /vagrant/www/wordpress-default/public_html/wp-content/themes/twentyseventeen/test.php: Permission denied
```

So cron works, kind of? Even though ` >/dev/null` should prevent the sending of the mail. How do I test if my function will run on cron? When I run it by going to the url in the browser (http://local.wordpress.test/wp-content/themes/twentyseventeen/test.php) and put `echo` in the function I can see the output so there is no error in the code.

## Your Environment

* VVV version: 2.1.0
* VVV Git Branch: develop
* Vagrant version: Vagrant 2.0.2
* VM Provider name: VirtualBox
* VM Provider version: Version 5.2.6 r120293 (Qt5.6.3)
* Operating System and version: macOS High Sierra v10.13.3 (17D102)

**Comment by tomjn** [comment]
`test.php` in your example does not load the WP environment, so anything in your `wp-config.php` is irrelevant. The file is self contained and standalone.

I would strongly advise against using a standalone PHP file this way in general, especially one placed in the theme ( functionality goes in plugins ). Instead, use a custom WP CLI command

Also note that the `print_r` in this code does nothing:

```
// this:
error_log( print_r( 'TESTING CRON', true ) );
// is the same as:
error_log( 'TESTING CRON' );
```

As for the mail, just because you piped `stdout` to `/dev/null` doesn't mean you piped `stderr`too. This is a general bash question though, not VVV specific, but to save searching, try `&>/dev/null` instead of `>/dev/null`, or consider piping to a `/vagrant/cron.log` file instead.

Just be mindful that the cron job will only run while the VM runs and your computer is awake and active. Additionally, you'll need to set it up again if you ever recreate the VM

**Comment by dingo-d** [comment]
Sure thing, thanks for the tips. The cron is working (tested), I'll just need to set up a log file and a way to notify me if cron fails. For the live site I'll let my devops work it out how it should work :)
