### ISSUE TITLE
WP Core JS build changing

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1447]
https://core.trac.wordpress.org/ticket/43055

TLDR we can't run the `src` and `build` folders in parallel as a build step is necessary, meaning `src` will never work properly

We should take this as an opportuntiy to fix up https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop and deprecate the old develop site template

**Comment by LoreleiAurora** [comment]
Just  to note:
i wouldnt auto run grunt watch in the background, it does not work great on mapped folders.

**Comment by tomjn** [comment]
Thoughts on the deprecation of `wordpress-develop` in favour of `custom-site-develop`:

 - What if we modify the provisioner to insert an MU plugin that puts a notice in the admin bar warning the site template is deprecated and linking to migration instructions?
 - We'll need migration instructions, though I'd expect anybody doing core dev could do it themselves
 - We'll need to change the `vvv-config.yml` so new users get `custom-site-develop`
 - The vvv mu plugin that lets you fast switch from `src` to `build` will need to go away :(
 - A notice in the dashboard would probably be helpful
 - Visiting `src` will give a `wp_die` with a warning, instead perhaps we should modify the nginx config to redirect to the trac ticket or a doc? Maybe serve a static html file instead?

**Comment by pento** [comment]
Just dropping in to give y'all an update on the JS reorg work. 🙂

Because `grunt watch` (or any watching-type build tool) is a less-than-fun time with mapped folders, I think the best option for Core is going to involve moving to a more opinionated development environment. We've found [Gutenberg's setup scripts](https://github.com/WordPress/gutenberg/blob/master/bin/setup-local-env.sh) to be quite useful, so will probably move in a similar direction in Core.

With that in mind, I would suggest you move in the direction that makes the most sense for VVV, rather than being concerned with Core devs being able to setup a VVV-based development environment. Certainly, I think the folks most familiar with VVV/Vagrant would appreciate a way to keep using it, but I agree that you can expect current core devs to be able to do the migration themselves.

**Comment by tomjn** [comment]
>  I agree that you can expect current core devs to be able to do the migration themselves.

Given that VVV gets installed on contributor days, I'm keen to make sure VVV is usable out of the box for this, if only for inclusivity and to help first time contributors

**Comment by tomjn** [comment]
@pento I can't see anything in the GB scripts of note other than a docker call and a splash screen with some checks for existing tools, are you saying Core development will be using a docker container in future? Or that VVV is no longer to be used for core dev?

**Comment by pento** [comment]
I'm not saying VVV _can't_ be used for core dev, and it's a little premature of me to be saying that Docker is the right option, it's just the option that's worked well for Gutenberg so far.

@omarreiss will be opening a Core ticket where we can discuss the details of the pros and cons of each option. I'm certainly convinced that, with Core moving to a more complicated contribution process, we need to make it significantly easier for people to contribute. Part of that is automating setting up a development environment for people who aren't in a position to choose one for themselves.

The actual tool that sits behind that automation could easily be Docker or VVV, that's mostly a question of which is a better fit.

**Comment by earnjam** [comment]
Since this change is part of WP trunk now, https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop/ actually doesn't work at the moment. It defaults to using src when the `vvv_env` cookie isn't set, so unless you set that manually, or else change the nginx config directly, you can't get to the develop environment.

**Comment by tomjn** [comment]
i'm closing this one out, things seem to be working
