### ISSUE TITLE
Migrating from VV and Customfile(s)

### ISSUE THREAD

**Issue by akasophistikat** [Varying-Vagrant-Vagrants/VVV#1461]
## Context 

I've been using VVV 1.4 for quite some time now and managed my sites using [VV](https://github.com/bradp/vv) and *Customfile*. After going through the [Adding a New Site](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/) documentation, moving to VVV 2+ has proven to be more difficult than I expected; [VV](https://github.com/bradp/vv) spoiled me.

## Current Behavior

Using [VV](https://github.com/bradp/vv) and *Customfile* I was able create a site and then sync the **wp-content** folder.
~~~~
config.vm.synced_folder "~/project/wp-content" "/srv/www/project/htdocs/wp-content"....
~~~~

## Expected Behavior

After successfully creating a new site using the [custom-site-template](https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git) I thought defining **vm_dir** and **local_dir** would essentially be doing what *Customfile* does but it only leads to
> **Problem:** Could not load the site, this implies that provisioning the site failed, please check there were no errors during provisioning, and reprovision.

## Question(s)

If my project structure is 
~~~~
database/
wp-content/
README.md
~~~~
What's the procedure in order to sync my wp-content folder? Should I copy the folders from the [custom-site-template](https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git) output into my project structure and simply define the *_dir folder(s)?
~~~~
52     vm_dir: /srv/www/project/
53     local_dir: /home/username/www/project/
~~~~ 

## Your Environment

* VVV version: 2.1.0
* VVV Git Branch: master 
* Vagrant version: 2.0.3
* VM Provider name: VirtualBox
* VM Provider version: 5.1.4
* Operating System and version: Linux eos 4.4.0-116-generic #140~14.04.1-Ubuntu SMP Fri Feb 16 09:25:20 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tomjn** [comment]
Mapping custom sub folders under VVV 2 is the same as under 1, unsupported
and requiring custom files

Mapping folders adds a performance overhead, something that isn't mentioned
by tools such as VV, and isn't something VVV will support directly, vm_dir
etc are meant to change where a site is located, on a site level scope not
subfolders such as wp content etc

So use custom files, and if you do, be warned it's expected you have
knowledge of vagrant and we won't support it, the vagrant docs are pretty
clear on how to do it

Also keep in mind that rather than mapping sub folders into weird places,
custom provisioner's and version control checkouts, coupled with IDE/Editor
projects are a far superior solution. You shouldn't need to rearrange your
folder structure to make browsing your project easier
