### ISSUE TITLE
Best Practice for Theme Folders Located Elsewhere

### ISSUE THREAD

**Issue by lchski** [Varying-Vagrant-Vagrants/VVV#149]
I'm looking for a recommendation about a workflow best practice. Ideally I'm able to use VVV and have the theme folders that I'm working with located in a separate directory. Is there a recommended method to do this?

I tried symlinking, but it doesn't provide the desired result because the symlink on the server ends up pointing to a location on my local machine. (Which makes sense, of course.)

Is there an easy way I can have my themes located in separate directories, with them somehow being referenced by my VVV install?

**Comment by XedinUnknown** [comment]
Hi,

I have a similar problem. At first, I thought it may be due to how symlinks are made on Windows VS Unix. However, now I see that it's a different kind of problem.

Still, what is the proper way of doing this? I've described my setup [here](http://stackoverflow.com/questions/33224105/testing-plugins-live-with-varying-vagrant-vagrants), and I suspect that many people will want something similar, because... you know... it only makes sense to have the project in its own project folder.

**Comment by XedinUnknown** [comment]
As a temporary solution, I have created a hard link (or, in Windows, a junction) *from* the WP plugin directory in VVV to the project folder.

**Comment by XedinUnknown** [comment]
For possible solution, see my [SO question](http://stackoverflow.com/questions/33224105/testing-plugins-live-with-varying-vagrant-vagrants).
