### ISSUE TITLE
Certificate is not generated when provisioning a single site

### ISSUE THREAD

**Issue by circuuz** [Varying-Vagrant-Vagrants/VVV#1522]
## Expected Behavior

A site's certificate should be generated when provisioning a site with:

```vagrant provision --provision-with site-XXX```

## Current Behavior

A site's certificate is NOT being generated when provisioning a single site, which force us to run the full provision every time a new site is added.

## Possible Solution

The contents of the provision file for the tls-ca utility should (more or less) be copied into provision-site.sh and wrapped in a call to `is_utility_installed` to check that the tls-ca utility is installed.

## Your Environment

* VVV version: 2.2.1
* VVV Git Branch: master
* Vagrant version: 2.1.1
* VM Provider name: VirtualBox
* VM Provider version: 5.2.8
* Operating System and version: Mac OS 10.13.4

**Comment by tomjn** [comment]
Hmmm that's true, but Im not sure how to resolve this, there's a reason we
don't make much noise about per site provisioners

**Comment by Mte90** [comment]
Maybe a check if the certificate exist and in case not generate again?

**Comment by benlumia007** [comment]
if you have an existing ssl certificate from before, I think its possible that you will need to delete that before you install the newest version of the ssl. i mean that's what i've been doing lately.

**Comment by tomjn** [comment]
Utilities run on provision, the `--provision-with` is vagrant lingo for executing a specific provisioner. So we can't regenerate certificates because no utilities are loaded, and most of the VVV provisioner isn't either, the only thing you can expect is the `vvv-init.sh` of that site, and some stuff to copy the nginx config into the appropriate place.

This is why we don't advertise that you can do this. Suggestions on file changes are welcome though, just understand that Utilities don't run in that context, and we have no mechanism for triggering them like that, unless you use `vagrant up --provision` or `vagrant provision`

**Comment by benlumia007** [comment]
@circuuz 
did u ever get this to work without the `--provision-width` and use just `vagrant up --provision` or `vagrant provision`

**Comment by benlumia007** [comment]
@tomjn 
Should we closed this since, if no response from the user that  create this ticket, I'm going to assume that is fixed.

**Comment by tomjn** [comment]
Sure, we'd need to change how utilities work to make this happen which is going to take some time
