### ISSUE TITLE
IP Address for VVV

### ISSUE THREAD

**Issue by benlumia007** [Varying-Vagrant-Vagrants/VVV#1532]
This is actually more of a question than anything else. 

Since VVV uses 192.168.50.4 by default. So the whole of me doing this, is there a way to use two instance of vvv, one for develop and one for master on the same machine using two different folders, one called develop and one for master. 

if i were two launch both  of them at the same time, i'm going to assume that it uses 192.168.50.4 no matter what. is there a way to actually change it so that one uses 50.4 and one uses 50.5 or something like that 

that way i don't have to destroy just to use a different version

**Comment by earnjam** [comment]
You can set the IP in your vvv-custom.yml file. 

The last section just add a setting for `private_network_ip` like this:

```
vm_config:
  memory: 2048
  cores: 1
  private_network_ip: 192.0.2.5
```

I setup a VVV instance using the IP in the example above because it's part of a subnet reserved for documentation examples, so I knew it wouldn't be in use. In my case VVV wasn't working whenever I was on my company VPN because Cisco AnyConnect was routing the normal private network subnets through it and they wouldn't load.

**Comment by benlumia007** [comment]
cool, let me test this out before i close this ticket. 

thanks

**Comment by earnjam** [comment]
Actually now that I say that, looks like this only works if you're running off master or develop branch, or the v2.2.1 tag. The v2.1.0 tag doesn't have the change. It was added in January
https://github.com/Varying-Vagrant-Vagrants/VVV/commit/458020a32f29624c866b06217a68d4d7a462441e

**Comment by benjaminlu007** [comment]
yeah, im using the latest versions anyways, so yeah. thanks for the info.

**Comment by benlumia007** [comment]
man having two accounts is just bleh.. keep forgetting this, using the wrong account lol

**Comment by benlumia007** [comment]
closing ticket, that `private_ip_address` works
