### ISSUE TITLE
Parallels: Failed to mount folders in Linux guest.

### ISSUE THREAD

**Issue by No3x** [Varying-Vagrant-Vagrants/VVV#1600]
## Expected Behavior
When `vagrant up` the fs should be mapped to the guest.

## Current Behavior
The `vagrant up` process fails

## Possible Solution
Unknown
## Steps to Reproduce (for bugs)

1. checkout develop branch commit 448583f3b28272ce33a636c6554b61f260bdd272
2. have parallels as provider
3. `vagrant up`

Relevant part of the log:
```
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /var/log => /Users/myuser/Vagrant/vagrant-local/log
Failed to mount folders in Linux guest. You've specified mount options
which are not supported by "prl_fs" file system.

Invalid mount options: ["dmode=777", "fmode=777"]
```
## Context

I can't use VVV with parallels.

## Your Environment

* VVV version: 
* VVV Git Branch: develop commit 448583f3b28272ce33a636c6554b61f260bdd272
* Vagrant version: 2.1.1
* VM Provider name: parallels
* VM Provider version: 1.7.8
* Parallels version: 10
* Operating System and version: OSX El Capitan

**Comment by tomjn** [comment]
Hello!

I am unfamiliar with the prl_fs filesystem, and I see you've taken the
unusual step of using parallels, can you elaborate?

I also see that the majority of the provisioner log is missing, can you
provide a full log? It is critical and essential that you do not censor
logs down to a handful of lines, the entire log is a requirement in 90% of
situations. You can link to a gist if it's very long

I would recommend strongly that you use a virtual box based provisioner,
I'm unaware of any active testers or developers who have worked with VVV
and parallels in the last 2 years, and would consider support for parallels
historic rather than active. It's very likely that you would need to source
the fix yourself and maintain and test support yourself

**Comment by No3x** [comment]
> I am unfamiliar with the prl_fs filesystem, and I see you've taken the unusual step of using parallels, can you elaborate?
> I would recommend strongly that you use a virtual box based provisioner, I'm unaware of any active testers or developers who have worked with VVV and parallels in the last 2 years, and would consider support for parallels historic rather than active. It's very likely that you would need to source the fix yourself and maintain and test support yourself

Thought parallels is still supported. I had performance issues years ago and switched to parallels which worked still well with VVV 2.2.1.

> It is critical and essential that you do not censor logs down to a handful of lines, the entire log is a requirement in 90% of situations

Here is the full log: https://gist.github.com/No3x/c4a56267395b59f8005c7e645ca62f68

> It's very likely that you would need to source the fix yourself and maintain and test support yourself

I really don't need to use parallels that bad. I will use what's supported and switch to Virtualbox since I'm not really familiar with this vagrant stuff. I just want to develop WordPress plugins.

**Comment by tomjn** [comment]
As I thought, it never gets past the vagrant file, that error suggests that if it worked for you in the past and it doesn't work now, then something else has changed. The parallels specific portions of the vagrant file have not seen changes in quite a while

> Thought parallels is still supported. I had performance issues years ago and switched to parallels which worked still well with VVV 2.2.1.

It's a roll of the dice, it worked at some point, but the resources to maintain support are not there, so wether it continues to work or not is an unknown

While the docs do say:

> In addition to VirtualBox, provider support is also included for Parallels, Hyper-V, VMWare Fusion, and VMWare Workstation.

Mileage may vary, and active testing of those providers is variable. If there's an issue with a provider it's a case of trying it out, discovering it, and reporting the bug. VirtualBox being the most widely used and what all the instructions cater to is pretty much guaranteed to be supported. Hyper-V or VMWare fusions not so much. I tried to set up Hyper V instructions for example, but I didn't have the means to verify them, and I asked if somebody could run through them and check, that was months ago though with no response.

It's also difficult because a lot of these providers require you to pay upfront for a license to gain access, making Hyper-V and VirtualBox the only free options ( assuming a Windows license )

So looking at the issue, I would look here:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L385

And notice that similar guards are not present on the other `synced_folder` directives that specify file and folder permissions. My guess is that they would need to be added.

This Hyper V block might be the best way to do that for local sites:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L439

Specifically, you will want to add Parallels specific overrides to those synced folders that specify fmode and dmode

If you manage to get it working, please send a PR, but I cannot guarantee that once that issue is resolved that you won't face others
