### ISSUE TITLE
xDebug will not connect

### ISSUE THREAD

**Issue by ARAGATO** [Varying-Vagrant-Vagrants/VVV#1618]
I have been trying for almost three days, but I do not get xdebug/atom/vvv working.

My xdebug.log shows me the following error:
Log opened at 2018-08-24 12:22:28
I: Connecting to configured address/port: 10.0.2.15:9000.
W: Creating socket for '10.0.2.15:9000', poll success, but error: Operation now in progress (29).
E: Could not connect to client. :-(
Log closed at 2018-08-24 12:22:28

When I check for listening ports on my host machine:
 netstat -tulpn | grep ":9000"
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::9000                 :::*                    LISTEN      11095/app.asar --no

The Path Mappings have been set in atom.

VVV latest version, just downloaded it a couple of hours ago.
Linux Mint 17.3 
Atom 1.21.1 

I have been through every google site regarding that issue and cannot get it working. What the heck am I missing?

**Comment by tomjn** [comment]
@ARAGATO you're using `10.0.2.15` as the IP to connect to, where did you get that IP from? I'm assuming it's the IP of your computer ( not the IP of the virtual machine ), you need to connect to the guest machine/VM running VVV, not the host machine

**Comment by tomjn** [comment]
The IP is `192.168.50.4` by default, remember, your IP != VVV IP. Also keep in mind that VVV is not setup for remote network requests, if you're trying to access a VVV instance on a different computer across an office network, it will not work. This is because people were using VVV in production which is a bad idea

**Comment by ARAGATO** [comment]
Oh dear, I read somewhere I should use the eth1 IP. So I went into vagrant ssh and looked up my eth1 via ifconfig, which resulted in the 192.168.50.4. However, I should have looked up my vboxnet2 adapter on my local machine which results into a 192.168.50.1, which is the correct one to use. It works now, after like a work week of fiddleing. Thanks.

**Comment by tomjn** [comment]
Before you go, can you try using VVV.test instead of an IP?

**Comment by ARAGATO** [comment]
Yes, good idea tomjn. 
I tried it and it seems to work as well. Setting the remote IP to vvv.test by default might be the optimal solution from my point of view.
![image](https://user-images.githubusercontent.com/25451106/44671128-cd19ef00-aa4e-11e8-8e5c-216076413c8a.png)

**Comment by Mte90** [comment]
I am investigating because I have the same problem.
Right now I am tryng to understand if xDebug is running and enabled (it is, the profile works) but:
```
<?php

$sock = socket_create(AF_INET,SOCK_STREAM,0);
socket_bind($sock, '192.168.50.1', 9000) or die();
socket_listen($sock);
$client = socket_accept($sock);
echo "connection established $client";
socket_close($client);
socket_close($sock);
```
This script hang from host and ip changed also from insde the VM.
Looking with `netstat -tulpn | grep ":9000"` if I enable with `xdebug_on` that command show nothing.

**Comment by Mte90** [comment]
Nevermind was my client with issues.
