### ISSUE TITLE
Can i use VVV and all the software it installs for commercial purpose ?

### ISSUE THREAD

**Issue by user-mk** [Varying-Vagrant-Vagrants/VVV#1622]
I want to use VVV for creating wordpress themes and plugins. 

Now VVV installs php, wordpress and yet other software.

1) Can those software be used for creating wordpress themes and plugins that will be sold ? The themes and plugins will be sold not software installed by vvv

**Comment by tomjn** [comment]
Yes, the license is here:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/LICENSE

GitHub puts a nice summary at the top:

<img width="1023" alt="screen shot 2018-08-29 at 00 51 29" src="https://user-images.githubusercontent.com/58855/44757187-b2ff1000-ab25-11e8-903f-ede57461337f.png">

So yeah if VVV destroys your computer, burns your house down, and overthrows your government, you can't sue us for that.

On the other hand if you want to build a website that destroys your computer, burns your house down, and overthrows your government, I don't recommend it but you can do that! And you can sell it!

**Comment by user-mk** [comment]
Sure, thanks. One thing that bothers me is that php, mariadb, and all packages installed by vvv come with different licenses. VVV is MIT, so surely it can be used without questioning licensing and commercial use. But those software that come with different licenses( such as php, ubuntu, memcached) can they be used for creating and selling wordpress themes and plugins ? 

Again the themes and plugins will be sold not packages installed by vvv.

**Comment by tomjn** [comment]
> One thing that bothers me is that php, mariadb, and all packages installed by vvv come with different licenses.

I fail to see the relevance, opensource code licenses are more concerned with what you can do with the code, not how the end software gets used. You would have to consult those licenses.

VVV does not bundle that softwares source code though, it directs a VM to install it.

This is all irrelevant. There's a difference between using and modifying software.

> But those software that come with different licenses( such as php, ubuntu, memcached) can they be used for creating and selling wordpress themes and plugins ?

If they can't how is that anybody could do it to begin with? As I said before, using != modifying, and if you intend to distribute the source code of the PHP interpreter with your premium plugins, then you should read the license. I am not aware of any plugin author who does that though.

> Again the themes and plugins will be sold not packages installed by vvv.

Not sure what you're talking about here, or how it's relevant

---

It sounds like you have a lot of strange ideas about how licenses work, and misconceptions. If any of these were actual problems, then pretty much the entire web would have to come down, and we'd be left with a handful of bespoke Windows systems.

I would suggest if you have further questions that you consult a lawyer rather than getting legal advice online, or just trust that it's not a problem.

Sadly this is not the place to discussing licences, VVV uses MIT, we aren't aware of any issues that causes, there are no issues using VVV to produce software for commercial purposes.
