### ISSUE TITLE
Google Maps API

### ISSUE THREAD

**Issue by jsaxestaral** [Varying-Vagrant-Vagrants/VVV#1637]
Has anyone successfully implemented google maps API on VVV?  I've tried putting in a few different things in the HTTP Referrers portion of the API setup, but nothing seems to work. I always get the "This API project is not authorized to use this API" error.

Have tried:
http://mysite.test
https://mysite.test
http://192.168.50.4
https://192.168.50.4
http://localhost

Any advice would be appreciated...

**Comment by tomjn** [comment]
I don't see any particular reason that VVV specifically would prevent this. A quick google suggests that issue is because you haven't turned it on in your cloud console.

https://stackoverflow.com/questions/32994634/this-api-project-is-not-authorized-to-use-this-api-please-ensure-that-this-api#32998566

Eitherway it's either a local developer environment issue that would affect any local dev environment, not just VVV, or it's unrelated
