### ISSUE TITLE
Renaming the WP Develop site

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#1649]
A lot of people seem to think that in order to do client work or develop things on WP, you need to use the custom site develop template.

But this is untrue, that site template is for working on WP itself, core patches, testing, trac tickets, etc. They should be using the standard site template instead

How should we rename this site to dispel this misconception? `trunk.wordpress.test`?

**Comment by Mte90** [comment]
Maybe we can change the title of the website like "WP Nightly Contribute version"
Because many people seems open the dashboard and don't read was his written.
So maybe we can improve that too adding like an alert on clicking and opening that website.
Or adding in the custom file as default a stable site and switch the order inside the dashboard.

**Comment by tomjn** [comment]
I added a PR that renames them to:

 - one.wordpress.test
 - two.wordpress.test
 - trunk.wordpress.test

Then adds descriptions, specifically mentioning plugin development, to the first 2

**Comment by mrigankvallabh** [comment]
I think the documentation on vvv.test is already saying that wordpress develop is for contributing to core wordpress, and wordpress default is the template that one may use for client, theme or plugin work. In my opinion the document is already a good lead as to what sites install are for what purpose.

**Comment by tomjn** [comment]
True, but some people have mistaken it or when it's explained it isn't obvious to them, so I'm keen to make things as clear as possible

**Comment by tomjn** [comment]
This was done and is in v2.4
