### ISSUE TITLE
PHP errors logged in /var/log/php7.2_errors.log instead of /srv/www/sitename/log/error.log

### ISSUE THREAD

**Issue by paulschreiber** [Varying-Vagrant-Vagrants/VVV#1671]
Iinstead of each site's errors being logged separately, all are logged in one place.

## Expected Behavior
PHP errors for each site are logged in `/srv/www/sitename/log/error.log`.

## Current Behavior
PHP errors for all sites are logged in `/var/log/php7.2_errors.log`

## Steps to Reproduce (for bugs)
`error_log( 'hi' );`

Possibly related:
https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1620
https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1636

## Your Environment

* VVV version: 2.2.1
* VVV Git Branch: 2.2.1 tag
* Vagrant version: 2.2.0
* VM Provider name: VirtualBox
* VM Provider version: 5.2.18
* Operating System and version: macOS 10.13.6

**Comment by tomjn** [comment]
So those are Nginx access and error logs, there's currently no way I'm aware of to splice apart the PHP error log so that it gets put in that folder ( or a means of configuring VVV to do so ), if you know of a way to do it I'm keen to get it done

In the meantime, I've started on pull requests to change the names of those log files to `nginx-access.log` and `nginx-error.log`

**Comment by tomjn** [comment]
As an aside, VVV has never had per site PHP error logs to my knowledge, if it did it was in the pre-2.0 days

**Comment by Mte90** [comment]
As I can see this now with wp 5.2 can be handled manually using ``define( 'WP_DEBUG_LOG', '/tmp/wp-errors.log' );` in the wp-config.php.
