### ISSUE TITLE
hostsupdater.remove_on_suspend in Customfile no longer works

### ISSUE THREAD

**Issue by afercia** [Varying-Vagrant-Vagrants/VVV#1727]
I have some custom sites (I guess I'm not the only one) and since years I've set this in my `Customfile`:

```
config.hostsupdater.remove_on_suspend = false
```

to avoid to have to enter my password each time I halt or boot VVV.

Seems to me this no longer works after https://github.com/Varying-Vagrant-Vagrants/VVV/commit/17719c6639baeec6a75166d23deffd790286a32b

I've also seen https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1706/commits/efb3dcb6f2e315ef698420a8022703334dcabcf0 and the related PR.

If now the configs in the `Customfile` are actually to be considered "additional" and not "replacement",  what is the new way to set `remove_on_suspend` to false? I'd greatly appreciate to not having to enter my password each time 🙂 

Aside: I guess this applies also to other configs, how to override them now?
Thank you.

**Comment by afercia** [comment]
Thanks for your feedback.

> you can make your hosts file writeable 

Doesn't sound like a good idea 🙂 

> set it to a config value so that it could be controlled from vvv-custom.yml instead,

Would it work in the `vm_config` section then? Please don't assume people necessarily know this kind of things, it's not so obvious 🙂 A few configs in my `Customfile` have been there long before `vvv-custom.yml` was introduced.

**Comment by tomjn** [comment]
That sounds good, just needs a pull request

What else do you have in there?

**Comment by afercia** [comment]
A few configs to sync the plugins directory across all the default and custom sites, e.g.:
`config.vm.synced_folder "/Users/andrea/wp/plugins", "/srv/www/wordpress-49/public_html/wp-content/plugins", :owner => "www-data"`

**Comment by tomjn** [comment]
I see, just keep in mind that the more you mount the greater the performance hit. Since it looks like you're trying to use the same plugins folder and test it across multiple WP instances, perhaps it would be better to use a subdirectory install, and map subdomains on to different folders?

e.g.

 - wp-content
 - wp50
   - index.php
   - wp
 - wp51
   - index.php
   - wp
etc..

Then you can modify the nginx config and map each subdomain to the relevant subfolder, and map `/wp-content` to `wp-content` for all of them?

This way, no symlinks necessary, no duplicate plugin folders, no vagrant shared mounts

**Comment by tomjn** [comment]
I'm going to close this one out, feel free to reopen if there's an Q's though
