### ISSUE TITLE
Adding a new site to VVV--using my own WordPress files stored on GitHub

### ISSUE THREAD

**Issue by cagross** [Varying-Vagrant-Vagrants/VVV#1736]
I want to create a new site in VVV.  I know how to create a default WordPress site in VVV, by following the the [Add a New Site](https://varyingvagrantvagrants.org/docs/en-US/adding-a-new-site/) instructions.  But in my case, I've backed up WordPress files from an existing site (all files except wp-config.php and .htaccess) , and stored them in a GitHub repo.  I'd like to now create a new VVV site from these files.  In turn, I'd want to initialize my VVV WordPress folder as a local git repo.  I would then migrate the database from my remote site, to the new VVV site (using a plugin: WP Sync DB).  What's the best approach to this--specifically, does VVV offer any method of creating a new VVV site using WordPress files from my own GitHub repo?

Can I do this perhaps by specifying my own Git repo (instead of https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git) in vvv-custom.yml?  Or would I simply create a default WordPress site in VVV (using the VVV documentation), then replace all the files on my own (either manually, or with Git)?  The latter would be a fallback method.  I'm just wondering if VVV offers a more efficient or advantageous method.

Now that I think about it, even if VVV could create a new WordPress site using my own WordPress _files_, there may be _database_ issues with that site.  Specifically, I guess VVV would try to create a site with my own WordPress files, but try to pair it with the default VVV database--that doesn't sound like it will work.

Just thought I'd ask.

**Comment by tomjn** [comment]
> Can I do this perhaps by specifying my own Git repo (instead of https://github.com/Varying-Vagrant-Vagrants/custom-site-template.git) in vvv-custom.yml?

Yes and no, if you put your own repo in to `vvv-custom.yml` it would:

 - clone the repo into the `www` folder under the given site name
 - have no idea how to provision it

VVV needs at minimum a `vvv-nginx.conf` to tell it how to serve the site, otherwise it will clone the repo, mount the folders, but nothing more, you'll get the dashboard when you visit the sites URL, and it'll complain it couldn't find nginx files in the provisioning log

The simplest and easiest method would be to use the custom site template to create a new WP install, then swap out the database contents, and replace the files

>  Or would I simply create a default WordPress site in VVV (using the VVV documentation), then replace all the files on my own (either manually, or with Git)?

You could do that, you could even fork the custom site template and modify `vvv-init.sh` to do just that, then you could just point VVV to the forked site template. You could also put a `.vvv` or a `provision` folder in your sites repo and put an appropriate set of provisioners in there.

> Specifically, I guess VVV would try to create a site with my own WordPress files

VVV doesn't download and install WordPress, it simply runs `vvv-init.sh` if it's there, then copies `vvv-nginx.conf` to the appropriate place, and finally adds any hosts in any `vvv_hosts` files it finds.

It's the site provisioners that do the WP installation, and the DB creation, and it's the site provisioner specified in the `repo` field. If your sites repo also contains provisioner files VVV can use then hooray it's all in the same repo.

If you had your own set of provisioners you can make them do what you want. You could even install Joomla or Drupal if that's what you really wanted to do.


--

As an aside, in the future I'd like to be able to specify a repo for the `wp-content` folder in the custom site template, but this hasn't been implemented, and you shouldn't expect it to arrive in the next few weeks

**Comment by benlumia007** [comment]
i finally understand how to provision works and create your own fork using custom-site-template. is not that difficult :)

the vvv-init actually does download and install WordPress, if it exists, then it uses the wp cli to do an update if there is one.

**Comment by cagross** [comment]
@tomjn OK understood on all.

> The simplest and easiest method would be to use the custom site template to create a new WP install, then swap out the database contents, and replace the files.

OK I'll go this route--I'll have VVV create a default WordPress site, then manually add my own site files, and migrate my own database.

> you could even fork the custom site template and modify `vvv-init.sh` to do just that, then you could just point VVV to the forked site template. 

That's an interesting solution.  I may play around with this method in the future.  Or maybe use this method so VVV creates a new WordPress site, but with a few plugins pre-installed.

> You could also put a `.vvv` or a `provision` folder in your sites repo and put an appropriate set of provisioners in there.

This seems a little more complex for me, but good to know.

We can consider this resolved.

**Comment by benlumia007** [comment]
@tomjn 

should we closed this ticket as resolved!
