### ISSUE TITLE
Request to http://vvv.test returns 404

### ISSUE THREAD

**Issue by matthewhegarty** [Varying-Vagrant-Vagrants/VVV#1738]
## Expected Behavior

Request to http://vvv.test should return the test page

## Current Behavior

The nginx 404 page is returned.

## Steps to Reproduce (for bugs)

1. Follow the vvv installation instructions
2. Browse to http://vvv.test/
3. Should see http 404

All other sites return 404:
- http://one.wordpress.test
- http://two.wordpress.test

I've tried full removal and reprovision.
I have installed and used vvv successfully on this PC recently (last month).  That installation also has the same issue now, so presumably this is related to latest version of vvv.

Note `/etc/hosts` is setup / cleared on each up / halt:

```
192.168.50.4  vvv  # VAGRANT: 1f6c58670c01bdaa161e231ca10b59e3 (default) / ee7ffe46-fa47-4377-8f53-3d51010075b0
192.168.50.4  vvv.dev  # VAGRANT: 1f6c58670c01bdaa161e231ca10b59e3 (default) / ee7ffe46-fa47-4377-8f53-3d51010075b0
192.168.50.4  vvv.test  # VAGRANT: 1f6c58670c01bdaa161e231ca10b59e3 (default) / ee7ffe46-fa47-4377-8f53-3d51010075b0
192.168.50.4  vvv.local  # VAGRANT: 1f6c58670c01bdaa161e231ca10b59e3 (default) / ee7ffe46-fa47-4377-8f53-3d51010075b0
192.168.50.4  vvv.localhost  # VAGRANT: 1f6c58670c01bdaa161e231ca10b59e3 (default) / ee7ffe46-fa47-4377-8f53-3d51010075b0
192.168.50.4  one.wordpress.test  # VAGRANT: 1f6c58670c01bdaa161e231ca10b59e3 (default) / ee7ffe46-fa47-4377-8f53-3d51010075b0
192.168.50.4  two.wordpress.test  # VAGRANT: 1f6c58670c01bdaa161e231ca10b59e3 (default) / ee7ffe46-fa47-4377-8f53-3d51010075b0
192.168.50.4  trunk.wordpress.test  # VAGRANT: 1f6c58670c01bdaa161e231ca10b59e3 (default) / ee7ffe46-fa47-4377-8f53-3d51010075b0
```

[debug.log](https://github.com/Varying-Vagrant-Vagrants/VVV/files/2900699/debug.log)

## Your Environment

* VVV version: v2.5.1-git:master
* VVV Git Branch: master
* Vagrant version: 2.2.3 (also occurred on 2.2.2)
* VM Provider name: VirtualBox
* VM Provider version: 5.2.18
* Operating System and version: Ubuntu 18.04

**Comment by tomjn** [comment]
Some questions:

 - Do you have any other environments, vagrant boxes, or software that serves things on port 80?
 - Is this a brand new VVV instance, or an existing one that's just broken? Did you just update?
 - By the Nginx 404 page do you mean the VVV dashboard with the banner at the top? Can you be more specific? **Are you absolutely sure it's the one Nginx provides and not the one Apache provides?** What does the text say?

I can't find anything in particular in the debug log, but since it's so verbose it's difficult to go through. Does the problem go away if you reprovision with `vagrant provision`?

**Comment by matthewhegarty** [comment]
Thanks for quick response.  I have found this issue, which is that somehow another vagrant instance was running in the background.  I have shut it down and now vvv working as per normal.

**Comment by tomjn** [comment]
Yay :)
