### ISSUE TITLE
Ubuntu 14.04 LTS (Trusty) just reached EOL

### ISSUE THREAD

**Issue by m-e-h** [Varying-Vagrant-Vagrants/VVV#1769]
No more security, package, or maintenance updates.
https://lists.ubuntu.com/archives/ubuntu-announce/2019-March/000241.html

I know it isn't a cut and dry upgrade path https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1710

Just sayin.

**Comment by tomjn** [comment]
I believe I have a plan but it will require manpower that doesn't currently
exist on the project

Namely that's we switch to building our own boxes, by provisioning VVV with
no sites then packaging the resulting VM as a box

The downside is we can't fire up a VPS on a major provider and run a build
server. We don't have a company sponsoring with a physical machine that can
run for an hour on every PR merge and Monday mornings

Having said that, Im more than happy for contributions and to advise on
what needs to be done. I just don't have the bandwidth to do that myself in
the near future

**Comment by m-e-h** [comment]
Thanks for the response @tomjn !

Packaging VVV boxes does sound ideal for the long term!

A short term solution may be needed in the meantime though. At least for new installs and those that don't mind losing their db.

Your thoughts here make sense

- If no existing VM exists, use Ubuntu 18
- If the database is already mapped to a shared folder, switch to Ubuntu 18 ( VVV 1 users had the shared folder so VVV 2 falls back to it for compatibility reasons )
- If a VM exists, and it's using Ubuntu 14, try to migrate the database folder so that on the next provision, it upgrades to 18

@Mte90 's comment sounds possible too
>Maybe we can do a script that is executed only on when there is the bump of the distro.
In that way we can do a full backup of the database to reimport later and add other integrations in case we need it.

I'll keep thinking about it and look into some options when I can but I'm with you on the bandwidth. 
Plus, because of the excellent work you and others have done here, I mainly just use VVV blindly and would have to get caught up on how things actually work :smile:

**Comment by tomjn** [comment]
We add an option to the `vvv-config.yml` that's present in the default, changing the box to a VVV box:

 - Existing users won't get the new box until they add it themselves
 - We can turn it on in a `vagrant destroy` trigger so on the next provision they get it
 - Users who want the new box can opt in
 - We can make a song and dance about it in the dashboard
 - The `apt-get` based provisioners and the core utility only get ran in the box build process
 - The only provisioners that are ran are site provisioners, and additional utilities

Some things to keep in mind:

 - A flag will be needed to turn on the core utility and apt-get provisioners
 - It's likely we'll need to change how certain browser facing software is installed, we can't just put it in `/srv/www/default` any more, bringing that folder inside the VM would mean no more custom dashboards
 - Utilities will need a `provision-site.sh` script, otherwise the TLS-CA utility won't be able to generate certificates for new sites

Once those are done, we'll be in a position where we can add the flag to switch boxes, and start building them ourselves

**Comment by tomjn** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1771 switches us over from the Ondrej PPA to the VVV mirror PPA. I consider this at best a temporary fix though, I'd like to get us on to Ubuntu 18 and back on to Ondrej sooner rather than later, or at least on to maintained packages we can mirror

**Comment by tomjn** [comment]
https://github.com/Varying-Vagrant-Vagrants/VVV/pull/1771 got merged, so we have a little breathing room, will need to do a point release of 2.7 this weekend, but for now switching to `develop` will do the trick for most people

**Comment by Lisa-Williams** [comment]
Ubuntu 14.04 LTS will get security updates until April 2022, when it reaches EOL.
[https://wiki.ubuntu.com/Releases](https://wiki.ubuntu.com/Releases)

**Comment by tomjn** [comment]
Ondrej removed the PHP packages for Ubuntu 14 as it reached end of standard support, and we don't have backups. We also encountered various constraints holding us back as a result of using such an old box.

Since `develop` branch is now on Ubuntu 18, I'm going to close this out

**Comment by Lisa-Williams** [comment]
No problem. I didn't realize that there were various other constraints.
