### ISSUE TITLE
Issues with cURL and REST

### ISSUE THREAD

**Issue by dingo-d** [Varying-Vagrant-Vagrants/VVV#1820]
## Expected Behavior

cURL should be working fine

## Current Behavior
I get reports from site url:

> The REST API request failed due to an error.
> Error: [] cURL error 60: SSL certificate problem: unable to get local issuer certificate

And when trying to reach wordpress.org:

> Your site is unable to reach WordPress.org at 198.143.164.251, and returned the error: cURL error 28: Connection timed out after 10000 milliseconds

## Steps to Reproduce (for bugs)
1. Update VVV to version 3
2. Get the latest WP (5.2.1)
3. Check the site in site health

## Context

I cannot update plugins - ACF Pro from the dashboard for instance.

## Your Environment
* VVV version: 3
* VVV Git Branch: develop
* Vagrant version: 2.2.4
* VM Provider name: VirtualBox
* VM Provider version: Version 6.0.8 r130520 (Qt5.6.3)
* Operating System and version: MacOS 10.14.5

**Comment by tomjn** [comment]
@dingo-d is the VVV CA root certificate added to your systemwide keychain? Or did you only add it to your browser?

Also, how are you executing the REST API request? Is curl running inside the VM or on the host? Or is this from PHP itself? It's not clear what you're doing or how to reproduce this

**Comment by dingo-d** [comment]
Well this is what site health feature executes, I'm running it on WordPress installation that is done on VVV, not sure how site health does those things to check them tbh

**Comment by tomjn** [comment]
we probably need to add the root certificate authority inside the VM

**Comment by adamfaryna** [comment]
I have the same issue. What is the status of this? Is there any workaround/fast solution?

**Comment by tomjn** [comment]
> What is the status of this?

It hasn't been done, no eta currently. I'm not aware of anything that requires this other than the site health check, that can't be circumvented through best practice.

If this is impacting your development, it'll be because you're making a PHP request to the REST API, in which case save yourself the hassle and a remote request and use `WP_REST_Request` and `rest_do_request` e.g.

```php
$request = new WP_REST_Request( 'GET', '/wp/v2/posts' );
$response = rest_do_request( $request );
 
if ( $response->is_error() ) {
    // Convert to a WP_Error object.
    $error = $response->as_error();
    $message = $response->get_error_message();
    $error_data = $response->get_error_data();
    $status = isset( $error_data['status'] ) ? $error_data['status'] : 500;
    wp_die( printf( '<p>An error occurred: %s (%d)</p>', $message, $error_data ) );
}
 
$data = $response->get_data();
$headers = $response->get_headers();
echo "<p>Success! Here's the data:</p>";
var_dump( $data );
```

https://developer.wordpress.org/reference/functions/rest_do_request/

If it's on the same multisite you can do even better with `switch_to_blog`

With that in mind, as well as it being super low hanging fruit, it's not a high priority. The database shared folder, and other things being broken are much higher priority, so this was pushed to the back of the queue.

If you wanted to do this though, a PR to the VVV utilitie that modifies `tls-ca/provision.sh` so that after it's provisioned the certificates it then follows [these instructions](https://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate), copying `/srv/certificates/ca/ca.crt` into the appropriate place

Someone will eventually get around to this, but there's no ETA

**Comment by dingo-d** [comment]
Ok, so I realised that I'm not only using curl for health check but for another project which needs to make a curl call to a third party API, and currently I'm getting the 

> cURL error 28: (see http://curl.haxx.se/libcurl/c/libcurl-errors.html). Error: 404

I'm on latest develop branch

**Comment by tomjn** [comment]
Nothing to do with us, error code 28 is a time out according to that linked
URL. At most all VVV does is just install curl. We don’t install a special
version or put any kind of config in place, it’s just stock generic curl

**Comment by dingo-d** [comment]
It's odd because the same code works on live sever, and I see nothing that could affect this other than the same thing that affects the health check tool

**Comment by tomjn** [comment]
> It's odd because the same code works on live sever,

Just because the machine in the data centre can find a route to the destination and connect successfully, doesn't mean your local machine can. We get this with Ubuntu package mirrors sometimes, people provision and they can't connect to the mirror that was chosen, but the problem goes away when they switch networks.

> and I see nothing that could affect this other than the same thing that affects the health check tool

The problem here was that when using a TLS certificate, we had forgotten to tell the guest OS to accept the custom certificates VVV was making.

Your problem is error code 28:

> ### CURLE_OPERATION_TIMEDOUT (28)
> 
> Operation timeout. The specified time-out period was reached according to the conditions. 

Since it's connecting to a remote API, I'd speak with them about it. If you can demonstrate that it works on your host OS but not in the guest OS, then we might have a VVV problem, or it could be that you have a very low timeout on your request. At this point it's all speculation without actual hard information

**Comment by dingo-d** [comment]
Thanks for the detailed answer and the tips, I'll definitely apply them. The concrete case is done either manually (ajax triggered) or in a cron job (I'm retrieving some auth tokens so I implemented a way that will try to make the request for 5 times if it fails - just in case something is happening with the 3rd party API).

I'll try reprovisioning, and trying to do a curl request from within and outside of vagrant to see what could be the issue.

Thanks again for the answer :+1:
