### ISSUE TITLE
Vagrant Reload --provision-with and Vagrant Provision --provision-with fail

### ISSUE THREAD

**Issue by Stefan-Adam** [Varying-Vagrant-Vagrants/VVV#1833]
## Expected Behavior

Vagrant Provision --provision-with or Vagrant Reload --provision-with when provided with site-keyname (from sites in vvv-custom.yml) should be able to provision, without needing to reprovision all utilities and sites in the box.

## Current Behavior

When Run, the provisioner encounters some mySQL errors, then fails on a NGINX error. See https://pastebin.com/ckFm91uL for the vagrant log.

## Possible Solution

Modify provisioner so that standalone provisioner is not missing any dependencies.

## Steps to Reproduce (for bugs)

1. Using current Master Branch
2. Complete first Vagrant up, copy example snippet from vvv.test to vvv-custom.yml
3. Run Vagrant reload --provision-with site-newtest or Vagrant provision --provision-with site-newtest
4. Observe.

https://gist.github.com/Stefan-Adam/1e47d3d8efc32b475952dd16e034836d

## Context

Our team uses VVV for our local development, and often have upwards of 50-60 sites in our VVV box. During VVV2 we could use provision-with to only provision a new site, rather than reprovisioning tons of old ones. A full vagrant reload --provision can take upwards of 20min, while provision-with would take only 1-2 min.

## Your Environment

* VVV version: 3.0.0
* VVV Git Branch: master
* Vagrant version:2.2.4
* VM Provider name: Virtualbox
* VM Provider version:
* Operating System and version: Windows 10 Pro (reproducible on Mac OSX as well)

**Comment by benlumia007** [comment]
hi, should be `vagrant reload --provision`, there's no --provision-with

**Comment by Stefan-Adam** [comment]
Vagrant natively has a provision-with, so that you can avoid running all the provisioners see https://www.vagrantup.com/docs/cli/reload.html#provision-with-x-y-z

We used it all the time in VVV2, it just has stoppped working in VVV3

**Comment by tomjn** [comment]
@Stefan-Adam I suspect your problem is that you're not just provisioning, you're also doing a `reload`. As a result, `vagrant reload --provision-with site-newsite` roughly translates to:

1. turn off the VM
2. turn it back on again
3. but only run this singular provisioner

Because a site template provisioner now `reload`'s rather than `restart`'s the nginx service, it doesn't start up

So instead, it would be better to use the `--provision-with` as it was always intended:

```sh
vagrant provision --provision-with="site-newsite"
```

Along with the classic caveat that because the utility provisioners didn't get a chance to run, no SSL certificates get generated. This is why we don't document `--provision-with` in the VVV docs.

Have you instead considered using `skip_provisioning: true` in `vvv-custom.yml` for sites you aren't using?

**Comment by tomjn** [comment]
In particular, MariaDB and Nginx don't get started until `config.trigger.after :up do |trigger|` so they won't be available if you combine `--provision-with` and `reload`, or `vagrant up` for that matter.

**Comment by Stefan-Adam** [comment]
@tomjn Thanks for looking into this! 

I hadn't considered that using the `--provision-with` would skip the utility provisioners. Since I opened this I have been rewriting our dev software to use the `skip_provisioning:true` flag (We have a c++ app that generates vvv-config.yml entries, and runs the vagrant provisioner for new sites). Since we are looking to use the SSL certs now, It looks like we needed to switch over anyway. 

The main reason we used only `--provision-with` was to minimize the provisioning time. The current default provisioner spends ~20s every provision updating npm and npm-checkupdates (even if they are already at the current version), and seems to spend a few minutes reinstalling all of the utilities (Mongo, Tideways, etc) even if they were provisioned once before, but if that is unavoidable tradeoff to have the SSL certs work properly, it isn't too much of a time loss.

**Comment by tomjn** [comment]
Out of curiosity are you using the `custom-site-template` or `custom-site-template-develop`? Mongo/etc are setup to detect if they're already installed, but if you know of a way to make those scripts exit earlier if nothing needs to be done that'd be great

Additionally, VVV3 copies `vvv-custom.yml` into the VM at the start of provisioning, which doesn't happen with `--provision-with`, this is because `vvv-custom.yml` lives in the root folder, so making that a shared folder means it overlaps with every other shared folder, which can cause problems

**Comment by Stefan-Adam** [comment]
@tomjn We are using a fork of custom-site-template. I forked the master branch of custom-site-template the day I opened the ticket so I could add more options to the template (Custom User, Custom password, Custom DB Prefix, Plugins to install during setup, themes to install during setup, etc).

Also, when we set up a new box for the first time we typically do a full provision, then every time after that just use `--provision-with`. 

We never used reload before VVV3, we just adopted it when it became recommended in the dashboard.  Our original flow was 
`vagrant up`
`vagrant status`
`vagrant provision --provision-with xxx`

I am working on modifying the default provisioner so that it just checks the current npm and npm-checkupdates against remote instead of reinstalling them if it is already up to date.
