### ISSUE TITLE
Passing variables like {VVV_SITE_NAME} to other files during provision of custom site

### ISSUE THREAD

**Issue by NLW-paulm** [Varying-Vagrant-Vagrants/VVV#1843]
## Context

This is a question

## Your Environment

* VVV version: 3.0.0
* VVV Git Branch: Master
* Vagrant version: 2.2.4
* VM Provider name: Vitualbox
* VM Provider version: 5.2.30r
* Operating System and version: Win10

## Question

Im developing a custom site that has a script (outside of wp) that requires access to the DB. So in my provisioning folder the vvv-nginx.conf.tmpl file has a line 
`{vvv_path_to_site}/log/nginx-error.log;` 
which during provisioning passes the path of the site into the placeholder, when it creates vvv-nginx.conf.

So I tried to replicate this placeholder replacement by creating a db.ini.tmpl file and then using the cp command in my provision script to create a live version and copy it to the file system, and hopefully replacing the placeholder for sitename

db.ini.tmpl
```
user     = wp
password = wp
dbname   = {VVV_SITE_NAME}
host     = localhost
```
vvv-init.sh
```
cp -f "${VVV_PATH_TO_SITE}/provision/vvv-nginx.conf.tmpl" "${VVV_PATH_TO_SITE}/provision/vvv-nginx.conf"
echo -e "\nSetting up plugin database"
cp -f "${VVV_PATH_TO_SITE}/provision/database.ini.tmpl" "${VVV_PATH_TO_SITE}/provision/database.ini"
cp -f "${VVV_PATH_TO_SITE}/provision/database.ini" "${VVV_PATH_TO_SITE}/public_html/dash/config/database.ini"
#do something here to run mysql import script
```

But the placeholder doesnt get replaced by the site name, in database.ini like it does for nginx.conf

**Comment by tomjn** [comment]
> But the placeholder doesnt get replaced by the site name, in database.ini like it does for nginx.conf

This is because your changes copy the file, and only copy the file. No search replacements of any kind were performed, so none happened.

`vvv-nginx.conf.tmpl` isn't a VVV thing, it's something `provisioner.sh` does, and it's VVV's core site provisioner that replaces the `{VVV_SITE_NAME}` is only for the Nginx configuration. Otherwise there would be no way for VVV to configure nginx configs correctly. This is only done for nginx configs, and isn't a generic system.

If you're aware of a method of eliminating this system I'd much appreciate it

If you want your provisioner to work the way you expected, you have these choices:

 1. Fork VVV and change `provisioner-site.sh`, I don't recommend this
 2. Use `wp db` to execute your queries, avoiding the need for a database.ini at all
 3. Use `sed` to replace the values in the `database.ini.tmpl` file and write the result to `database.ini`, the same way the custom site template does
 4. Use hardcoded values, figure out the database name from the site folder name, or pass it as an argument

**Comment by NLW-paulm** [comment]
OK, great, thanks for the quick response.  Unfortunately I cant use WP-cli as im adding none Wordpress tools to the site. Its very much a concept/work in progress/idea at the moment.

Interesting the nginx conf is being deprecated, I have a few small tweaks I need to make to the nginx config so there is lots for me to think about here.

thanks for the quick response, I will close this ticket.

**Comment by tomjn** [comment]
Oh there's still going to be an nginx config, just not so much the template file. You can always fork the template and put whatever you want in the provisioners and configs
