### ISSUE TITLE
Windows 10: PHPUnit - Could not find /tmp/wordpress-tests-lib/includes/functions.php, have you run bin/install-wp-tests.sh ?

### ISSUE THREAD

**Issue by CreativeTransmissions** [Varying-Vagrant-Vagrants/VVV#1931]
Hi there,

I'm unit testing a number of wordpress plugins on different test websites.

Everytime I start vagrant and SSH in, the requried wordpress files seem to have dissapeared and I get the following message:

Could not find /tmp/wordpress-tests-lib/includes/functions.php, have you run bin/install-wp-tests.sh ?

Workaround is to run the script:
bash bin/install-wp-tests.sh wordpress_test root root localhost

This didn't happen prior to upgrading to version 3.

**Comment by Mte90** [comment]
how do you get the error you mentioned? with what command?

**Comment by tomjn** [comment]
@CreativeTransmissions I've been looking for that script for the last hour and have been unable to locate it, it's not in the VVV repositories, site templates, utility repo, it's not in a standard WP install.

However, since it put things in `/tmp`, and `/tmp` is a temporary system folder that's supposed to be temporary, I'm not surprised that turning the VM off and on cleared it. That's standard intended behaviour and has been since the 1980's. If somehow it didn't work that way in VVV 2, then that was a bug.

Eitherway I cannot find this script, and there are no clear instructions on how to reproduce this. It's unclear where the script was ran, where the script is located, and what pre-requisites are needed to be installed, be it specific site templates

**Comment by tomjn** [comment]
I've identified the source of this script, it's the WP CLI test suite generated by a `wp scaffold` command:

https://developer.wordpress.org/cli/commands/scaffold/theme-tests/

Eitherway, it's a good thing that the environment is erased. Unit tests are meant to run on a clean isolated environment for reproducibility. Preserving the files would mean that prior test runs could influence future test runs. That's why it's installed to `/tmp`. If this is undesirable I'd suggest opening an issue with the WP CLI support on how to change that, but it's not a VVV problem, or a VVV script, and this isn't a bug, it's intended
