### ISSUE TITLE
Network Access

### ISSUE THREAD

**Issue by jessemarco** [Varying-Vagrant-Vagrants/VVV#1945]
I have latest VVV, cloned from github. I am on master brunch. No errors at all after installation. I have installed all plugins. But if I access thrugh lcoal network my defined IP 192.168.1.200, I can see only vvv.test site in HTML, no CSS. 

So network is working fine, but I can not see updated links for device with correct IP address. There is always localhost in all URLs. 

Thank you guys.

**Comment by tomjn** [comment]
This is expected behaviour, `https://vvv.test` is the dashboard address, so if you visit `https://192.168.1.200/` you'll get a page that references the vvv.test domain. Your computer knows what `vvv.test` is because the `vagrant-hostsupdater` plugin added it to the host file on your computer. This other machine though has no idea what `vvv.test` is. It can't load any of the assets as a result.

Further more, VVV isn't recommended for use as a local network install. I can be used that way yes, but only with modifications. The need for a tweak to the vagrant file is intentional, as VVV wasn't built to be exposed to the internet. Doing that involves some risk, so you have to go into the vagrant file to enable having a public facing network adapter that can recieve requests from other machines.

In order to resolve this, you will need to add a hosts file entry to the relevant device, e.g.:

```
192.168.1.200 vvv.test
```

The same goes for any WordPress sites etc that were added to VVV, their custom hostnames will need adding to the device you want to access them from. Doing this will be different on the major OS', and isn't possible in some cases ( modern android phones that don't haven't been rooted )

**Comment by jessemarco** [comment]
I used to VVV over network with previous versions, it worked on all devices over network with "xip.io" service. Very convenient for my projects. 

I have solved my problem without VVV.

Thank you for elaborated response.
