### ISSUE TITLE
Add existing WP site to VVV directory --Having trouble with database

### ISSUE THREAD

**Issue by woshj** [Varying-Vagrant-Vagrants/VVV#2001]
Hello VVV/Vagrant/VM noobie here!

So I've recently had to start setting up a dev environment for existing WordPress sites

After getting everything setup correctly I replaced the web files in the VVV/www/wordpress-one/public_html dir and tried to access the site this gave a database error and now I'm stuck.

I know I have to replace the default database with the database from the existing site but I can;t figure out how. I have an .sql file from the existing site but I have no idea where to go from here.

I've been looking around for a day and a bit trying to figure out how to get this working and just can't get my head round it, another issue is that I can't access the wp-admin as I wasn't the one who setup the site initially will this cause any problems in simply getting the site/ database displaying correctly in a browser.

I'm sorry for asking what feels like a stupid question given there's documentation on this I'm just really struggling to figure this out!

Thanks in advance!

woshj

**Comment by Mte90** [comment]
Did you changed also the `wp-config.php` file?
This one contain the references to the database, if you don't use the right parameters is normal that wordpress cannot connect to a db.

**Comment by woshj** [comment]
> Did you changed also the `wp-config.php` file?
> This one contain the references to the database, if you don't use the right parameters is normal that wordpress cannot connect to a db.

Thanks for the quick reply!

I changed it but I'm not really sure what I was doing I changed the new site wp-config.php file to point to the same place as the default wp-config.php file but left everything else the same

```
/** The name of the database for WordPress */
define( 'DB_NAME', 'wordpress-one' );

/** MySQL database username */
define( 'DB_USER', 'wp' );

/** MySQL database password */
define( 'DB_PASSWORD', 'wp' );
```
I changed it to say the following, instead of what was already setup, this got me past the database error but now just displays a blank screen, do I have to put my existing .sql database anywhere within the VVV folder structure to make this work properly?

**Comment by tomjn** [comment]
Hey @woshj you can use Sequel Pro or PHPMyAdmin to import the sql file. Keep in mind that an sql file isn't a database, it's just a text file. with. all the SQL commands to recreate the tables and their. contents. You can access PHPMyAdmin via the VVV dashboard on the righthand sidebar, and. there's a Sequel Pro connection file in the `database` folder you can use to set up Sequel Pro fast

You will also need to adjust your `wp-config.php` to have the same salts as the production site, otherwise the passwords won't work. The same goes for all the plugins and themes.

You might also need to do a search replace on your database after importing to change the production site URL to your local URL.

> but now just displays a blank screen

Check your PHP error log, but, keep in mind that if your production site uses the ABC123 theme, you will need that theme to be present or WP. won't be able to load it and you'll get a blank frontend.

**Fundamentally, there's very little VVV specific about this, if anything, standard WP migration guides and techniques should work for you.**

**Comment by woshj** [comment]
> Hey @woshj you can use Sequel Pro or PHPMyAdmin to import the sql file. Keep in mind that an sql file isn't a database, it's just a text file. with. all the SQL commands to recreate the tables and their. contents. You can access PHPMyAdmin via the VVV dashboard on the righthand sidebar, and. there's a Sequel Pro connection file in the `database` folder you can use to set up Sequel Pro fast
> 
> You will also need to adjust your `wp-config.php` to have the same salts as the production site, otherwise the passwords won't work. The same goes for all the plugins and themes.
> 
> You might also need to do a search replace on your database after importing to change the production site URL to your local URL.
> 
> > but now just displays a blank screen
> 
> Check your PHP error log, but, keep in mind that if your production site uses the ABC123 theme, you will need that theme to be present or WP. won't be able to load it and you'll get a blank frontend.
> 
> **Fundamentally, there's nothing VVV specific about this, if anything, standard WP migration guides and techniques should work for you.**

Thank you mate

I found the phpmyadmin panel and started an import and I get an auth error but like you said that's not a VVV issue just a phpmyadmin/myown issue, thanks for pointing me in the right direction!

I'll have a look at wordpress docs and see how I get on, i'll close this as it's not your problem, thanks for the help again!

**Comment by tomjn** [comment]
If you can import just the tables and reuse the DB credentials VVV generated, you should be able to bypass that.  There are so many options. for how to do this so don't limit yourself to docs that mention vagrant and VMs :)

**Comment by ironicmoka** [comment]
My two cents:

I'm a huge fan myself of duplicator plugin: https://it.wordpress.org/plugins/duplicator/ it's fast to set up and build packages to export, optionally filter /uploads/ or other directories you want to zip and download aside  (or not download at all using live_url option in config.yml).

You just have to provision a site as usual in config.yml in order to update host file and create the db, then you could delete the public_html content and run here the duplicator installer providing db credentials (usually 'namesite' for db name and 'wp' both for db user and pass) and you're done.

Much easier and automated for me rather than running a wp cli database import and search and replace, or some sql query on phpmyadmin. And a lifesaver when clients don't provide FTP or server access at early stages of work.
