### ISSUE TITLE
Remove yaml.php from dashboard

### ISSUE THREAD

**Issue by Mte90** [Varying-Vagrant-Vagrants/VVV#2040]
We need to:

- Refactor those usages: https://github.com/Varying-Vagrant-Vagrants/dashboard/search?q=yaml.php&unscoped_q=yaml.php
- Test the new changes

**Comment by tomjn** [comment]
Why would we remove `yaml.php` from the dashboard? How will it read the `config.yml` file?

**Comment by Mte90** [comment]
Now we have php-yaml module in VVV so the support is by php language itself.

**Comment by tomjn** [comment]
In the latest yes, but the dashboard repo is cloned by VVV versions going back into the early 2.0's that don't have `php-yaml`

**Comment by Mte90** [comment]
Well we can add an alert for those users, if there is someone that use an old VVV version is a way to suggest them to migrate.

**Comment by tomjn** [comment]
Which version did `php-yaml` get added into VVV core? I don't see what benefit this brings us in practical terms at the moment or what we're fixing

**Comment by Mte90** [comment]
Right now `yaml.php` in Codacy is reporting a lot of issues.

We are using https://github.com/Varying-Vagrant-Vagrants/VVV/blob/2539dd8b9424484b3c79a87bd0f5658ac2e33352/provision/provision.sh#L165 so I guess that now is php 7.2.

I think that do this can be a way to invite people to update and have less support requests for old versions.

**Comment by tomjn** [comment]
Codacy scanning PHP is kind of broken, it needs to be changed to use an appropriate PHPCS standard, which means a `composer.json` and a PHPCS xml file in the dashboard repo

As for `php-yaml` it was only added 7 months ago, we haven't made many updates since then. Keep in mind that people tend to be put off by updates, and just put up with broken stuff or migrate elsewhere. Even if we did use `php-yaml` I'd have it fall back to what's in `yaml.php`

**Comment by Mte90** [comment]
So we can add this change for VVV 4? It will mean enough time and also a major, of course.

**Comment by tomjn** [comment]
I don't see a reason to change other than to satisfy Codacy for a coding standard we don't use.

Unless we intend to adopt PSR we should add a `phpcs.xml` to the dashboard repo. I'm not keen on our development decisions being determined just by the output of a tool, especially when `yaml.php` does the job without bugs right now.

If we did switch, I'd prefer the Symfony YAML component https://symfony.com/doc/current/components/yaml.html rather than depend on more apt packages.

**Comment by Mte90** [comment]
Looking at the code now at https://github.com/Varying-Vagrant-Vagrants/dashboard/blob/Mte90/support-meta-env/php/blocks/main/sites.php we support just php 7 so any requirement to use that library is kind of obsolete (and we are not supporting anymore old vvv version for this php requirement).

It is better to follows the standard and use that package also because we are using already `php-yaml` in a vvv-utilities https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/656ad9a8cdc91c8175410f69fafa30edd148c4ff/tideways/by-site.php#L9 so is already available in VVV.

**Comment by tomjn** [comment]
That would break the dashboard for a lot of people, I'd rather the dashboard told them to upgrade rather than breaking outright

**Comment by Mte90** [comment]
Well if it is an old VVV instance they cannot use the dashboard because they use php 5.6, I think that if we get the dashboard not working on those cases people will be forced to update.

**Comment by tomjn** [comment]
The dashboard would run on PHP 5.3+, and due to bugs in older VVV it may be running on 5.3 or 5.4. We shouldn't do this just to satisfy Codacy, especially when it's using an incorrect PHPCS ruleset. It is not worth the effort. Especially given that the longterm goal of this repo means it would need to be fundamentally changed anyway to a JS based frontend powered by a PHP based REST API. `yaml.php` stays.
