### ISSUE TITLE
Change database prefix

### ISSUE THREAD

**Issue by NLW-paulm** [Varying-Vagrant-Vagrants/VVV#2043]
HI, I cant work out how to change the database prefix for a site in my VVV setup.

In config.yml I have
custom:
      wp_version: latest
      db_prefix: swp_

I couldnt find anything on setting this in the documentation.

I have re-provisioned the site, but its still using the wp_ prefix, logging into the mariadb all the new tables are there, but im not sure how I can change the wp-config for this one site.

Versions
VVV - 3.2.0
Vagrant - 2.2.6

No errors during vagrant up --provision so im stumped.
Windows 10

**Comment by tomjn** [comment]
Are you setting the prefix, or are you changing the prefix on an already
provisioned site?

If the site already exists VVV won’t change it, you’ll have to manually
change the prefix via a database client and modifying the WP config file.

Otherwise changing the prefix for install will require you to install, aka
delete it and reprovision so it runs the install again.

Think of config as a restaurant order of what you want. If your table
already has food on it you can’t change your order after you’ve already
paid and left, not without resetting pieces and re-ordering

**Comment by NLW-paulm** [comment]
ahh im being a bit dumb, I was thinking it re-created the wp-file each time you provision (which I do a lot at the mo). Sorted, having a bad brain day! Apologies.
Thanks
Paul

**Comment by Mte90** [comment]
As I can see this is not supported https://github.com/Varying-Vagrant-Vagrants/custom-site-template I searched for this parameter on the repo without any results.

We can think to implement it
