### ISSUE TITLE
Import large database files: 504 Error

### ISSUE THREAD

**Issue by dashkevych** [Varying-Vagrant-Vagrants/VVV#2080]
What is  the best way to upload large database files? I was trying an import functionality in `vvv.test/database-admin/index.php` but I am getting 504 error.

Is there any documentation on how to perform a dump import in VVV?

Thank you!

**Comment by msaggiorato** [comment]
It's usually best to do it via CLI through SSH, not sure if we have any documentation for it tho.

If what you want to do is to put it in VVV alongside a WP install, then you can put it in your `public_html/wp-content` directory and name it `database.sql`. That should be picked up by the site provisioner and insert the database into the VVV structure.

Let me know if that helps.

**Comment by tomjn** [comment]
A 504 error means that whatever was generating the output never got in touch, which doesn't surprise me if you're trying to run a tonne of SQL commands.

> Is there any documentation on how to perform a dump import in VVV?

In this case, there is no VVV specific documentation because none is needed. Your problem is not a VVV problem and would happen anywhere. Different machines will stop working at different sizes depending on how quickly they can run the SQL, **but fundamentally,  PHPMyAdmin is not a great way to run expensive queries or upload large SQL files.** It can only work within the PHP time execution limit.

Still, we include PHPMyAdmin because it's useful for quick queries, but it shouldn't be relied on for heavy-duty work, the same goes for any other DB tool that runs in the browser

Instead, consider these other options that all have unlimited time to work with:

 - SSH in and use the `mysql` command
 - wp cli can import SQL files too
 - Connect directly to the database with a real DB client, such as HeidiSQL, Sequel Pro, MySQL Workstation, etc etc. You'll find a Sequel Pro config file in the `database` folder too for easy setup
 - Any other method of importing large SQL files! Once you've provisioned it's just a standard MariaDB install, so you don't need to know VVV specific things other than the host and default user/pass!

> If what you want to do is to put it in VVV alongside a WP install, then you can put it in your public_html/wp-content directory and name it database.sql. That should be picked up by the site provisioner and insert the database into the VVV structure.

This will only work if the site hasn't been set up yet. If it's already installed this will get skipped
