### ISSUE TITLE
Can't seem to change the default version of PHP

### ISSUE THREAD

**Issue by theMikeD** [Varying-Vagrant-Vagrants/VVV#2082]
Hi there,

I have a `config.yml` file that among other things contains the following:
```
---
sites:
  mysite:
    vm_dir: /srv/www/mysite
    nginx_upstream: php73
```
and a bit further down
```
utilities:
  core: # The core VVV utility
    - memcached-admin # Object cache management
    - opcache-status # opcache management
    - phpmyadmin # Web based database client
    - webgrind # PHP Debugging
    - trusted-hosts # GitHub etc
    - tls-ca # SSL/TLS certificates
    #- mongodb # needed for Tideways/XHGui
    #- tideways # PHP profiling tool, also installs xhgui
    #- php56
    #- php70
    # php71
    #- php72
    - php73
```
However once I provision, vvv.test tells me that php 7.2 is running, and on the command line I get

```
vagrant@vvv:~$ php --version
PHP 7.2.28-3+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:23:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.28-3+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

How is 7.2 even being installed, and why is 7.3 not being used? According to the docs, this should be working right? It does in fact set the correct version of php for this server specifically, but not CLI and not default. I don't need 7.2 at all...how can I just use 7.3?

**Comment by tomjn** [comment]
That makes sense, on CLI PHP uses 7.2, and `vvv.test` uses PHP 7.2 as well

When you say this:

```yaml
  mysite:
    vm_dir: /srv/www/mysite
    nginx_upstream: php73
```

You're saying that the site `mysite` uses PHP 7.3. This isn't the same as setting the default PHP, it only sets 7.3 for that site. Of course this is all assuming your Nginx config file has the appropriate upstream parameter

> How is 7.2 even being installed,

Because the core VVV provisioner always installs it, it's non-negotiable.

> and why is 7.3 not being used?

It is, on `mysite`, as the config specifies. If specifying PHP 7.3 for `mysite` meant that all CLI and dashboard uses 7.3, then what would happen if you had `site1` using PHP 7.1, and `site2` using PHP 7.4, which version of PHP would CLI use?

If the goal is to use PHP 7.3 on CLI, that's not something you can set in `config.yml`, but it can be done via `vagrant ssh` using the standard commands you'd use on any VPS:

https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/blob/master/php73/provision.sh#L104-L109

A good question might be why not add a setting to `config.yml` to specify the default PHP version. The problem there is that if you set it to PHP 7.3, that version of PHP gets installed via utilities, and utilities run after the core provisioner. So what will the core provisioner do when it needs to run PHP based tools such as composer if PHP hasn't been installed yet :(

Other notes:

 - There's no `hosts` section! That means no SSL certificates, no fast host provisioning, no dashboard links, etc. There are various other downsides to using `vvv_hosts`, assuming you use it at all, but I'd strongly recommend adding a hosts section
 - You've specified `vm_dir`, but there is no `local_dir`, these two come as a pair, and are non-negotiable. Even then the default value would have been `/srv/www/mysite` anyway, so that parameter can just be deleted

**Comment by theMikeD** [comment]
Ah, OK I understand now. Thanks for the explanation!

**Comment by Mte90** [comment]
There is something that we can do to help on debug this error? maybe add some alerts?

**Comment by theMikeD** [comment]
I think it's less an error and more of a misunderstanding. The only suggestion I could make would be to add some stuff to the docs about which php version is default, and what setting a version actually does...?

**Comment by tomjn** [comment]
My thoughts are that the dashboard can state which PHP version is being used for each site, and the site provisioner can state it

**Comment by tomjn** [comment]
Doesn't hurt to open new issues for dashboard tweaks :)
