### ISSUE TITLE
Support https for WordPress setting URLs in the config

### ISSUE THREAD

**Issue by truongwp** [Varying-Vagrant-Vagrants/VVV#2147]
I want to use `https`. After creating a new site and provisioning, I must go to `Settings > General` and change `WordPress Address (URL)` and `Site Address (URL)` from `http` to `https`. It will be great if I can set those URLs to https by default in the config file.

**Comment by Mte90** [comment]
There is the tls-ca utilities that enabled the support for those.
Check your config.yml and our documentation https://varyingvagrantvagrants.org/docs/en-US/references/https/

We don't want to force https as default in the settings for issues with certificates locally and for compatibility (also usually locally https is not used).

**Comment by truongwp** [comment]
Sorry. Maybe my issue description is not clear enough. I would like to have a config entry for each site, for example: `- https_url: false # false by default`. If I set it to `true`, the WordPress URLs settings will use `https` after creating site.

Currently, after creating a site, I must login to wp-admin, change the URLs to https and then login again. I want to reduce this step.

**Comment by Mte90** [comment]
Implement this is not so easy as you define, this require this command that will be executed at every provision:
```
wp search-replace http://domain https://domain
```
That is not very fast and require also a check inside the database to see if the database is already ported to https (to avoid to repeat again).
Right now on a new website installed is enough what you say but on a website that is already used since a while don't execute this command will not fix all the urls in the database.
As example, I have a website locally with 1gb database this command will require a lot of time.

So is better to execute manually because is not good that VVV does a search-replace for the user with the risk of breaking something.

**Comment by truongwp** [comment]
Ok. I understand. Thank for spending time on this issue :+1:
