### ISSUE TITLE
Private GitHub repo returns "Permission denied (publickey)" on provision

### ISSUE THREAD

**Issue by pnpetroff** [Varying-Vagrant-Vagrants/VVV#2186]
## What was The Command Used To Provision

```shell
vagrant up --provision
```
```shell
vagrant provision
```

## What Kind of VVV Provision Was This

This was a fresh install

## Logs/What Broke

I have added a custom project in the config.yml file:
```
wp-falconio:
  skip_provisioning: false
  description: "falcon.io"
  repo: git@github.com:FalconSocial/wp-falconio.git
  hosts:
    - wp-falconio.test
```

When Vagrant starts provisioning the directory it returns the following error:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

[Link to the full log.](https://gist.github.com/pnpetroff/eac191a9fa692921be7d8c3ee93c965e)

`ssh -T git@github.com` is successfull. It's also succesfull in `vagrant ssh`.

## Possible Solution
There is probably something wrong with the key that is used? I'm on Windows 10 with the default Git key client.

## Steps to Reproduce (for bugs)
1. Install Vagrant
2. Install latest VVV (even the dev branch)
2. Install latest VirtualBox
3. Run `vagrant status` and add the project in the `config.yml` file.
4. Run `vagrant up --provision`

## Your Environment

Operating System: Windows 10

```
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.5.0-zip-no-vcs

Platform: platform-mingw32 windows  HasWinAdminPriv  vagrant-hostsupdater NoColour shared_db_folder_disabled, VVV Path: "D:/falconi
o/vvv"
Vagrant: v2.2.9, VirtualBox: v6.1.10r138449
```

**Comment by Mte90** [comment]
If you use the git protocol instead of https it is normal to get this error because require authentication.
It is better to use the HTTPS version as we do in the `config.yml` for the various repo.

**Comment by tomjn** [comment]
key forwarding should allow the use of the SSH version, we use https urls because most users when they use it for the first time don't know what SSH keys are and haven't set them up, or know what an SSH Agent is

If you try to clone the repo manually does that work? Is it just that repo or all github repos?

And more specifically, what's inside the repo? VVV is expecting something that tells it how to provision the site, but if that repo is instead the site itself then it won't have a `provision.sh` or an Nginx config, and you'd get warnings and a non-functional site

**Comment by tomjn** [comment]
I've reopened as permission denied might be for a number of things, and SSH URLs can work.

I've double checked to try and reproduce with a `wordpress-three` site:

```yaml
  wordpress-three:
    repo: git@github.com:Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      install_plugins:
        - query-monitor
    hosts:
      - three.wordpress.test
```

Which worked for me:

```
    default: ------------------------------------------------------------------------------------
    default:  ▷ Running the 'site-wordpress-three' provisioner...
    default: ------------------------------------------------------------------------------------
    default:  * Downloading wordpress-three, git cloning from git@github.com:Varying-Vagrant-Vagrants/custom-site-template.git into /srv/www/wordpress-three
    default: Warning: Permanently added the RSA host key for IP address '140.82.118.3' to the list of known hosts.
    default:  * wordpress-three Site Template clone successful
    default:  * Adding domains to the virtual machine's /etc/hosts file...
    default:  * Adding hosts from the VVV config entry
    default:    - Added three.wordpress.test from /vagrant/config.yml
```

@pnpetroff can you do the same and let us know if that works? We need to distinguish if it's an SSH problem or a private repo problem

**Comment by pnpetroff** [comment]
> If you use the git protocol instead of https it is normal to get this error because require authentication.
> It is better to use the HTTPS version as we do in the `config.yml` for the various repo.

The [documentation says](https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/#how-do-i-work-with-private-gitlabgithub-repositories) that I should be using the SSH URLs for private repos.

Switching `git@github.com:FalconSocial/wp-falconio.git` to `https://github.com/FalconSocial/wp-falconio` gives the following error:

```
default:  ▷ Running the 'site-wp-falconio' provisioner...
default: fatal: could not read Username for 'https://github.com': No such device or address
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

> If you try to clone the repo manually does that work? Is it just that repo or all github repos?
> 
Cloning in `vagrant ssh` into the `/srv/www/` directory works but provisioning fails after that because "there is an already WordPress installation in there".

> @pnpetroff can you do the same and let us know if that works? We need to distinguish if it's an SSH problem or a private repo problem

@tomjn Thank you for taking a look at this. Unfortunately, It still shows the same error:

```
▷ Running the 'site-wordpress-three' provisioner...
default: Warning: Permanently added the RSA host key for IP address '140.82.118.3' to the list of known hosts.
default: git@github.com: Permission denied (publickey).
default: fatal: Could not read from remote repository.
default:
default: Please make sure you have the correct access rights
default: and the repository exists.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I'm open to any suggestions for tests on my side.

**Comment by tomjn** [comment]
So this isn't related to private/public repos, it looks like this is a basiic SSH issue, specifically SSH keys

> I'm open to any suggestions for tests on my side.

Do you have an SSH Agent active and running? Vagrant forwards the SSH agent allowing VVV to use all the same SSH keys etc the host can, but that does not appear to be happening here. As you're using a Windows machine, can you confirm the SSH agent is running as expected on the Windows host?

> Cloning in vagrant ssh into the /srv/www/ directory works but provisioning fails after that because "there is an already WordPress installation in there".

Without knowing the details of what happened in the provisioner log it's super difficult to debug that, but I'd like to focus instead of being able to create the custom site template example I used above in the situation where no folder exists so that we aren't crossing wires

**Comment by tomjn** [comment]
There's also the possibility that SSH key forwarding has been turned off. That's happened in the past where users have had problems figuring out what's going on, then found a line in their hosts SSH config turning off forwarding

**Comment by tomjn** [comment]
Also make sure to check through https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/#how-do-i-work-with-private-gitlabgithub-repositories

**Comment by pnpetroff** [comment]
I've went through all of these earlier.

`ssh-add -L` returns the same on host and guess.
`ssh -T git@github.com` too.
`echo "$SSH_AUTH_SOCK"` and `eval `ssh-agent` also return on both machines.

`.ssh/config` looks like this:
```
Host github.com
  ForwardAgent yes
```
Although I'm not really sure if Windows uses it. I've also added it to `C:\Program Files\Git\etc\ssh\ssh_config` for another try and unfortunately it's not working again.

**Comment by tomjn** [comment]
I don't use Windows enough personally to know many more troubleshooting steps for the SSH Agent, but that is the root of your problem. Host SSH keys aren't being forwarded to the guest VM

> .ssh/config looks like this:

I believe this allows an SSH session on github.com to use your keys, but github does not offer SSH sessions. `ForwardAgent` doesn't let you whitelist domains you can use keys to connect to. It's the other way around. `ForwardAgent defines places you can use keys to connect with.

Did you try the example from the docs?

```
Host *
   UseKeychain yes
   AddKeysToAgent yes
```

**Comment by pnpetroff** [comment]
> Did you try the example from the docs?

Yes, I tried that too.

If the problem is in the SSH forwarding wouldn't that mean that `git clone` shouldn't work on the guest machine? Because it works here.

Can I somehow create my project and the `/www` directory and run provision without any git queries?

**Comment by tomjn** [comment]
At this point there's very little on the VVV side of things that can help here. The problem is your setup does not forward SSH keys during provisioning. It **should** work if everything is set up correctly.

At the moment if I had to speculate, it's that your SSH Agent does not auto-start, so when you're provisioning it is not available, but when you SSH in manually later on it's after it has started. But I would need information to be able to debug that, and you're a Windows user, I'm not a Windows user.

> Can I somehow create my project manually in the /www directory and run provision without any git queries?

Yes, you can just git clone manually, then reprovision. I suspect however that the repo it's trying to clone is not a site template, but a WP install. This means you'll get a barrage of warnings about missing `provision/provision.sh`, and the site will fail to load due to a missing Nginx config. I cannot see that repo though as it's private. Just remember, the `repo` field is not for acquiring the website, it's for acquiring the site template provisioner

**Comment by tomjn** [comment]
And if you check your `git` config values inside the guest, do they match your host? If you `ssh -T git@github.com` in the guest who does it think you are?

If you run anymore commands, can you include their output here? Wether they work or not?

**Comment by pnpetroff** [comment]
> do you have multiple SSH keys configured?
There is only one.
```
ls -al ~/.ssh
```
Result:
```
./
../
agent.env
config
id_rsa
id_rsa.pub
known_hosts
```
> Since you made changes to the ssh config, did you restart the SSH Agent?
Yeah, I tried the following:
```
eval "$(ssh-agent -s)"
>> Agent pid 1088
kill -9 1088
ssh git@github.com
>> Enter passphrase for key '/c/Users/Admin/.ssh/id_rsa':
>> PTY allocation request failed on channel 0
>> Hi pnpetroff! You've successfully authenticated, but GitHub does not provide shell access.
>> Connection to github.com closed.
eval "$(ssh-agent -s)"
>> Agent pid 1103
```

`PTY allocation request failed on channel 0` but it still connects.

> Did you use the example from the docs, or my copy paste of the example from the docs? ( both have been edited since originally asked )

I stopped debugging with my private repo and only use the example from above:
```
 wordpress-three:
    repo: git@github.com:Varying-Vagrant-Vagrants/custom-site-template.git
    custom:
      install_plugins:
        - query-monitor
    hosts:
      - three.wordpress.test
```

> Do you have security software/VPN software that can interfere?
Yes, I've tried with and without.

> Do you have security software/VPN software that can interfere?
Everything is disabled. Just and antivirus but I tried with it turned off too.

> Is the D: drive a normal drive with a filesystem on a physical disk/SSD? Or is it a special drive such as a network share or other mapped filesystem?
Yes, `D:` is a normal NTFS system.


> If you ssh -T git@github.com in the guest who does it think you are?
Absolutely the same on host. 

The following commands are all in the guest
```
ssh -T git@github.com
>> Warning: Permanently added the RSA host key for IP address '140.82.118.3' to the list of known hosts.
>> Hi pnpetroff! You've successfully authenticated, but GitHub does not provide shell access.

echo "$SSH_AUTH_SOCK"
>> /tmp/ssh-MwaSGGF7eb/agent.3408

ssh -v git@github.com
>> OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
>> debug1: Reading configuration data /etc/ssh/ssh_config
>> debug1: /etc/ssh/ssh_config line 19: Applying options for *
>> debug1: Connecting to github.com [140.82.118.3] port 22.
>> debug1: Connection established.
>> debug1: key_load_public: No such file or directory
>> debug1: identity file /home/vagrant/.ssh/id_rsa type -1
>> debug1: key_load_public: No such file or directory
>> debug1: identity file /home/vagrant/.ssh/id_rsa-cert type -1
>> debug1: key_load_public: No such file or directory
>> debug1: identity file /home/vagrant/.ssh/id_dsa type -1
>> debug1: key_load_public: No such file or directory
>> debug1: identity file /home/vagrant/.ssh/id_dsa-cert type -1
>> debug1: key_load_public: No such file or directory
>> debug1: identity file /home/vagrant/.ssh/id_ecdsa type -1
>> debug1: key_load_public: No such file or directory
>> debug1: identity file /home/vagrant/.ssh/id_ecdsa-cert type -1
>> debug1: key_load_public: No such file or directory
>> debug1: identity file /home/vagrant/.ssh/id_ed25519 type -1
>> debug1: key_load_public: No such file or directory
>> debug1: identity file /home/vagrant/.ssh/id_ed25519-cert type -1
>> debug1: Local version string SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
>> debug1: Remote protocol version 2.0, remote software version babeld-7acd8e37
>> debug1: no match: babeld-7acd8e37
>> debug1: Authenticating to github.com:22 as 'git'
>> debug1: SSH2_MSG_KEXINIT sent
>> debug1: SSH2_MSG_KEXINIT received
>> debug1: kex: algorithm: curve25519-sha256
>> debug1: kex: host key algorithm: rsa-sha2-512
>> debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
>> debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
>> debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
>> debug1: Server host key: ssh-rsa SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
>> debug1: Host 'github.com' is known and matches the RSA host key.
>> debug1: Found key in /etc/ssh/ssh_known_hosts:1
>> debug1: rekey after 134217728 blocks
>> debug1: SSH2_MSG_NEWKEYS sent
>> debug1: expecting SSH2_MSG_NEWKEYS
>> debug1: SSH2_MSG_NEWKEYS received
>> debug1: rekey after 134217728 blocks
>> debug1: SSH2_MSG_EXT_INFO received
>> debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,rsa-sh
>> a2-512,rsa-sha2-256,ssh-dss>
>> debug1: SSH2_MSG_SERVICE_ACCEPT received
>> debug1: Authentications that can continue: publickey
>> debug1: Next authentication method: publickey
>> debug1: Offering public key: RSA SHA256:nZcX2HXAM7npWjL+At68S8X8F4YOa8xZbHeIhHBGCCs Admin@DESKTOP-E8JPN89
>> debug1: Server accepts key: pkalg ssh-rsa blen 407
>> debug1: Authentication succeeded (publickey).
>> Authenticated to github.com ([140.82.118.3]:22).
>> debug1: channel 0: new [client-session]
>> debug1: Entering interactive session.
>> debug1: pledge: network
>> debug1: Sending environment.
>> debug1: Sending env LANG = C.UTF-8
>> PTY allocation request failed on channel 0
>> debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
>> Hi pnpetroff! You've successfully authenticated, but GitHub does not provide shell access.
>> debug1: channel 0: free: client-session, nchannels 1
>> Connection to github.com closed.
>> Transferred: sent 3344, received 2376 bytes, in 0.3 seconds
>> Bytes per second: sent 12227.0, received 8687.6
>> debug1: Exit status 1

```


This is in my ssh config files:
```
Host github.com
   ForwardAgent yes
```

`Host *` doesn't seem to work. `ssh-add -l` returns "The agent has no identities."

**Comment by tomjn** [comment]
> This is in my ssh config files:

> ssh-add -l returns "The agent has no identities."

Are these on the host? `ssh-add -l` gives me a single entry for my SSH key on the host. It also gives that same entry when ran in the guest. Neither should say that there are no identities. **This implies that no key was added to the SSH Agent on the host**. Just because you have a key doesn't mean it's picked up automatically by the agent.

My own SSH config looks like this:

```
Host github.com
    MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512

Host *
	ConnectTimeout 30
	KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
	MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
	Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
	ServerAliveInterval 10
	ControlMaster auto
	ControlPersist yes
	ControlPath ~/.ssh/socket-%r@%h:%p
	AddKeysToAgent yes
	UseKeychain yes
	ForwardAgent yes
```

`ForwardAgent` shouldn't be in `Host github.com`. If you were to add it to a specific host it would be the IP of the guest VM. I recommend removing it as it doesn't do what you think it does. Note that my own config has a lot of cipher related items that shouldn't impact SSH forwarding

It should be enough to end the config with this:

```
Host *
	AddKeysToAgent yes
	ForwardAgent yes
```

Is this running in a generic Windows command line, or is it running in a layer such as WSL or git bash?

 `ssh-add -l` should return at least 1 entry on the host, and that entry should appear when `ssh-add -l` is ran on the guest.

**Comment by pnpetroff** [comment]
This is my config file:
```
Host *
	AddKeysToAgent yes
	ForwardAgent yes
```

`ssh-add -l` on host returns:
```
4096 SHA256:DwJsz63G2mLe1BmN7+lCl9jlJwXjyyAj7xi1Fs89PDA MYEMAIL@gmail.com (RSA)
```
`ssh-add -l` on guest returns:
```
4096 SHA256:DwJsz63G2mLe1BmN7+lCl9jlJwXjyyAj7xi1Fs89PDA MYEMAIL@gmail.com (RSA)
2048 SHA256:1M4RzhMyWuFS/86uPY/ce2prh/dVTHW7iD2RhpquOZA C:/Users/Admin/.vagrant.d/insecure_private_key (RSA)
```

Results are the same in Git Bash and the Windows Terminal.

OpenSSH services in `services.msc` are running too:
![image](https://user-images.githubusercontent.com/1108563/84575797-9eead800-adb8-11ea-980a-e59e431a3ba6.png)

**Comment by tomjn** [comment]
And it still says it cannot clone SSH url repositories from GitHub on provision?

> OpenSSH services in services.msc are running too:

My understanding is that OpenSSH in Windows is quite a recent change. It's probably unrelated to the code pathways that are being used here.

---

I'm afraid at this point as a Mac user the only thing I can advise is to check the status of the SSH Agent and that everything is as it's supposed to be configured, and try a system reboot.

There are no VVV specific debugging steps here, what we've been debugging so far is SSH configs, SSH Agent, and possibly vagrant itself. VVV operates under the assumption it is all working, the only part that actually messes with SSH agents is the bit in the vagrant file that says we want forwarding enabled:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L390-L394

Other than that it doesn't require any config values, perform any checks, or set any special options. If you have issues with provisioners not being able to use SSH keys from the host, it's overwhelmingly likely that it's an SSH configuration issue on the host. Perhaps the agent is not setup to auto-start ( the SSH agent is not the OpenSSH service ), isn't configured to forward, hasn't reloaded with a new SSH config, is missing SSH keys either because they dont exist or weren't added. There's a tiny chance this is a Windows + Vagrant issue, but that's very unlikely.

Clearly from your output keys are being forwarded when you use `vagrant ssh`. I'm also curious, if provisioning has no SSH agent, but `vagrant ssh` does, what if you provision after a `vagrant ssh`?

@benlumia007 do you know anything about this? I'm not a windows user so I'm struggling to think of anything more here. Clearly something is missing or misconfigured but I don't know enough about WIndows to be able to help.

**Comment by benlumia007** [comment]
make sure to add the public key to the GitHub website under the settings.

**Comment by pnpetroff** [comment]
> Clearly from your output keys are being forwarded when you use `vagrant ssh`. I'm also curious, if provisioning has no SSH agent, but `vagrant ssh` does, what if you provision after a `vagrant ssh`?

How can I achieve that? `vagrant provision` returns:
```
Command 'vagrant' not found, but can be installed with:

apt install vagrant
Please ask your administrator.
```

> make sure to add the public key to the GitHub website under the settings.
@benlumia007 Yes, it's added. I even generated a new key after reinstalling everything.

**Comment by tomjn** [comment]
Vagrant is the tool that spins up the VM and runs the VVV provisioners. It
doesn’t make sense to run it inside the VM. The vagrant ssh command opens
an SSH session inside the guest VM.W

**Comment by pnpetroff** [comment]
I see what you mean. Yeah, I did a `vagrant ssh` and after that provisioned. Still the same.

I even upgraded my Windows 10 from Home to Pro and it's still the same.

**Comment by benlumia007** [comment]
did u try using puttygen to create keys and try that.

**Comment by benlumia007** [comment]
ptuttygen, putty pageant,  windows is not the same is mac or Linux, everytime when you restart your computer, it will ask you for enter the passphrase if you have one. 

addd this to your .bash_profile and source it

```
env=~/.ssh/agent.env

agent_load_env () { test -f "$env" && . "$env" >| /dev/null ; }

agent_start () {
    (umask 077; ssh-agent >| "$env")
    . "$env" >| /dev/null ; }

agent_load_env

# agent_run_state: 0=agent running w/ key; 1=agent w/o key; 2= agent not running
agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)

if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
    agent_start
    ssh-add
elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
    ssh-add
fi

unset env
```

**Comment by benlumia007** [comment]
https://help.github.com/en/github/authenticating-to-github/working-with-ssh-key-passphrases

**Comment by benlumia007** [comment]
and i believe if u use git@github.com:username/xxxx.. by default it uses the master branch.

**Comment by benlumia007** [comment]
all this is udner the host computer ( windows 10 )

**Comment by pnpetroff** [comment]
Yeah, I've read all of these links and have that code in `.bash_profile` and still nothing.

Tried generating an SSH key in putty in still didn't work.

BUT using the *.ppk file and adding it to Pageant worked! I don't know what was causing this and where the SSH problem was (neither Open SSH and the native Windows solution worked) security but I'm leaving it like this.

Thank you for all the help, guys. I'm sorry I couldn't really find the culprit to share it here.

**Comment by tomjn** [comment]
That’s interesting 🤔 that should give us clues for reproducing and
debugging

**Comment by benlumia007** [comment]
yeah, but then windows does things very very idiotic in some things but i knew putty, pageant works because I've done so I thought i mentioned it earlier. 

but  at least it solves your problem so cool :p

**Comment by pnpetroff** [comment]
Felt great, actually couldn't believe.

I'm still curious about this issue so If you want me to run some tests in the future just tag me here.
