### ISSUE TITLE
Should Site Template init a new  git repo in public_html?

### ISSUE THREAD

**Issue by tomjn** [Varying-Vagrant-Vagrants/VVV#2235]
After reading #2234 I wonder if we should explicitly `git init` in the public webroot folder before installing WP etc in there in the custom site template?

**Comment by Mte90** [comment]
This should not create a git repo empty?

**Comment by tomjn** [comment]
It’d be an empty git repo but it would be a separate repo from the
provisioner template repo.

**Comment by Mte90** [comment]
What it is the purpose to create an empty repo? So people can create a new one because already exists?

**Comment by jd4u** [comment]
As I understand "custom-site-template.git" is a template, and that should once implemented become a part of the new site as implementation of template, instead of keeping it a template by keeping .git.

Process can be like following.
- create site folder "A"
- download template in folder "A/template" 
- create two folders "A/provision" and "A/public_html" and work further on.
- put a readme.md in A folder instructing the design and expected workflows and warning.
- never remove anything outside "A/template".

**Comment by Mte90** [comment]
> As I understand "custom-site-template.git" is a template, and that should once implemented become a part of the new site as implementation of template, instead of keeping it a template by keeping .git.

That template is used by VVV and don't involve the website also if called template, so it is just internal. The git folder of that template is important to check if it is updated because it will download code to update as example the nginx settings or other things, so that folder is required and is still there since VVV 1.

>     * create site folder "A"
That folder is public_html that is a similar name on web hostings, but it is customizable with a fork (or a parameter if I can remember right).

>     * download template in folder "A/template"

We use the provision folder for that and include the nginx config and the bash script but everyone can put there whatever they need in their template.

>     * create two folders "A/provision" (for any custom script, not of the template) and "A/public_html" and work further on.

>     * put a readme.md in A folder instructing the design and expected workflows and warning.

This is something that we can do for sure, maybe with the downloading of the readme of the template itself that should incldue this information.

>     * never remove anything outside "A/template".

This is not handled by us but by git, the last patch of today of Tom avoid that someone can add files to the template repo and avoid those cases at all.

**Comment by tomjn** [comment]
> As I understand "custom-site-template.git" is a template, and that should once implemented become a part of the new site as implementation of template, instead of keeping it a template by keeping .git.

For the provisioner, but not the site. Think of it as a template used to create a site, not a template that becomes a site.

Changing how site templates work ata  fundamental level is not something that can be done without major disruption for the entire user base. We would need to introduce something brand new in VVV 4.

Also, this introduces new problems:

 - how would we pull down bugfixes
 - how would you create a site that already has a git repo
 - where would upstream/remote be?

**Comment by jd4u** [comment]
To my understanding, VVV is just a provisioning approach to development environment. It will update dev-env as an when required and help in removing the task from developer to setup and maintain.

VVV shall work to achieve following 
1] Separate concerns/aspects of 
- VVV requirements (like a site template that provision runtime )
- Dev-env targeted components (like WordPress )
- Actual development workspace (having themes, plugins, docs, libs, one or more git repo, etc. totally managed by dev)
2] Maintain states of first two concerns/aspects to keep updates going on.
3] Provide mapping between workspace to target components via soft links or change copies.

I will try to understand VVV's complete process in coming days. May be I find some steps to solve those three issues noted by you.

**Comment by Mte90** [comment]
> To my understanding, VVV is just a provisioning approach to development environment. It will update dev-env as an when required and help in removing the task from developer to setup and maintain.

Yes like all the other competitors like Chassis, Lando or custom based like Docker or on Vagrant like this project. They provision in a way or another in different levels and completeness based on the needs.

>     * VVV requirements (like a site template that provision runtime )

Well VVV is more advanced than this. VVV download and execute various installer, the right name is provisioner because they also update and generate config files with keeping the support with old/previous instances (with a specific time frame).  
This is already separated because VVV execute them on vagrant up/provision/halt so you do just once. In case of provisioning will do also a lot of stuff like installing utilities like TLS-CA certificates or php 7.4 as example. Including also site templates that can be for wordpress development or contributions.

> 1] Separate concerns/aspects of

So this is already separated because are different repositories, we are working in this period to improve their isolation in VVV can run also outside of Vagrant like in Docker or with Ansible.

So as user you just need to update your config, do a provision (with the `custom-site-template`) and develop inside the wordpress root of your website (as basic usage but you can do more and in various way).

My suggestion is to check https://varyingvagrantvagrants.org and see if everything is clear and in case open a new ticket about just update the documentation because we are discussing a specific adding to `custom-site-template`.

**Comment by jd4u** [comment]
"1] Isolation of concerns/aspects for" is more appropriate instead of "1] Separate concerns/aspects of" in my last comment.

**Comment by tomjn** [comment]
Refactoring provisioners isn't the goal of this issue

**Comment by jd4u** [comment]
#https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2234#issuecomment-687350328

Isolated vvv and dev, with help of Customfile.

**Comment by tomjn** [comment]
Closing this as there are better ways to manage this and it doesn't fit in with how things work
