### ISSUE TITLE
wp-content outside root doesn't work correctly

### ISSUE THREAD

**Issue by pnpetroff** [Varying-Vagrant-Vagrants/VVV#2252]
I want to move **wp-config.php** and **wp-content** one dir up - just outside the root like this:

![scrn2](https://user-images.githubusercontent.com/1108563/95176548-b0237e80-07c5-11eb-903b-3e64be14145c.jpg)
Added the following line to the **wp-config.php** (before the **wp-settings.php** line):
```
define( 'WP_CONTENT_DIR', dirname( __FILE__ ) . '/wp-content' );
```

The themes and plugins are there when I go to the admin dashboard but it looks like the resource paths (images, CSS, JS) are broken:

![scrn](https://user-images.githubusercontent.com/1108563/95176727-f11b9300-07c5-11eb-87e2-ca8a97793c8e.jpg)

I'm using the default *wordpress-one* installation without any **config.yml** changes. Also the latest VVV 3.4.1 version.

Is there a step that I am missing before/after provisioning?

**Comment by tomjn** [comment]
You can move `wp-config.php` one level up, but you cannot move `wp-content` out of `public_html`. If you do this then there's no way to load assets externally. This is true of VVV but it's also true of any host be it local or live.

Can I ask _why_ you're trying to move `wp-content` up one folder?

**Comment by pnpetroff** [comment]
Thank you @tomjn for the quick answer (as always)!

I am trying to move it outside because together with some other files I wanted to make it easier for version control. Everything in the same dir and just gitignore the public_html directory.

**Comment by tomjn** [comment]
hmmmm would a WP subdirectory install not achieve the same goal?

**Comment by pnpetroff** [comment]
I was thinking about this while I was writing the above message. I guess [this](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1971#issuecomment-543292734) is what I need to know.

In addition is there a way to make the **wordpress-one** directory root? Will just removing the *public_html* part from **vvv-init.sh** and **vvv-nginx.conf** work? I know I will expose the provision directory this way but this will be for the dev environment only.

**Comment by tomjn** [comment]
Sort of, **but I wouldn't recommend it**, and it will cause lots of new and harder problems. Just set the public html parameter to an empty string in `config.yml` as documented on the site template readme for that site, no modifications to the provisioners are necessary. But it will not help you, in fact it will do the opposite.

If your goal is to simplify version control management, then moving everything up will cause a fundamental problem, namely, there's already a `.git` folder in that location, so from a version control point of view moving everything up 1 folder is somewhat of a disaster since it introduces lots of new problems and replicates a very unusual and insecure server environment.

I don't see how any of this improves git workflow. My recommendation would be to have a git repo that represents a `wp-content` folder, and clone that to `wp-content`. This is how a lot of hosts work, e.g. WP Engine or VIP Go. If you switch to the `develop` branch you can even tell VVV to clone that repo into the appropriate place ( see https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2247 ).

Otherwise, moving stuff ***up*** is rarely the answer, it would be better to move things _down_ instead.

**Comment by tomjn** [comment]
More to the point, if you just open the `wp-content` folder in VS Code and symlink in `wp-config.php`, how would you know the difference between a subdir install, a classic install, or something else? Would it even matter?

**Comment by pnpetroff** [comment]
Thank you for the detailed explanations. Really helpful to plan my project structure!

**Comment by tomjn** [comment]
I'm closing this but if you have any more questions let us know
