### ISSUE TITLE
Failed to fetch packages on vagrant up or vagrant up --provision

### ISSUE THREAD

**Issue by Andre2SM** [Varying-Vagrant-Vagrants/VVV#2293]
## What was The Command Used To Provision

```shell
provision up
```

## What Kind of VVV Provision Was This

This was a fresh install

## Logs/What Broke

```yaml
- Provisioner log https://gist.github.com/Andre2SM/0ec1d9e7076524037d213d7cbaaf0290
- Config file https://gist.github.com/Andre2SM/f27b4b0fddc453ee0cd30e216182e605
```

## Your Environment

Operating System: Windows 10 Home Single Language
__ __ __ __
\ V\ V\ V / Varying Vagrant Vagrants
 \_/\_/\_/  v3.4.1-git::stable

Platform: platform-mingw32 windows  vagrant-hostsupdater shared_db_folder_disabled, VVV Path: "F:/sitios-web"
Vagrant: v2.2.10, VirtualBox: v6.1.16r140961

**Comment by tomjn** [comment]
@Andre2SM your provisioner log cuts off all the vagrant specific output, it contained a tonne of info we output so that when people open github issues we don't have to ask them a tonne of questions

However, your problem is simple, this is right at the very end of the log:

> E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/x/xdebug/php8.0-xdebug_2.9.8+2.8.1+2.5.5+3.0.0~beta1-2+ubuntu18.04.1+deb.sury.org+1_amd64.deb  **_Connection timed out [IP: 91.189.95.83 80]_**
> E: Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/x/xdebug/php7.3-xdebug_2.9.8+2.8.1+2.5.5+3.0.0~beta1-2+ubuntu18.04.1+deb.sury.org+1_amd64.deb  _**Connection timed out [IP: 91.189.95.83 80]**_
> E: Aborting install.

Connection timed out. However hard we try, if your network connection is unstable, or the remote server hosting all the packages goes down, there's nothing we can do but try again.

I'm assuming the command you ran was `vagrant up --provision`, so re-run it until it works, and consider trying on a different network.
