### ISSUE TITLE
Upgrade or use different version of nodejs than v10

### ISSUE THREAD

**Issue by atomtigerzoo** [Varying-Vagrant-Vagrants/VVV#2332]
Is it possible to use another version of nodejs and if, then how?

I tried upgrading via terminal but it fails with permission errors.

I found that in /provision/core/nodejs/provision.sh a check is enabled for version higher than 10. Why is that? Can I override this somehow by changing the check and the apt sources to a newer version?

**Comment by tomjn** [comment]
This was done because WP core would only build in Node v10. We do have an nvm utility that can be used if you need other versions. I'd be open to upgrading Node if WP core builds on newer versions ( the package.json appears to have been updated to Node 14.15.0 )

Note that if you want Node to run file watchers, you're better off running them either on the host, or in a non-shared folder. It might work okay for you but it may also miss file changes sometimes due to micro-caches

**Comment by tomjn** [comment]
If this were changed, I'd expect the code to remain the same, but to enforce Node 14 rather than Node 10

**Comment by atomtigerzoo** [comment]
Thank you for the clarification with the WP core build - makes sense then.

I will try the nvm option for now 🙃

**Comment by tomjn** [comment]
@atomtigerzoo in theory this PR should resolve your issue by upgrading to Node v14: https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2333

It's untested though. It'd be a great help if you can switch to that branch, reprovision, then check that all is good. If it isn't, post the terminal output in the PR as well as `node --version`
