### ISSUE TITLE
Run VVV without goodhosts, instead reach over IP

### ISSUE THREAD

**Issue by cueqzapper** [Varying-Vagrant-Vagrants/VVV#2334]
I want to run VVV without goodhosts, since this edits hosts file and I don't like that.

Solution: Is there a setting to remove goodhosts and instead reach the websites over the defined IP address. It can't find an option to remove goodhosts.

**Comment by Mte90** [comment]
Uhm I think that VVV works with ip address but as it is a multi host web server you get the `vvv.test` domain.
So without ip routing you cannot get a specific site and it became useless, the reason why we have also goodhosts.

**Comment by tomjn** [comment]
> since this edits hosts file and I don't like that.

**That's not possible**, without a domain there is no way for Nginx to route traffic to the correct site. The only site that will work is the dashboard which auto-redirects to vvv.test anyway.

**So even if you removed goodhosts it would not give you what you want.** You would still have to modify the hosts file manually.

[However I suspect that what you've asked is not what you want, just a solution you've devised but don't know how to implement.](https://en.wikipedia.org/wiki/XY_problem) Why do you want to remove goodhosts and use an IP? Is this because goodhosts reformats the hosts file? ( and if so, why did you ask how to remove goodhosts rather than how to stop it reformatting? That's something we can actually help with!! )

**Comment by cueqzapper** [comment]
Question rephrased: Goodhosts gets blocked by security software which I don't have permission to whitelist. The file that gets blocked is cli.exe. And it does that everytime i run vagrant up. The hosts file is already correctly edited so it doesn't need to do that every time.

**Comment by tomjn** [comment]
hmmm another solution would be to not attempt to edit the hosts file if it already has the desired hosts. I've created an issue at https://github.com/goodhosts/vagrant/issues/22

**Comment by cueqzapper** [comment]
I have admin rights, but we have very strict security rules. Program which blocks is called Airlock.

**Comment by tomjn** [comment]
Is it possible that even reading the hosts file may not be enough then? @Mte90 what about a DNS look up with an ultra low timeout?

**Comment by Mte90** [comment]
I think that Airlock is like an antivirus and monitor some critical file so any change is blocked.

I don't know if also the reading is blocked outside Airlock. I cannot find anything online but I don't know if we can fix on our side.

**Comment by cueqzapper** [comment]
Add the possibilty to add a parameter to neither check or update the hosts file, when user already knows that hosts file has been correctly edited. Probably not a good idea to add this option just for one user (me) but would obviously be awesome ;-)

**Comment by tomjn** [comment]
I'm closing this for now as modifying the hosts file is pretty fundamental to how VVV works, as is using host names instead of direct IPs. The appropriate fix here is to whitelist goodhosts binary making changes to the hosts file, or allowing some sort of approval of the change. Both of these are Airlock issues not VVV issues.

Future methods of avoiding hosts file modifications could be possible, but they would not involve direct IP access, as the hostname is necessary to identify which site to serve. Zeroconf/bonjour could be used, or the user could setup local DNS rules. Neither of these are on our roadmap at the moment so it would need to be an outside contribution
