### ISSUE TITLE
'vagrant up' hanging at 'SSH auth method: private key'

### ISSUE THREAD

**Issue by CalvinNelson-occmgmt** [Varying-Vagrant-Vagrants/VVV#2414]
I have done a ton of trouble shooting on this issue, and am now trying here.

I am new to vagrant, so this is a fresh install on my computer for vagrant, and VMBox. I was able to first successfully install a scotchbox vm, but after doing some more research I found that this was the industry standard. So I destroyed that install and starting setting VVV up.

When I first ran vagrant up from `~/vagrant_local` it looked like it was working fine then the setup stopped at 'SSH auth method: private key'.

After some research I saw that I might need the vagrant default insecure key so I added `~/.ssh/authorized_keys/vagrant & vagrant.pub` file, with the contents copied from [here](https://github.com/hashicorp/vagrant/tree/main/keys).

That did not resolve my issue. I have reprovisioned, and also tried updating the box but nothing.

Any help would be greatly appriciated.

**Comment by tomjn** [comment]
You shouldn't need to download and install the insecure key. There's a large chunk of information that was requested in the issue template that's missing though. Judging from `~/vagrant-local` you are not a Windows user, or you're using this inside WSL. I'm not sure.

Can you provide more information? The full output of the command that failed would be useful

**Comment by Josef37** [comment]
I have the exact same issue (I just started to figure it out 😃). Some steps worth taking:

1. Launch the VM's **interface in VirtualBox** and have a look in which state it is. Is it still booting or just waiting? If it is booting, you might have to increase the timeout (like stated in the console).
2. Look at the [Troubleshooting page](https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/) and try `vagrant halt` then `vagrant up --provision` or **`vagrant up --provision --debug > vagrant.log`**. Mysteriously, the latter (with the debug flag) worked every time... This might hint you at what is going wrong.
3. If you're getting ["Virtualbox Interface has active connections" on Windows shutdown](https://stackoverflow.com/questions/56562630/how-to-fix-virtualbox-interface-has-active-connections-error-in-windows) but you shut your VM down with `vagrant halt`, there might be something else blocking. In my case **Docker Desktop** somehow got resurrected into autostart after updating my Windows 10 version. Uninstall it or stop the service.
4. Maybe try [increasing **`memory`**](https://github.com/hashicorp/vagrant/issues/7965#issuecomment-452650092) in `config/config.yml`.
5. Maybe [kill your **ssh-agent** process](https://github.com/hashicorp/vagrant/issues/6985#issuecomment-180396307) or [disable it for the current session](https://tomjn.com/2016/08/03/vagrant-provision-timeouts/) with `export SSH_AUTH_SOCK=""`.
6. Sometimes, [**updating** Vagrant and Virtualbox does help](https://stackoverflow.com/questions/38900334/vagrant-disable-ssh-agent). 
7. This might be unrelated, but make sure to `vagrant plugin install vagrant-goodhosts`. I just had the old plugin installed (I guess "vagrant-hostsupdater").
8. [**Starting from Fresh**](https://varyingvagrantvagrants.org/docs/en-US/troubleshooting/) might be worth trying out.

I hope this saves you some time debugging your VVV setup. It took me some evenings 😄 But I'm so grateful something like VVV even exists, because I just can't do DevOps... Keep up the awesome work! ❤️

**Comment by evertiro** [comment]
Has this been resolved?

**Comment by tomjn** [comment]
closing this due to lack of response, VVV has had a lot of changes since this, as has vagrant and virtualbox
