### ISSUE TITLE
Need help to run VVV hosts onto different devices from same network

### ISSUE THREAD

**Issue by premsurana** [Varying-Vagrant-Vagrants/VVV#2456]
Hi, so I need help in getting WordPress instances of VVV on different devices which are on same network for testing purpose

I was able to get into dashboard page `vvv.test` through IP by uncommenting `config.vm.network :public_network` in `vagrantFile`, but it gave a warning to install vagrant plugin hosts updater which I did later on, and I'm still unable to get into any site from other devices

I didn't find any previous issue which would help me resolve this but couldn't find one, so I hope I'm not bothering any of you with such a newb question!

**Comment by tomjn** [comment]
@premsurana there are some important things to remember when doing this:

1. VVV is optimised for local development, not production, exposing VVV to the internet is a big ssecurity risk. Afterall you want predictable easy logins for local dev, but they're disastrous for security. Danger!!!!! ⚠️ 
2. If you visit the dashboard at any URL other than `vvv.test` it will warn you about hostsupdater, even if you have it installed. You are not supposed to visit the IP directly
3. To visit a site you **must** have that sites host name in the computers hosts file pointed to the right IP. This is impossible on iOS and requires extreme effort on newer Android versions. You will likely need a custom DNS server on your local network
4. We could add a flag to `config.yml` so that you don't have to modify the vagrant file, but we will not. It's a **dangerous** thing to do. Use a staging server instead. VVV is not a staging server.

If you're finding this difficult, that is good, _right now we want this to be a difficult thing to do_.

In the past some people have spun up VVV to host their website and done what you are trying to do now to enable this. The sad part is anybody can plug their sites domain into an SQL client, use the username/password in the docs and hack their website. Likewise, anybody could SFTP into your VVV and make commits to your client sites and other nefarious things.

This isn't a problem because VVV only accepts connections from you, but if you open it up, anybody who can access your network can do it too.

**Comment by premsurana** [comment]
I understand the risks, ill find a way around in order to test on other devices thank you for the reply!
