### ISSUE TITLE
WebP support is missing

### ISSUE THREAD

**Issue by desrosj** [Varying-Vagrant-Vagrants/VVV#2457]
**Is your feature request related to a problem? Please describe.**

WebP support was recently merged into WordPress Core in https://core.trac.wordpress.org/changeset/50810. But it appears that VVV does not support the format.

**Describe the solution you'd like**

If the ImageMagick library is compiled with the WebP codec present, it should automatically support the format.

See [Trac-35725](https://core.trac.wordpress.org/ticket/35725).

**Comment by Mte90** [comment]
We need to check if the ondrej ubuntu ppa support it.

**Comment by tomjn** [comment]
> If the ImageMagick library is compiled with the WebP codec present, it should automatically support the format.

We don't build PHP packages, we just install whatever we get from the Ondrej PPA. You'll want to get those packages changed as they're widespread. Once you've done so you'll find a lot of Ubuntu/Debian servers, as well as VVV and Chassis amongst others, will work with webp.

https://launchpad.net/~ondrej/+archive/ubuntu/php

Otherwise, rebuilding PHP dependencies is beyond the scope of the project. 

There is a ticket for Ondrej PPA Imagick webp support at:

https://github.com/oerdnj/deb.sury.org/issues/1071

Which points towards:

https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1117481

and 

https://askubuntu.com/questions/251950/imagemagick-convert-cant-convert-to-webp

Which suggests that installing the  `webp` apt package will fix things, but I have no information on this.

**Comment by tomjn** [comment]
If we can get some testing of https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2458 that should verify if this is the case
