### ISSUE TITLE
Q: Binding a VVV site to a real domain

### ISSUE THREAD

**Issue by jobatabs** [Varying-Vagrant-Vagrants/VVV#2489]
Hi!

I searched through the docs a couple of times, but didn't find help there. (Though it's always possible I missed some now-obvious keyword.) I also tried editing the config on my own, but this failed me too.

My situation is this:

I'm working on a WP theme for a client. I would like to show the work to the client remotely, without uploading the theme to their live site yet.

I control a real, internet-accessible domain, let's say `mytestsite.mydomain.com`, which points to my router's public IP with an A record. My LAN is NATted, but I can port forward connections from my router to my computer.

I am on a default, blank slate VVV installation that works perfectly well for access on localhost, through `one.wordpress.test`. What steps would I need to take to make `wordpress-one` accessible from the public internet?

Any insights appreciated!

Immediate edit to satisfy the bot:
macOS 10.14 Mojave
Vagrant 2.2.16
VirtualBox 6.1.22
VVV is the latest from `git pull`

**Comment by tomjn** [comment]
VVV deliberately disables public networking, **it is not a staging server**, and is no substitute for a staging server. Ideally we can make this harder to do, not easier.

VVV is optimised as a local development server, not secure internet exposed server. By doing this you expose your machine to the open web, with `root` access available. The access details are documented on the VVV website and are very weak ( by design ).

Any use of VVV as an internet connected staging server should be considered a major security breach by you and your client, with all the legal ramifications that entails.

> What steps would I need to take to make wordpress-one accessible from the public internet?

It would be unethical and wildly irresponsible of me to tell you how to do this.

You have 3 alternatives:

 - set up a tunnel through which the site can be exposed using tools such as ngrok
 - use a staging server as your staging server
 - demonstrate the changes to the client be that in person or remotely via screenshare.

**Comment by jobatabs** [comment]
Well, thank you for your quick and thorough answer.

I wasn't planning on exposing any other ports than 80, for exactly the reasons you describe, but apparently this is not supported. I have no idea what a staging server is, but I will look into that, then.

Thank you anyway.

**Comment by tomjn** [comment]
>  I have no idea what a staging server is, but I will look into that, then.

It's just a host that's used for a non-production site, the same kind you would use for production, though you may choose to allocate it fewer resources
