### ISSUE TITLE
Q: Is there a clean solution for vagrant-goodhosts requiring a password?

### ISSUE THREAD

**Issue by rtpHarry** [Varying-Vagrant-Vagrants/VVV#2512]
I'm on MacOS Big Sur. I'm not an expert in the intricacies of this operating system, I spent most of my life on Windows.

I have vagrant-goodhosts installed to manage the HOSTS file.

Each time it boots up it wants me to type in my master password so it can write to the file.

Is there anything that can be done to avoid this requirement?

I'm a bit dumb so I keep forgetting its going to ask me. I'll set it reprovisioning, then come back later ready to use it and realise it got stuck almost instantly.

I'm thinking that maybe the option is to reduce the permissions required to write to the HOSTS file, which to be honest I am open to. I appreciate if I got some bad software it could maybe hijack it easier.

**Comment by tomjn** [comment]
Options:

1. Wait 20 seconds as it's one of the very first things that happens, before provisioning etc
2. Contribute to `vagrant-goodhosts` to make it check i the hosts are already in the hosts file so it doesn't need to ask
3. There's a PAM module to use touch ID instead of typing it
4. There's a command to whitelist in the readme of the plugin, don't ask me how it works or how to set it up though as I don't use it personally ( I type the password instead of touch ID )
5. You can make the hosts file world writable ( very insecure )
6. You can change site provisioners so they don't do crazy/silly things like importing gigantic databases. Maybe only do this when creating the site for the very first time? Or as a separate step? Provisioning sets up the site, nobody said it had to do all the other tasks too, or that they always have to run. Provisioning should take less than 5 minutes, usually ~2 minutes maybe less. If a single site takes longer than this then either you're doing too much or you've installed the WP Meta environment

**Comment by rtpHarry** [comment]
Thank you for your amazing support, as always.
