### ISSUE TITLE
Bug: Updating the macOs Monterey not working

### ISSUE THREAD

**Issue by chetansatasiya** [Varying-Vagrant-Vagrants/VVV#2548]
## Current Behavior
Getting below error
<img width="1005" alt="Screenshot 2021-10-27 at 1 16 57 PM" src="https://user-images.githubusercontent.com/7081284/139022619-7d51cf3f-1f35-4cc4-bbc5-3e71c690ee80.png">

## Steps to Reproduce (for bugs)

1. Updated the MacOS to Monterey
2. Vagrant up
3. Getting error

**Comment by rtpHarry** [comment]
I hit this issue as well after foolishly letting the update run. It seems it will be fixed in the next maintenance release, but there is a special build available now which fixed it for me:

https://www.virtualbox.org/ticket/20636

https://www.virtualbox.org/download/testcase/VirtualBox-6.1.29r148140.dmg
