### ISSUE TITLE
Q: Multisite:  Domain?  Directory?

### ISSUE THREAD

**Issue by mcyzyk** [Varying-Vagrant-Vagrants/VVV#2743]
I have just installed a full Multisite into VVV.

Our Sites in this Multisite are like so:

```
multisiteURL
site1.multisiteURL
site2.multisiteURL
site3.multisiteURL
```

I have set my config to:

`wp_type: subdomain`

But my Sites end up with their original URLs:

```
site1.livesiteURL
site2.livesiteURL
site3.livesiteURL
```

I also tried with:

`wp_type: subdirectory`

No Joy.

In VVV, how to deal with a Multisite whose individual Sites are set up so?

```
multisiteURL
site1.multisiteURL
site2.multisiteURL
site3.multisiteURL
```

Thanks!

Mark

**Comment by tomjn** [comment]
if you are on multisite.test and add a new site and instead of `new.multisite.test` you get `new.productionsite.com` then that suggests that you didn't search replace everything everywhere, e.g. `wp-config.php` or the multisite network tables etc.

Keep in mind though that those options are for the initial setup, if you create a singular site and then change `wp_type` after the fact it will have no effect. VVV won't try to _modify_ a site that has already been provisioned

**Comment by mcyzyk** [comment]
Thanks!

When I import I need to Search and Replace for each one of my 20+ Site URLs?

**Comment by tomjn** [comment]
you need to search replace all tables for every URL/domain that you have to change them to what you've told VVV. This would be true no matter what you used for local, or if you hosted it on a private/office server.

Remember, WordPress can have a multisite were each site/blog has a completely different TLD, so it will see no issues if you use the domains you put in VVV's config and search replaced, but have a production URL somewhere else, you can't really pick and choose which bits you localise.

**Comment by mcyzyk** [comment]
Thanks Tom!

Just what I needed to know.

Mark
