### ISSUE TITLE
Having issues getting VVV running on Ubuntu

### ISSUE THREAD

**Issue by topdown** [Varying-Vagrant-Vagrants/VVV#391]
VVV runs beautifully on my Mac
Tried the same setup on Ubuntu 12.04 no luck
Tried 32 & 64 VirtualBox and Vagrant

Updated my workstation to Ubuntu 14.04 and tried again, same issues.

```
 default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
Timed out while waiting for the machine to boot.
```

When I try vagrant up again it runs the end of vagrant up showing the host list.
But none of them work.

Try vagrant halt

```
[~/vvv] ➔ vagrant halt
==> default: Running triggers before halt...
==> default: Executing command "vagrant ssh -c 'vagrant_halt'"...
The command "vagrant ssh -c 'vagrant_halt'" returned a failed exit code. The
error output is shown below:

ssh_exchange_identification: read: Connection reset by peer
```

SSH Debug using the address above

```
[~/vvv] ➔ ssh vagrant@127.0.0.1:2222 -v
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
ssh: Could not resolve hostname 127.0.0.1:2222: Name or service not known
```

It seems to always be related to SSH.
I can't spend anymore solo time trying to figure this out on Ubuntu.
Any ideas why this is being so stubborn?

**Comment by ljgww** [comment]
After a lot of experimentation and observation I came to conclusion that this is not SSH issue rather it is network configuration issue on a box and the way how vagrant treat it.

Vagrant is trying to be smart by injecting network adapter configuration during up script execution while not really giving an option to a user to configure vbox network in some alternative (maybe more appropriate configuration). To much 'intelligence' and treating user to be 'stupid' is not always good idea ;)

I have a pc that has no virtualization setup, this does not stop vagrant from working but once in many reloads (say in 1 of 10 attempts everything gets properly setup and ssh works without problems). Of course this happens after many retries (timeouts on box OS).

In essence box ETH0 almost never gets properly configured during box booting. I have increased timeouts beyond realistic limits to counter numerous attempts of the box to get its network properly configured. Box's eth0 looks like failing on DHCP finally ending up with IPv6 address instead of IPv4 address. Of course from vagrant script side it looks that vbox is not yet connected (there are no routes) so vagrant script tries to try and retries to try until **eventually** after some additional time-outs eth0 on the box gets configured properly (god knows which DHCP is hit to help)

I have experimented by forcing vbox to use various eth0 setups (including forcing to be static one within the same network as host) but that gets nullified by vagrant script injection configuration that insists on NAT setup and UUID network identifier (which seems to be luckily generated once one vagrant setup is made) and undoing any alternative network configuration.

I run Ubuntu 14.04 32 vbox on 14.04 64bit host (with no virtualization). Its working SOMETIMES (when I get lucky)

Not to mention that I run currently latest version of Oracle VBox and latest version of Vagrant, just for someone who would surely wander is that is up to date ... there are no firewalls or other fancy disruptors in between.
