### ISSUE TITLE
wp-cli not installing 

### ISSUE THREAD

**Issue by rtvenge** [Varying-Vagrant-Vagrants/VVV#410]
When I run `vagrant up` for the first time on a new vvv project, it seems to be skipping wp-cli. When I run `vagrant up` I see:

```
==> default: Downloading wp-cli, see http://wp-cli.org
==> default: Cloning into '/srv/www/wp-cli'...
==> default: warning: expected SRV RR, found RR type 1
```

And when I ssh into the machine for the first time, I see:

```
-bash: /srv/www/wp-cli/utils/wp-completion.bash: No such file or directory
```

I know wp-cli changed their install process recently, now using a `wp-cli.phar` file. Maybe this has something to do with it? Is anyone else seeing this issue?

Let me know if you need anymore information from me.

**Comment by kouik** [comment]
Same problem here on Windows.
I just have one `git pull` command that generate this message. My script is provisioning from some many repositories, and it appears that for the one which produces this error message, i used the `git` protocol instead of the `ssh` one in the repo url (url set by WP-Skeleton framework).

Changing repo/sub-module url from `git://github.com/WordPress/WordPress.git` to `git@github.com:WordPress/WordPress.git` fixed my problem.

Also note that prior to the first ssh connection to the remote host (in this case, github), i've added the following line inside my `vvv-init.sh` provisionning script to prevent a key validation failure because github could be not yet added to known hosts.
```sh
ssh -o StrictHostKeyChecking=no git@github.com uptime
```
I used the uptime command to do something, but you could use what you wan't, like an echo.

After the second provisioning, i received an interesting output that said :
```
You appear to be using ssh to clone a git:// URL
Make sur your core.gitProxy config option and the
GIT_PROXY_COMMAND environnment variable are not set.
```
When i saw this message, i had already changed the repo URL, and everything were working fine, but this could help someone that need to use the git protocol.

Dunno if we had the same problem there, but googling for the error message above dropped me there.

Hope that helps someone.

**Comment by cfoellmann** [comment]
Is this solved since we checkout via `https:` and not over `git:` anymore?

**Comment by jeffslofish** [comment]
I ran the VVV install procedure, and then edited /src/www/wp-cli/.git/config in the VM to use both https: and git: protocols (trying one at a time with a `git pull`) and they both worked fine.  I am on OSX 10.11.6 at commit 1f99518 in VVV. So, this issue may have been fixed, but it doesn't appear to be by changing from the git: to https: protocol.

**Comment by jeremyfelt** [comment]
Now that we're downloading and managing updates through the Phar file (See #1057), I think we can treat this as closed as it was related to the management of the package via git.
