### ISSUE TITLE
Move to Git?

### ISSUE THREAD

**Issue by aaroncampbell** [Varying-Vagrant-Vagrants/VVV#482]
I don't want to start a holy war, but after having moved most of my workflow to git, when I try to do core dev on VVV it's painful to be stuck in SVN. What is the consensus (or lack thereof) for moving to using git for wordpress-develop (and maybe wordpress-trunk)?

**Comment by aaroncampbell** [comment]
> If the goal of this is simply to make diffing and patching easier on folks unable or unwilling to learn svn, then just say that. 
"The goal of this is simply to make diffing and patching easier on folks." At least in my opinion that's the case. I think that VVV is supposed to make developing with and on WordPress as easy as possible, and I think git helps do that by letting people use modern tools they are familiar with and like.

**Comment by ericandrewlewis** [comment]
Drew said:
> My feeling is that as long as core continues to be versioned with svn, VVV -- considered to be the officially recommended vagrant package for core development -- should follow that lead. 

Whether or not there's any official recommendation by the WordPress core team, the VVV community should define and serve its userbase independently. I think the 80/20 rule should apply here. 

The fact that WordPress core primarily uses svn doesn't apply to this discussion. The project's reasons for staying on svn, as I understand, are a matter of priority and backwards compatibility. That's a separate issue from the goal of VVV: providing the greater contributor-base with a VM to use for WordPress core development (among other things).

I think we can all agree svn is the past and git is the future. I'm personally unwilling to learn any more about svn than I already do, unless out of necessity, because it is an archaic technology. We should push contributors to use modern, familiar, and better tools.

**Comment by jeremyfelt** [comment]
I totally agree that git would be the more pleasant default. Speed continues to be my primary concern with switching before having a configurable VVV. There's just no easy way for a user to decide which sites should be created in advance. Ideally, I could tell provisioning to skip everything except for the develop repo, and then check it out with git rather than svn.

With my unshaped 34Mbps down connection at home:
* 34 seconds for `git clone git://develop.git.wordpress.org/`
* 14 seconds for `svn checkout https://develop.svn.wordpress.org/trunk`

If I limit that connection to 5Mbps:
* 5 minutes, 23 seconds for `git clone git://develop.git.wordpress.org/`
* 49 seconds for `svn checkout https://develop.svn.wordpress.org/trunk`

I haven't gone through the full provisioning of a new VVV instance at 5mbps (though that should happen to identify pain points), but adding 5 minutes is tough. Providing the `develop_git` script is a nice intermediary step to switch when a dev is ready to make that decision. I think #319 will open some doors for us on this.

It'd be really nice if we could get details on average connection speed somehow, or even find a way to detect slow bandwidth in advance.

**Comment by christophercochran** [comment]
If those are the speed differences, I would keep SVN over Git as default just for usability/sanity sake. With traveling a lot the wifi speeds on hotels, cafes, buses, and planes isn't always the best and I'm lucky if I am seeing 5Mbs. Yes at my home speeds are not an issue, and most likely for most won't be. But for those who aren't lucky at home to have access to High Speed internet, and those traveling a lot, I could see speed being an important factor.

I also know there are a lot of Git lovers, but there also a lot SVN lovers as well. With the tool in place to convert to git repo if need, I think speed would out weigh in this case as to what the default option should be. Just my opinion.

**Comment by johnjamesjacoby** [comment]
Hi. Having core commit access definitely makes using Subversion a better experience, since you're getting the environment you're working on. For the rest of everyone using VVV that isn't burdened with upholding the functionality of 25% of the internet, but is still interested in improving it, Git would be ideal IMO.

I'm willing to admit that I'm bias and maybe spoiled by average (50Mbps wee!) speeds most of the places  I spend most of my time, but let's consider also that these speeds really only matter for the initial clone, not subsequent pulls. Yes, the initial clone will take some time, and is big enough where maybe you don't want to tether to your cellular and `vagrant destroy` fifteen times, but I doubt that's the 80% use-case here either.

The folks at [Atlassian blogged](https://blogs.atlassian.com/2014/05/handle-big-repositories-git/) about shallow clones and other alternatives last year. Maybe there's some trickery we can employ to speed this up without pulling the entire history?

The script is really cool, and I also didn't know it existed until I went looking today, but at the same time this script feels backwards. VVV should be for contributors to contribute via Git, and when they graduate to having core commit access they can run a script to switch them to using Subversion.

Tangentially, theres's an issue that needs filing upstream with Netbeans as it seems to struggle with tracking changes in different nested revision history types. Specifically using the `develop` site, because the `.gitignore` in the root cascades up into ignoring plugins & themes, which even though are their own checkouts, are fully ignored; it isn't until everything is a Git checkout that Netbeans understands what to do.

(I know none of you care about Netbeans; just noting incase someone else runs into this here. 😎)

**Comment by jeremyfelt** [comment]
> The folks at Atlassian blogged about shallow clones and other alternatives last year. Maybe there's some trickery we can employ to speed this up without pulling the entire history?

I'd be up for playing with a pull request around this.

**Comment by ericandrewlewis** [comment]
Some benchmarks from on my 90Mbs connection, comparing an svn checkout to a shallow git checkout:

`git clone --depth 1 "git://develop.git.wordpress.org/" "/srv/www/wordpress-develop"` 18 seconds
`svn checkout "https://develop.svn.wordpress.org/trunk/" "/srv/www/wordpress-develop"` 31 seconds

**Comment by aaroncampbell** [comment]
On a (much) slower connection (~2Mbps) that is far less stable, I had to run a bunch of tests to get a good idea of the time savings. The times ranged from 30 seconds to well over a minute, but on average the `git clone --depth 1` was about 10-15 seconds faster than the `svn checkout`

**Comment by aaroncampbell** [comment]
That changes the default to git (using `--depth 1`), changes the `develop_git` script to a `develop_svn` script (doing exactly what you'd expect), and updates the README to reflect the changes.

**Comment by jeremyfelt** [comment]
Bump. As part of the shift to the new provisioning configuration, we should make `git` the default in the [vvv-wordpress-develop](https://github.com/Varying-Vagrant-Vagrants/vvv-wordpress-develop) repository.

**Comment by Mte90** [comment]
We can close this one because right now we are using git everywhere.
The https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop/blob/master/provision/vvv-init.sh provisioner include a check for svn and in case still use that or will use git to download.
The standard provisioner use git.
