### ISSUE TITLE
Xip.io Usage

### ISSUE THREAD

**Issue by CNSam** [Varying-Vagrant-Vagrants/VVV#483]
Hi all,

Just wondering if the xip.io functionality should work 'out of the box' as im just getting 'The webpage is not available' when visiting: http://local.wordpress.192.168.8.115.xip.io/

Regards

**Comment by cfoellmann** [comment]
_xip.io usage_ is a good candidate for a wiki article.
Otherwise we could close this, right?

**Comment by MickeyKay** [comment]
Hey all,

Would love to see a proper wiki on this. I've been attempting to piece this together from all the various tutorials out there, and have still not had success. No matter what I do, I end up with an unstyled version of the site with broken links when viewing via the xip.io address on my phone (for testing).

If I install the Root Relative URL's plugin, this fixes some things including the broken stylesheet reference and the links, however it also breaks other plugin functionality. I'm also confused because some tutorials state that this plugin or something similar is required, however others make no mention of this issue, suggesting that things should just work out of the box.

Any suggestions? Will open a new issue to get this convo going as well...

**Comment by salcode** [comment]
@MickeyKay I agree with @ezekg's suggestion in #723 to use [Dynamic Hostname](https://wordpress.org/plugins/dynamic-hostname/), this is the same plugin I use.

**Comment by MickeyKay** [comment]
Gotcha, will try, thanks. One question - it seems that this plugin is
mentioned in some tutorials but not others. Same goes for the Root Relative
URL's plugin. It seems odd to me that this isn't a mandatory part of every
xip.io setup alongside VVV - is there some configuration in which this
wouldn't be required?

Lastly, I definitely think this warrants a section in the wiki.

**Comment by salcode** [comment]
@MickeyKay I prefer using the [Dynamic Hostname Plugin](https://wordpress.org/plugins/dynamic-hostname/) but there are a couple of other options:

## Alternatives to Dynamic Hostname Plugin

### Define in wp-config.php
You would have to update this whenever your IP address changes.
```
define('WP_SITEURL', 'http://local.wordpress.10.0.1.11.xip.io');
define('WP_HOME', 'http://local.wordpress.10.0.1.11.xip.io');
```

### Dynamic in wp-config.php
Doug Stewart shares code here that can be placed in wp-config.php to get this behavior
http://zachwills.net/setting-up-ngrok-and-vvv-to-share-your-local-wordpress-environment-with-the-world/#div-comment-71

### Update Your Database Manually
You can edit the database directly and change the values for
__siteurl__ and __home__ directly in the options table (_wp_options_). This would have to be updated whenever your IP address changes.

## Wiki Update
If you want to take a first pass at a wiki page based on your recent experiences, I'm sure others would appreciate the guidance.

**Comment by MickeyKay** [comment]
Thanks for the update. One observation though, upon installing the Dynamic Hostname Plugin, I received the following admin notice:
![image](https://cloud.githubusercontent.com/assets/3189678/9313384/8939774a-44d7-11e5-804f-4ab749d5931e.png)

So it looks like I have to manually config `WP_HOME` in wp-config.php anyways, unless I'm missing something there? Any ideas?

Also, in [this post](https://make.wordpress.org/core/2015/03/16/mobile-patch-testing-with-vvv-and-xip-io/), Ryan Boren writes that:

>I’m using Vagrant’s public_network option along with xip.io. This allows me to test from any device on my local network using links like http://build.wordpress-develop.192.168.1.11.xip.io/ without the need for port forwarding, dynamic dns, or hosts file editing.

So it sounds like there is some solution that works out of the box and doesn't require port forwarding, dynamic dns changes, or editing the hosts file.

Does anyone have insights on how to achieve this out of the box? From everything I've read on both VVV and the Variable VVV site creator, it sounds like all this is supposed to just work right out of the box. Is there something I'm missing?

**Comment by salcode** [comment]
Dynamic Hostname Plugin Admin Notice
------------------------------------------------------
Yes, the Dynamic Hostname plugin asks you to define WP_HOME in wp-config.php.  If I understand correctly, this is to define the official version of the site url and then dynamic hostname works on top of that.

I have __never__ set those values in wp-config.php and other than the warning I've yet to suffer any consequences from this.

VVV out of the Box
--------------------------
You can use the public network option out of the box. You'll still need to solve the hostname issue with one of the options listed above (but by dealing with it directly in `wp-config.php` you could make the argument, it is out-of-the-box).

@jpry has a great writeup on how to use the public network option at http://webdevstudios.com/2015/08/04/how-to-view-a-locally-developed-website-devices/
and he finally helped me understand how to properly use the __public_network__ option in #566


forwarded_port vs public_network
---------------------------------------------

### public_network
- Does not require an additional utility (pfctl), which may not be available on all systems
- has the benefit of a shorter `Customfile`
```
# Set up with a Public network
config.vm.network :public_network
```

### forwarded_port
- Eliminates having to log into your Vagrant box to determine the correct IP address
- Does not require a `vagrant reload` when your IP address changes (I've heard from others this is necessary with public_network but I've not tested this claim)

If I were using a Windows machine, I'd use _public_network_ rather than figure out how to do the port forwarding but since I'm on a Mac and I've got my [Customfile](http://salferrarello.com/vagrant-vvv-setup-wordpress/) dialed-in, I prefer Port Forwarding.

**Comment by tomjn** [comment]
Marking this as closed, it's something that would have to be added to the `custom-site-template` repo

**Comment by tomjn** [comment]
But for reference, exposing VVV to the internet rather than just a private network is not a good idea security wise

**Comment by dingo-d** [comment]
Yeah, people should use [Browsersync](https://browsersync.io/) for testing the site on other devices.

**Comment by JPry** [comment]
> exposing VVV to the internet rather than just a private network 

The Xip.io service is designed to only expose the site to the local network. The DNS lookup does traverse the internet, but it resolves on the local network.
