### ISSUE TITLE
Use innodb_file_per_table = 1 ?

### ISSUE THREAD

**Issue by jb510** [Varying-Vagrant-Vagrants/VVV#537]
Would it make sense to use Use innodb_file_per_table = 1 to split the DBs into separate files, whereby deleting a database might reclaim disk space or did moe the DBs out of the sync'd folder make that pointless?  

This was a tweak Eric Mann had proposed herw https://eamann.com/tech/varying-vagrants-evolved/ some time ago, but which I really liked.

**Comment by jeremyfelt** [comment]
I'd definitely be open to discussing this. This looks like a good comparison of the pros/cons - http://dev.mysql.com/doc/refman/5.6/en/innodb-multiple-tablespaces.html

**Comment by jb510** [comment]
Well it's well beyond my level of expertise, so I'll defer to @ericmann and others, just wanted to raise it for discussion as it "looked good to me".

**Comment by ericmann** [comment]
First and foremost, this makes a huge difference if you ever import a DB into VVV only temporarily. If you do so, and MySQL is using a single file, the file will expand to fit automatically. When the DB is later dropped, though, the file _will not decrease in size_, meaning you're continuing to lose space on the disk.

So whether you're archiving/purging old projects or just deleting large DBs used to perform data migrations (in some cases these can be 2GB+) you end up with lost disk space due to the single file.

The flag is quick, simple, and even with large DBs I've never seen an issue with performance on either Windows or Mac (using Hyper-V or VirtualBox). Then again, WordPress uses a very small number of tables, so the table-related performance issues in that linked document won't necessarily affect the large majority of users.

I'm all for making this change.

**Comment by TheLastCicada** [comment]
I support this change as well - we have this set on all stage servers we setup where databases are created and destroyed frequently and I also use this setting on many live sites.  I've never noticed any hit in performance - and if there is, I'd consider it very minor.  I agree with all of the points made by @ericmann.

**Comment by jeremyfelt** [comment]
Nice, I'm game. Is there any worry of something strange happening to existing databases when the config changes all of a sudden?

**Comment by jeremyfelt** [comment]
I switched back and forth between the settings and all databases continued to be fine. Seems if you want major space savings on existing DBs, you'll need to go through the process of recreating the databases. It should work fine on new DBs though. http://dba.stackexchange.com/questions/11043/mysql-changing-innodb-file-per-table-for-a-live-db

I'm going to merge #538, feel free to continue leaving info on making this switch if anything comes up.

**Comment by jb510** [comment]
Not a huge deal, but I think that belongs in the [mysqld] block where I put it.
http://dev.mysql.com/doc/refman/5.6/en/tablespace-enabling.html

**Comment by jeremyfelt** [comment]
Doh, I didn't catch that at all. I wonder if my testing mattered. :) Reopening!
