### ISSUE TITLE
Use nvm instead of nodejs

### ISSUE THREAD

**Issue by Fouppy** [Varying-Vagrant-Vagrants/VVV#562]
Out of the box, after a fresh provisioning, each time I need to use npm I have to add sudo before.

I finally removed nodejs package and installed nvm, it's like rvm for node (https://github.com/creationix/nvm)

Everything works without sudo now

Any reason not to switch in the provision script?

**Comment by cfoellmann** [comment]
NVM is a version switcher for nodejs like phpbrew ( #586 ) is for PHP, right?
Since we are not really aiming for support of nodejs development I do not see any pros here. Do you have any advantages other than the removal of sudo?

You can change to the root user by `sudo su`. That can be helpful in longer ssh sessions.

**Comment by aaronjorbin** [comment]
As node is required for the WordPress core build process and multiple
versions are supported, this may actually make a lot of sense

On Friday, February 26, 2016, Frédéric Honoré <notifications@github.com>
wrote:

> Closed #562 <https://github.com/Varying-Vagrant-Vagrants/VVV/issues/562>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Varying-Vagrant-Vagrants/VVV/issues/562#event-567828675>
> .
>


-- 
http://aaron.jorb.in
twitter: twitter.com/aaronjorbin

**Comment by jeremyfelt** [comment]
Indeed, let's reopen and discuss some more. Does #779 have any impact on this?

**Comment by ntwb** [comment]
One thing to be aware of, is with NVM it doesn't support multiple versions of NPM

So if you want to use the LTS (Long Term Support) v2.x branch of NPM you'll need to install it via `npm install -g npm@2` or likewise, if you want to use the "stable" 3.x branch then `npm install -g npm@3`

I suggest VVV should standardise on the LTS v2.x branch of NPM, if people want to switch to v3 thats straight forward per above.

**Comment by jeremyfelt** [comment]
Ok. I'm wrapping my head around the NodeJS, NVM, and NPM stuff. Let's use this ticket to plan out some steps and then get things merged. :)

### NVM

We'll use #863 to install and configure the latest version of NVM.

This could go in right now. My only question was whether it would be worth downloading a zipped package from the GitHub repository rather than cloning the repo and then watching tags. It's a small commit history, so the clone won't take long either way, so it may be fine as is.

### NPM

From @ntwb:
> I suggest VVV should standardise on the LTS v2.x branch of NPM, if people want to switch to v3 thats straight forward per above.

If I run `npm --version` inside my VVV instance right now, it's showing 3.8.6. Is that correct or should we force it back to LTS 2? What is the harm in NPM 3.x.x by default?

I'm not sure we have a place where this is specified, so we may need a pull request that locks things in place once we decide.

### NodeJS

We can use #779 to update the default system version of Node to the 4.x LTS release per [this comment](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/788#issuecomment-205791239), though I would not personally be opposed to running the latest stable. I guess it does make sense to use core defaults for some of this.

**Comment by ntwb** [comment]
> NVM - My only question was whether it would be worth downloading a zipped package from the GitHub repository rather than cloning the repo and then watching tags. It's a small commit history, so the clone won't take long either way, so it may be fine as is.

I thought about this then looked at the other packages included via `git clone` and thought it would make sense to also to be a git clone'd repo though I've no real strong opinion for either method though.

> NPM - If I run npm --version inside my VVV instance right now, it's showing 3.8.6. Is that correct or should we force it back to LTS 2? What is the harm in NPM 3.x.x by default?

Yes, that is correct. Currently the latest NPM is installed via `npm install -g npm` via [provision.sh#L234](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/master/provision/provision.sh#L234), no final decision has yet to be made on using NPM v2.x or 3.x for core, see [#35105](https://core.trac.wordpress.org/ticket/35105), though if it was decided to use the 2.x branch then tweaking that provision command to `npm install -g npm@2`. 

Not sure how we'd handle peoples personal choice of using NPM v2.x or 3.x, but this can be addressed later in another issue/pull request and shouldn't be a blocker to getting the NodeJS updates in.

> NodeJS - We can use #779 to update the default system version of Node to the 4.x LTS release per this comment, though I would not personally be opposed to running the latest stable.

I'm using NodeJS 5.x (and NPM 3.x) here locally, what I was aiming for with that comment and decision was to have the broadest compatibility with #core by default because who knows ¯\_(ツ)_/¯

Maybe the argument should go the other way, use the latest stables (NodeJS 5.x, PHP 7.0) and ultilise NVM to switch back to 4.x if needed, and PHPBrew back to 5.x ¯\_(ツ)_/¯

**Comment by jeremyfelt** [comment]
#863 is merged, #779 is still open.

**Comment by jeremyfelt** [comment]
I'm finally back on this. :)

Current status:
```

**Comment by jeremyfelt** [comment]
Ok, we now have nvm via #863 and NodeJS 4.2.x via #779.

On a fresh `vagrant up`:

```
vagrant@vvv:~$ node --version
v4.5.0
vagrant@vvv:~$ npm --version
3.10.6
vagrant@vvv:~$ nvm --version
0.31.4
```

**Comment by ntwb** [comment]
@jeremyfelt Watch out for NVM aliases, aka `nvm install stable`, the `stable` [alias is deprecated](https://github.com/creationix/nvm#usage), in particular I'd avoid using that in any scripts to prevent unforeseen explosions 💥 

And thanks everyone for getting this done 🎉
