### ISSUE TITLE
Getting SSL Self Signed Certificate Working on Windows

### ISSUE THREAD

**Issue by DevinWalker** [Varying-Vagrant-Vagrants/VVV#567]
Hey there,

I'd love to be able to develop over HTTPS on my local development sites. I followed the wiki article found here: https://github.com/Varying-Vagrant-Vagrants/VVV/wiki/Site-specific-self-signed-SSL-certificates and it makes sense for the most part but the issue is it drops off for Windows users. I can access HTTPS sites but the lock is red and crossed out. I tried a ton of various stackoverflow recommendations about adding the certificate to windows and Chrome. Nothing I try seems to get the darn lock green. Any suggestions? Right now here's what it looks like: 
![https](https://cloud.githubusercontent.com/assets/1571635/6071745/33d846b2-ad4e-11e4-8516-6acdbbad9d61.png)

**Comment by cfoellmann** [comment]
You need to extract the CA cert from your vagrant.
Since I have no idea about how it it with ubuntu I can not point you to the right location. Maybe someone else can help

**Comment by cfoellmann** [comment]
Did you solve this?
Why do you need this? Self-signed certs __should__ present this way.

**Comment by DevinWalker** [comment]
This way? Which way? Green or red? 

No I didn't solve it.

**Comment by cfoellmann** [comment]
self-signed certs are red because there is no authority confirming its validity.
I just had another look. The standard cert installed by nginx isn't even signed the common way by a CA cert. Since I am no SSL expert my only advice would be to create a CA cert and with that a self-signed cert for the domain you need. then you can import the public part of the CA cert into the windows certificate store.

It is not the easiest task.
Again, why do you need to get a "green" indicator for the cert? There is no downside of a red indicator if you run you vagrant locally.

**Comment by DevinWalker** [comment]
Basically it would be a convenient way to test for non-secure content getting through, but not critical at all. I'd say you could close this issue out.

**Comment by cfoellmann** [comment]
you can use the web console of your browser to see if elements are loaded via http or https

**Comment by jeremyfelt** [comment]
Sorry to come in super late. :)

While I agree with @cfoellmann that there's no downside to the red, part of me really wants to know why. If you're still fighting this and don't mind doing some debugging, can you [use OpenSSL](https://jeremyfelt.com/2015/05/28/openssl-commands-that-came-in-useful-today/) to debug the cert/key and find out what info is in it. It's entirely possible that the domain mismatch is really what the error is.

**Comment by BrettLefty** [comment]
I may be wrong, but it seems to me like people are saying you can't get a self signed certificate to show up with the green lock thing. I was able to do so. You have to generate a crt file and install it, and it shows you a warning about an untrusted entity claiming to represent your domain. Once you install it though, it works and shows up with the green lock, not a red lock because it's self-signed.

This tutorial is what I followed: https://devcenter.heroku.com/articles/ssl-certificate-self
