### ISSUE TITLE
Using base box instead of provisioning each time for performance.

### ISSUE THREAD

**Issue by EHLOVader** [Varying-Vagrant-Vagrants/VVV#594]
Since the provisioning can take a long time, would it be of any benefit to create a base box for vagrant to provide quick stable vagrant ups in the future? 

I couldn't find any information on this, has it been discussed before?

EDIT: to clarify... Not talking about any of the sites or WordPress installs. But tools, services and configurations in an image instead of scripted. Many Dev environments seem to be doing that instead like homestead for Laravel.

**Comment by EHLOVader** [comment]
As I sit here and wait while my VM reprovisions everything just so the services and one site can be started I still wonder, generally speaking would a base box be much simpler? limiting provisioning to only site configuration and service restarts?

**Comment by jeremyfelt** [comment]
We tried this briefly once before via #6, but I think that mostly because it was easier to give a talk on Vagrant and pass around a pre-packaged box. We moved back to the standard box in 107c7425cc54046bbe6.

I think provisioning is a necessary evil and that an empty base box is a good thing. Ideally, things get converted to look for latest packages at some point and `vagrant provision` is run on a fairly frequent basis. The only time things are really slow are that initial `vagrant up`.

**Comment by EHLOVader** [comment]
Gotcha, I must have something wrong in my box from tinkering so much. When I start the box each day it doesn't always come up with services running. To get those running reliably I almost always have to run `vagrant provision` it has gotten stuck on NPM tasks and often takes a long time provisioning the handful of sites I have in my vvv instance. 

This takes a long time and seems similar to the initial `vagrant up`. I  wonder if I am missing something in the provision.sh file that would tip me off to a better reliable way but moving box provisioning out of the script came to mind as an area that could improve on this.

**Comment by jeremyfelt** [comment]
I've started to change my mind on this a bit. It would be interesting to find the right way to regularly package boxes so that provisioning wasn't as necessary. A version of this is already happening for WordPress contributor days.

**Comment by jeremyfelt** [comment]
Chatted with @LoreleiAurora about this yesterday a bit. I think we have several options available to us for hosting a pre-packaged box. I'd like to start working toward a future where every time a new version of VVV is shipped, we're also able to update the base box so that `git pull && vagrant box update` will kind of _Just Work_.

**Comment by tomjn** [comment]
I'm closing this in favour of #1469 as this is the plan for VVV 3
