### ISSUE TITLE
Rookie

### ISSUE THREAD

**Issue by Hanque** [Varying-Vagrant-Vagrants/VVV#602]
I am very new.
I have a PC running Ubuntu 14.04, Virtualbox, and Vagrant.
Now, after 30+ man-hours of cataloging my error-prone effort, I have had enough successes to continue.
My goal is to repair my client's Wordpress site.
Any help beyond the great stuff I have found already would be appreciated.
Best regards,
Hanque

**Comment by jeremyfelt** [comment]
Hi @Hanque, thanks for stopping by. Is there anything specific you have a question about?

**Comment by Hanque** [comment]
Actually, I am about to abandon the vvv unless I can learn more about the errors I am getting.  I can't edit the Vagrantfile because I get an error message about "mime" and "mailcap".I am guessing that my Ununtu 14.04 and Ubuntu 12.04 are too far apart to get along with Vantage. If it sounds like I am ignorant, it may be true. I have been using computers since 1975 so I know a little bit. Is there a comprehensive manual that may guide me into VVV with more detail?

Date: Sat, 11 Apr 2015 17:22:17 -0700

**Comment by jeremyfelt** [comment]
We don't have a comprehensive manual, though there are write-ups on several topics. "[The First Vagrant Up](https://github.com/Varying-Vagrant-Vagrants/VVV#the-first-vagrant-up)" covers the initial process of getting the default WordPress environments up and running. Also see this repository's [wiki](https://github.com/Varying-Vagrant-Vagrants/VVV/wiki) for additional information.

If you can provide the exact error or a screenshot, we may be able to narrow down where the issue is.

**Comment by Hanque** [comment]
I really appreciate the feedback but I think Vagrant might work just fine if barriers in Ubuntu could be surmounted.
I will "google" for Ubuntu permission line commands. 
I was hoping to stay away from terminal typing but I am willing to put up with it, a little.
Tell me, if I ever get Vagrant running, does it run without a lot of tinkering?

Date: Sun, 12 Apr 2015 10:56:25 -0700

**Comment by cfoellmann** [comment]
Normally Vagrant runs well on machines not running Windows.
Your best approach might be starting fresh. Removing everything VVV and go through https://github.com/Varying-Vagrant-Vagrants/VVV#the-first-vagrant-up

If you still have problems or want to be on the safe side: Reinstall Virtualbox and Vagrant,too.
