### ISSUE TITLE
Wordpress all of sudden not installed?

### ISSUE THREAD

**Issue by gitdistill** [Varying-Vagrant-Vagrants/VVV#640]
I'm not sure what I did but for some reason after a recent vagrant up and navigating to the usual http://local.wordpress.dev I get the intro to the 5minute wordpress instead of being able to login to wordpress.

I tried a vagrant provision and got:

==> default: Updating WordPress Stable...
==> default: Error: The site you have requested is not installed.
==> default: Run `wp core install`.

I see that when I vagrant ssh, I can navigate to the wordpress default install (with my files intact) located at:

/vagrant/www/wordpress-default/wp-content/

so maybe this is a host issue? in that local.wordpress.dev is not pointing to the right directory?

**Comment by gitdistill** [comment]
Let me put it another way. How do I not lose everything (wordpress settings, post content, installed plugins, etc.) if and when I have to create a new vagrant instance?

**Comment by gitdistill** [comment]
I suppose the triggers

**Comment by byronjohnson** [comment]
Did you find a way to fix this? I'm having this occur for all of my sites now.

**Comment by DevinWalker** [comment]
Same here when I run the command ` wp scaffold plugin-tests plugin-name` I receive from WP-CLI: `Error: The site you have requested is not installed.` when it's clearly installed and I'm able to access it. A bit baffled at the moment.

**Comment by jeremyfelt** [comment]
If you use `vagrant halt` or `vagrant suspend` to end a session and then `vagrant up` to start again, the database for your WordPress installation will remain. If you use `vagrant destroy`, the database will be erased with the rest of the virtual machine.

If you want to move everything to a new VM instance, you would need to backup the databases and content as if you were swapping servers. Content is mapped to your local machine, so that's easier to handle.

**Comment by gitdistill** [comment]
I did not destroy, I halted. I can't remember for the life of me what I did to resolve. Must have started over. Thanks and luck to the others, if I think of anything that might help will add.
