### ISSUE TITLE
VVV + Gulp Browser-Sync?

### ISSUE THREAD

**Issue by TheAggressive** [Varying-Vagrant-Vagrants/VVV#754]
How can I set up gulp browser-sync to work with VVV?

Thanks!

**Comment by devster31** [comment]
What would be the difference from a normal vagrant box?
For wordpress stable something like:
```
browser-sync start --proxy "local.wordpress.dev" --files "style.css,*.php"
```
for example should work, assuming you installed browser-sync globally and you are in a theme directory. This doesn't use the gulp integration, but can be done similarly with a gulpfile in the theme directory.

**Comment by TheAggressive** [comment]
I got it to work with this code but points to local host instead of the actual domain.

<code>
// Browser Sync
gulp.task('browserSync', function() {
    browserSync.init({
        proxy: 'local.wordpress.dev' // Needs the Vagrant Domain Name
    });
});
</code>

**Comment by fclaussen** [comment]
Have anyone figured this out? I've tried a bunch of stuff but I can't make it work

**Comment by devster31** [comment]
```javascript
gulp.task( 'browserSync', function() {
    browserSync({
        logPrefix: 'local.wordpress.dev',
        proxy: 'local.wordpress.dev',
        reloadDelay: 3000,
        open: false
    });
});

gulp.task( 'watch:dev', ['browserSync'], function() { //['styles:dev', ]
    gulp.watch( '**/*.php' ).on( 'change', browserSync.reload );
    gulp.watch( 'style.css', ['styles:dev']);
});
```
I got it to work with this, but it may have changed, haven't updated browserSync in a while

**Comment by fclaussen** [comment]
Thanks @devster31 but It is still not working.
I think I might be close but I don't know what else to do.

I opened vvv Vagrantfile and enabled the forwarded port on line 150.

My task now looks like this
```
gulp.task( 'browserSync', function() {
    browserSync({
        logPrefix: 'owasco.dev',
        proxy: 'owasco.dev',
        port: 8080
    });
});
```

Now I have access over http://localhost:8080 but instead of displaying my site it is displaying the same content as http://vvv.dev

Any other tips on how to make this work? Anyone?

**Comment by devster31** [comment]
@fclaussen I'm running that gulpfile on the host machine, maybe that's the issue. If it's not I don't know what it could be.

**Comment by fclaussen** [comment]
I'm running it on the vm. I ssh into it and run gulp.

**Comment by coffeeneed** [comment]
This didn't work for me. I'm trying to set up VVV with Roots Sage Starter Theme, but I can't seem to get BrowserSync to work. Isn't it possible to run this on the host machine?

**Comment by remondevries** [comment]
@coffeeneed I am trying to do the same thing, had any luck? Seem to be working just fine when running Trellis but in VVV things seem to be different.

**Comment by tomjn** [comment]
**Don't run commands that watch files inside the VM in mounted/shared folders, run them on the host machine**

Do not be surprised if it does not work, this isn't a "its broken lets flip a flag to fix it" thing, it's a tradeoff between performance and latency. Docker for example sacrifices CPU performance to make this work. leading to excessive CPU spikes. Vagrant in network shares uses micro caches to speed things up. It's not a simple thing to fix, and it will never be how you expect it to work due to fundamental technology decisions made elsewhere

**Comment by coffeeneed** [comment]
@remondevries I did not find a solution for this. I started using other tools with Docker instead. Good luck!
