### ISSUE TITLE
Random issue with ports

### ISSUE THREAD

**Issue by alexmoss** [Varying-Vagrant-Vagrants/VVV#776]
When I have VVV running, this app no longer works until I restart:
http://www.ps3mediaserver.org/

It's a long shot, but would you know how two can run side-by-side? Is there a setting within VVV I can change ports or some other potential conflict?

Thanks

**Comment by jeremyfelt** [comment]
Hi @alexmoss, thanks for the ticket. It's entirely possible that the two are conflicting, but it's hard to immediately tell from the documentation. VVV via Vagrant configures a virtual machine at 192.168.50.4 and assigns an IP of 192.168.50.1 to your local machine so that it can communicate. There should be no port forwarding by default that would conflict, but it's possible that network configuration does.
