### ISSUE TITLE
Is it possible to exlude sites from loading on vagrant up?

### ISSUE THREAD

**Issue by mishtershmart** [Varying-Vagrant-Vagrants/VVV#780]
Howdy,

I'm currently using VVV in place of MAMP; i.e. I have one instance that I use to develop a number of client's sites. This is working fine, but the whole process of booting/halting the virtual machine is getting kinda long with the number of sites I have in there; especially the sites with very large databases.

I'm wondering if there is a way I can disable sites that I only work with now and then, so that they don't load up on the vagrant up command?

Cheers,
Phil

**Comment by cristovaov** [comment]
Hi Phil,
By moving your VVV configuration scripts in a subfolder / site `[ex: /Site/vvv-import/]`, you should be able to disable a site by removing its configuration folder. Keep these configs in a private repo, so that you don't have to worry about deleting them. I have a very basic [repo](https://github.com/cristovaov/site-importer-vvv) of such a config folder as example.  

I would however recommend to keep sites/projects per directory. With https://github.com/Varying-Vagrant-Vagrants/VVV/pull/659 you can now more easily comment out from `L 773 to 813`, some VVV features you don't intend to use and this way speed up provisioning processes of a new Vagrant instance.

Hope this info can be of help ~
-Cris.

**Comment by jeremyfelt** [comment]
Noting also that we have #474 open to provide a method for excluding sites. This is something I'd like to see at least minimal support for in the future.
