### ISSUE TITLE
Machine name keeps changing

### ISSUE THREAD

**Issue by lkwdwrd** [Varying-Vagrant-Vagrants/VVV#848]
I often run vagrant commands from sub-folders of the VM definition. It would appear that the new code setting the machine name based on the folder name doesn't traverse to the VVV root directory. The result of this is that my machine name keeps changing as I run vagrant commands from the various subdirectories. This hasn't caused too much trouble, but it would be nice to maintain a consistent name as long as the rood dir remains the same.

**Comment by jeremyfelt** [comment]
I *finally* got around to checking this out. 

Starting in a `~/Development/vvv` directory.

When I `vagrant up`, I see the message "Bringing machine 'default' up with 'virtualbox' provider", but when I open the VirtualBox GUI I see "vvv" as the machine name.

If I change directories to `~/Development/vvv/www/wordpress-develop` and run `vagrant ssh` or `vagrant up` again, nothing changes. If I run `vagrant halt` and then `vagrant up` again, my box name inside the GUI changes to "wordpress-develop". So it seems that a box needs to be powered on to receive a new name.

As mentioned in #865, this poses the biggest problem when you run multiple instances of VVV from different project directories that have the same subdirectory names.

Example:
* `~/Development/project-one/vvv/`
* `~/Development/project-two/vvv/`

This creates a situation in which there are two boxes named "vvv". Conflict!

I think the ways around this are:

* If you setup a second VVV instance, make sure you use a Customfile to configure the box name manually.
* Set the box name so that it is absolutely unique with a hash of the full path to the `Vagrantfile` as mentioned in #865.
* Set the box name so that it is likely unique by adding a short random number to the end of the name.

In the last two, we would also want to generate the directory name based on the project, not the working directory.

I was previously worried about making this change in a minor release of VVV, but I don't think that's an issue as it seems to require only a reboot of the VM and won't cause real issues with stability.
