### ISSUE TITLE
New VVV Box Can't Install Sass

### ISSUE THREAD

**Issue by rwrobe** [Varying-Vagrant-Vagrants/VVV#890]
I've tried installing SASS many times in a new VVV box, using the command `sudo gem install sass`, but when I try `sass -v` afterward I get an erro saying that sass could not be found.

**Comment by ivcreative** [comment]
Same here also hope they make this VVV an updated version with apache

**Comment by cfoellmann** [comment]
What does sass have to do with Apache? We use nginx which also has nothing to do with sass/ruby

**Comment by frankjrangel** [comment]
Hey guys @rwrobe @ivcreative  
Most likely the problem is that you don't have the gems folder in your PATH, your set up may vary from mine because I updated the bundled ruby version but I think my solution will work for you as well.

Simply go to the **.bashrc** file on your home folder (or do `cd ~/ && vim .bashrc` from anywhere, easy) and add the following:
`export PATH="/var/lib/gems/1.9.1/gems/sass-3.4.22/bin:$PATH"`

Of course your ruby or sass versions may vary as well, be on the lookout for that
Also you may have to logout and log back in for it to work

Cheers!
