### ISSUE TITLE
VVV doesn't work after disconnecting from a VPN

### ISSUE THREAD

**Issue by mrpritchett** [Varying-Vagrant-Vagrants/VVV#894]
I use Cisco AnyConnect to go on and off a VPN for a client. Once I disconnect from the VPN, when using Mercury Vagrant I have to run `sudo route -nv add -net 192.168.150 -interface vboxnet0` to reroute the IPs to cause vagrant to work. But with VVV this doesn't work even after I adjust the IP to match the IPs from hosts. Any idea on this?

**Comment by jeremyfelt** [comment]
I have a feeling strange things can happen.

That's probably my best answer. 😄 

In all seriousness, I use Cisco AnyConnect on a pretty regular basis with both VVV and another VM and haven't had any trouble yet—even without any commands to reroute IPs. There are probably a wide variety of client settings in the VPN client that may affect this though.

**Comment by mrpritchett** [comment]
We're working on it internally at Crowd Favorite to see if we can get any traction on a solution. For now I've switched to WPE's Mercury Vagrant for this project. I'll report back if we find a solution.

**Comment by lkwdwrd** [comment]
Hey Matt, it's kind of side-stepping the issue, but on of the things we've been doing when we have to deal with AnyConnect VPNs (and a couple of other VPN flavors too) is package them up and proxy requests through a virtual machine: https://github.com/ericmann/openconnect-vm

You can then use [Proxy SwitchyOmega](https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif?hl=en) in Chrome, or [FoxyProxy](https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/) in Firefox to whitelist the requests that need to be made through that VPN connection. It has helped us only make requests through the VPN when necessary. Since the AnyConnect VPN is typically client owned, we try to keep requests through the VPN limited to ONLY requests for that client and the whitelist is the perfect way to do it.

Using this technique I have still been able to tunnel through to our company owned VPN (An OpenVPN install connected to with TunnelBlick) to keep general traffic secure. Running the AnyConnect VPN through the OpenVPN VPN was a bit weird at first, but I actually found it increased stability when switching networks rather than cause any problems. Good luck!

**Comment by jeremyfelt** [comment]
I'm going to close this out, but please feel free to leave any additional information. Good stuff for anyone running into the same issues.
