### ISSUE TITLE
Could not rename the directory

### ISSUE THREAD

**Issue by tuantai0304** [Varying-Vagrant-Vagrants/VVV#918]
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: vvv
The name of your virtual machine couldn't be set because VirtualBox
is reporting another VM with that name already exists. Most of the
time, this is because of an error with VirtualBox not cleaning up
properly. To fix this, verify that no VMs with that name do exist
(by opening the VirtualBox GUI). If they don't, then look at the
folder in the error message from VirtualBox below and remove it
if there isn't any information you need in there.

VirtualBox error:

VBoxManage.exe: error: Could not rename the directory 'C:\Users\TuanTai\VirtualBox VMs\ubuntu-cloudimg-trusty-vagrant-amd64_1465869727246_57247' to 'C:\Users\TuanTai\VirtualBox VMs\vvv' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3016 of file VBoxManageModifyVM.cpp
```

Hello everybody,

I always run into this problem whenever I call vagrant up from the second time. The script auto create the folder VVV in the first run, but it seems trying to create another vvv in second time. What can I do in this situation?

Thanks

**Comment by cfoellmann** [comment]
are you opening cmd/ps in admin mode? Could cause this issues.

**Comment by glerner** [comment]
This issue is not resolved, I have the exact same problem. Windows 10, Vagrant 1.9.1, 

<code>cd C:\home\glvagrant
git clone git://github.com/Varying-Vagrant-Vagrants/VVV.git dev
cd dev
vagrant up
	Adding box 'ubuntu/trusty64' (v20170110.0.0) for provider: virtualbox
==> default: Successfully added box 'ubuntu/trusty64' (v20170110.0.0) for 'virtualbox'!
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: dev
VBoxManage.exe: error: Could not rename the directory 'C:\home\glvagrant\ubuntu-cloudimg-trusty-vagrant-amd64_1484382016546_37157' to 'C:\home\glvagrant\dev' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3052 of file VBoxManageModifyVM.cpp
</code>

Yes, I am running Administrator:Windows PowerShell
