### ISSUE TITLE
Should www folder be empty?

### ISSUE THREAD

**Issue by mrdv** [Varying-Vagrant-Vagrants/VVV#933]
Hi guys, 

I am trying to setup VVV for the first time. Running OSX i had some issues with Virtual Box so I did fresh install on both Vagrant and Virtual box.

After running vagrant up all of the 5 links

vvv.dev
local.wordpress.dev
local.wordpress-trunk.dev
src.wordpress-develop.dev
build.wordpress-develop.dev

go to the default debian page. Shouldn't there be a fresh WPs already? 

If not, how do I setup one?

**Comment by mrdv** [comment]
Whoops, it seems vangrant up returned some errors after all.

This is what I got for each of the websites

==> default: Installing WordPress develop...
==> default: Error: This does not seem to be a WordPress install.
==> default: Pass --path=`path/to/wordpress` or run `wp core download`.
==> default: cp: 
==> default: cannot stat `/srv/config/wordpress-config/wp-tests-config.php'
==> default: : No such file or directory
==> default: /tmp/vagrant-shell: line 776: cd: /srv/www/wordpress-develop/: No such file or directory

and at the end

==> default: nginx: unrecognized service
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.


I tried vangraut up --provision no luck. Any clues why I am getting these errors?

**Comment by jeremyfelt** [comment]
Hi @mrdv, thanks for opening a ticket, sorry the wait.

It sounds like provisioning is not running completely. Can you run `vagrant provision` and copy/paste the entire output into a [gist](https://help.github.com/articles/about-gists/) so that we can try to spot the underlying issue.

**Comment by anhdq1801** [comment]
I run `vagrant up` or `vagrant provision` more time but still have error

> ==> default: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/customize/class-wp-customize-site-icon-control.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/customize/class-wp-customize-cropped-image-control.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/customize/class-wp-widget-area-customize-control.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/customize/class-wp-customize-background-image-control.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/customize/class-wp-customize-media-control.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/customize/class-wp-customize-nav-menu-section.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/customize/class-wp-customize-nav-menu-item-control.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/customize/class-wp-customize-new-menu-section.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/customize/class-wp-customize-header-image-setting.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/customize/class-wp-customize-nav-menu-auto-add-control.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/customize/class-wp-customize-nav-menu-control.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/customize/class-wp-customize-nav-menu-item-setting.php: Cannot open
==> default: wordpress/wp-includes/customize/class-wp-customize-nav-menu-setting.php
==> default: : No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/customize/class-wp-customize-nav-menu-setting.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/class-smtp.php
==> default: 
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/class-smtp.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/template-loader.php
==> default: wordpress/wp-includes/class-walker-comment.php
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/template-loader.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/class-walker-comment.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/class-wp-network.php
==> default: wordpress/wp-includes/atomlib.php
==> default: wordpress/wp-includes/theme-compat/
==> default: wordpress/wp-includes/theme-compat/comments.php
==> default: wordpress/wp-includes/theme-compat/sidebar.php
==> default: 
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/class-wp-network.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/atomlib.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/theme-compat: Cannot mkdir: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/theme-compat/comments.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/theme-compat/sidebar.php: Cannot open
==> default: wordpress/wp-includes/theme-compat/embed.php
==> default: wordpress/wp-includes/theme-compat/footer.php
==> default: wordpress/wp-includes/theme-compat/footer-embed.php
==> default: wordpress/wp-includes/theme-compat/header-embed.php
==> default: wordpress/wp-includes/theme-compat/embed-content.php
==> default: wordpress/wp-includes/theme-compat/header.php
==> default: wordpress/wp-includes/theme-compat/embed-404.php
==> default: wordpress/wp-includes/class.wp-styles.php
==> default: wordpress/wp-includes/rewrite.php
==> default: : No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/theme-compat/embed.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/theme-compat/footer.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/theme-compat/footer-embed.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/theme-compat/header-embed.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/theme-compat/embed-content.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/theme-compat/header.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/theme-compat/embed-404.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/class.wp-styles.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/rewrite.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/nav-menu.php
==> default: 
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/nav-menu.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/embed-template.php
==> default: wordpress/wp-includes/class-wp-comment.php
==> default: wordpress/wp-includes/class-wp-customize-control.php
==> default: 
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/embed-template.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/class-wp-comment.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/class-wp-customize-control.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/user.php
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/user.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/cache.php
==> default: tar: 
==> default: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/cache.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/session.php
==> default: wordpress/wp-includes/ms-default-constants.php
==> default: wordpress/wp-includes/ms-default-filters.php
==> default: 
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/session.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/ms-default-constants.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/ms-default-filters.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/post-thumbnail-template.php
==> default: wordpress/wp-includes/class-wp-theme.php
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/post-thumbnail-template.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/class-wp-theme.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/feed-rdf.php
==> default: 
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/feed-rdf.php: Cannot open
==> default: wordpress/wp-includes/class-wp-metadata-lazyloader.php
==> default: wordpress/wp-includes/pomo/
==> default: wordpress/wp-includes/pomo/mo.php
==> default: wordpress/wp-includes/pomo/streams.php
==> default: wordpress/wp-includes/pomo/translations.php
==> default: : No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/class-wp-metadata-lazyloader.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/pomo: Cannot mkdir: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/pomo/mo.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/pomo/streams.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/pomo/translations.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/pomo/entry.php
==> default: wordpress/wp-includes/pomo/po.php
==> default: wordpress/wp-includes/bookmark-template.php
==> default: wordpress/wp-includes/class-wp-http-response.php
==> default: wordpress/wp-includes/feed-rss2.php
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/pomo/entry.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/pomo/po.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/bookmark-template.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/class-wp-http-response.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/feed-rss2.php: Cannot open: No such file or directory
==> default: wordpress/wp-includes/taxonomy.php
==> default: tar: 
==> default: wordpress: Cannot mkdir
==> default: : Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/taxonomy.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/feed-atom-comments.php
==> default: tar: 
==> default: wordpress: Cannot mkdir
==> default: : Permission denied
==> default: 
==> default: tar: wordpress/wp-includes/feed-atom-comments.php: Cannot open: No such file or directory
==> default: wordpress/wp-includes/load.php
==> default: tar: 
==> default: wordpress: Cannot mkdir
==> default: : Permission denied
==> default: 
==> default: tar: wordpress/wp-includes/load.php: Cannot open: No such file or directory
==> default: wordpress/wp-includes/default-constants.php
==> default: tar: 
==> default: wordpress: Cannot mkdir
==> default: : Permission denied
==> default: wordpress/wp-includes/class-wp-locale.php
==> default: wordpress/wp-includes/meta.php
==> default: 
==> default: tar: wordpress/wp-includes/default-constants.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/class-wp-locale.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/meta.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/theme.php
==> default: tar: 
==> default: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/theme.php: Cannot open
==> default: wordpress/wp-includes/class-wp-term-query.php
==> default: : No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/comment-template.php
==> default: wordpress/wp-includes/class-wp-term-query.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/comment-template.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/class-wp-customize-panel.php
==> default: tar: 
==> default: wordpress: Cannot mkdir
==> default: : Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/class-wp-customize-panel.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/pluggable-deprecated.php
==> default: tar: 
==> default: wordpress: Cannot mkdir
==> default: : Permission denied
==> default: wordpress/wp-includes/widgets.php
==> default: 
==> default: tar: wordpress/wp-includes/pluggable-deprecated.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/widgets.php: Cannot open
==> default: wordpress/wp-includes/functions.wp-scripts.php
==> default: : No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/functions.wp-scripts.php: Cannot open
==> default: wordpress/wp-includes/class-wp-image-editor-gd.php
==> default: wordpress/wp-includes/canonical.php
==> default: : No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/class-wp-image-editor-gd.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/canonical.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/ms-load.php
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/ms-load.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/class-walker-category-dropdown.php
==> default: wordpress/wp-includes/Text/
==> default: wordpress/wp-includes/Text/Diff/
==> default: wordpress/wp-includes/Text/Diff/Engine/
==> default: wordpress/wp-includes/Text/Diff/Engine/string.php
==> default: wordpress/wp-includes/Text/Diff/Engine/native.php
==> default: 
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/class-walker-category-dropdown.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/Text: Cannot mkdir: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/Text/Diff: Cannot mkdir: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/Text/Diff/Engine: Cannot mkdir: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/Text/Diff/Engine/string.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: wordpress/wp-includes/Text/Diff/Engine/xdiff.php
==> default: wordpress/wp-includes/Text/Diff/Engine/shell.php
==> default: wordpress/wp-includes/Text/Diff/Renderer/
==> default: wordpress/wp-includes/Text/Diff/Renderer/inline.php
==> default: wordpress/wp-includes/Text/Diff/Renderer.php
==> default: wordpress/wp-includes/Text/Diff.php
==> default: wordpress/wp-includes/rest-api.php
==> default: tar: wordpress/wp-includes/Text/Diff/Engine/native.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/Text/Diff/Engine/xdiff.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/Text/Diff/Engine/shell.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/Text/Diff/Renderer: Cannot mkdir: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/Text/Diff/Renderer/inline.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/Text/Diff/Renderer.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-includes/Text/Diff.php: Cannot open: No such file or directory
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/rest-api.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/update.php
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/update.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-includes/comment.php
==> default: 
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: 
==> default: wordpress/wp-includes/comment.php: Cannot open
==> default: : No such file or directory
==> default: wordpress/wp-config-sample.php
==> default: tar: wordpress: Cannot mkdir: Permission denied
==> default: tar: wordpress/wp-config-sample.php: Cannot open: No such file or directory
==> default: tar: 
==> default: Exiting with failure status due to previous errors
==> default: mv: 
==> default: cannot stat ‘wordpress’
==> default: : No such file or directory
==> default: /tmp/vagrant-shell: line 616: cd: /srv/www/wordpress-default: No such file or directory
==> default: Configuring WordPress Stable...
==> default: Error: This does not seem to be a WordPress install.
==> default: Pass --path=`path/to/wordpress` or run `wp core download`.
==> default: Installing WordPress Stable...
==> default: Error: This does not seem to be a WordPress install.
==> default: Pass --path=`path/to/wordpress` or run `wp core download`.
==> default: Updating WordPress trunk...
==> default: Updating '.':
==> default: U    wp-includes/version.php
==> default: U    wp-includes/pluggable.php
==> default: 
==> default: Fetching external item into 'wp-content/plugins/akismet':
==> default: Updated external to revision 1479205.
==> default: At revision 38227.
==> default: Updating WordPress develop...
==> default: Updating '.':
==> default: U    tests/phpunit/tests/mail.php
==> default: U    src/wp-includes/pluggable.php
==> default: 
==> default: Fetching external item into 'tests/phpunit/data/plugins/wordpress-importer':
==> default: Updated external to revision 1479205.
==> default: At revision 38287.
==> default: Updating npm packages...
==> default: Initializing grunt in WordPress develop... This may take a few moments.
==> default: /tmp/vagrant-shell: line 718: grunt: command not found
==> default:  
==> default: VVV custom site import
==> default: Cleaning the virtual machine's /etc/hosts file...
==> default: Adding domains to the virtual machine's /etc/hosts file...
==> default: -----------------------------
==> default: Provisioning complete in 118 seconds
==> default: For further setup instructions, visit http://vvv.dev
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: mysql stop/waiting
==> default: mysql start/running, process 11209
==> default: Running provisioner: shell...
    default: Running: inline script
==> default:  * Restarting nginx nginx
==> default:    ...done.

**Comment by jeremyfelt** [comment]
@anhdq1801 I trimmed your vagrant output down a bit to the relevant parts. It looks like there is a permission issue of some kind with the mapped drive. What's interesting is that the WordPress trunk directory seems to be having no trouble.

* What OS are you using?
* What version of VVV are you using?
* What version of VirtualBox is installed?
* What version of Vagrant is installed?
* Is there a `wordpress/` and/or `wordpress-default` directory in VVV's `www` directory?

**Comment by jeremyfelt** [comment]
I'm going to close this out, but please feel free to continue discussion. We can always reopen if needed.
