### ISSUE TITLE
Box doesn't include PHP's BC Math Module?

### ISSUE THREAD

**Issue by jakejackson1** [Varying-Vagrant-Vagrants/VVV#944]
I wasn't able to use any of [PHP's BC Math functions](http://php.net/manual/en/ref.bc.php) when running the latest version of VVV (it just throws PHP errors). Is this module not included? If not, why?

**Comment by jeremyfelt** [comment]
Hi @jakejackson1, thanks for opening a ticket. My guess is that php-bcmath is not common enough to be included as part of the php7.0 package that we're using. I don't recall running into the BC Math functions myself.

I would recommend adding `apt-get install php7.0-bcmath` to a `provision/provision-post.sh` file so that it is available in your local configuration.

**Comment by LoreleiAurora** [comment]
This was included back when we were on 5.6 (i just missed it out), should we not add it again for BC?

**Comment by jeremyfelt** [comment]
@LoreleiAurora good catch, I didn't know it was! :) We should have it for BC then.

**Comment by jrfnl** [comment]
BCMath has been included in the default PHP compilations since PHP 3, so including it is definitely recommended.
