### ISSUE TITLE
Document the ongoing maintenance of a local VM

### ISSUE THREAD

**Issue by jeremyfelt** [Varying-Vagrant-Vagrants/VVV#961]
How these may matter and how they should be kept up to date:
- VirtualBox updates
- Vagrant updates
- `vagrant box update`
- vagrant-vbguest plugin

**Comment by jeremyfelt** [comment]
From #953, for an initial configuration of VVV...

* develop is probably the best branch to use, though will be unstable from time to time
* We should have more releases to make master more stable
* develop is the right branch for git clone to encourage contributions.
* Instructions should be available for running master or specific tagged versions.

**Comment by rclations** [comment]
Doesn't that setup make a fairly large assumption that anyone setting up VVV for the first time will have a desire, knowledge, and expertise to deal with any instabilities on a develop branch, and also a desire to become a contributor immediately?

I feel like a better and more common approach would be to offer a really stable piece of software to new users and make it easy for anyone with a desire/expertise to get to the potentially-unstable develop branch and contribute, rather than the other way around?

**Comment by jeremyfelt** [comment]
That's true, and somewhere where we can split the instructions up and be clear.

Installation instructions on varyingvagrantvagrants.org should lean toward how to retrieve the latest stable version. Instructions attached to this repository should favor the develop branch and probably be oriented more around contribution.

**Comment by Mte90** [comment]
We need to care of this updates right now?
I mean:

- VVV doesn't run if you are using a not supported version of Vagrant
- Virtualbox doesn't matter a lot, and is not easy because right now we are suggesting 5.x on Windows and in other OS the last version but this can change
- box update is already documented in other pages in the docs
- vbguest is not required anymore also because we are using an update box image

**Comment by tomjn** [comment]
that seems right, lets go over the existing docs and confirm all is good
