### ISSUE TITLE
Private Key change permissions 0600

### ISSUE THREAD

**Issue by bountydigital** [Varying-Vagrant-Vagrants/VVV#988]
Hi, 
I'm trying to install Vagrant and this error keeps coming up but I'm not sure how to change the permissions:

```
The private key to connect to this box via SSH has invalid permissions
set on it. The permissions of the private key should be set to 0600, otherwise SSH will
ignore the key. Vagrant tried to do this automatically for you but failed. Please set the
permissions on the following file to 0600 and then try running this command again:
```

**Comment by LoreleiAurora** [comment]
Try running `chmod 0600 .vagrant/machines/default/virtualbox/private_key` from the VVV root.

**Comment by xhiza** [comment]
move private_key out of NFS drive and create a soft link towards old location (don’t forget to chmod original key)

**Comment by tomjn** [comment]
It's not supposed to be outside of the machine for security reasons. This was likely because of an older version of Vagrant, it was a bug a while back that it would not set the key properly

**Comment by nontro** [comment]
@xhiza the soft link worked perfectly for me

**Comment by tomjn** [comment]
Recreating the VM with a `vagrant destroy && vagrant up --provision` would be better. No user should ever have to touch the key file as it's an internal Vagrant thing

I suspect some users might do so in order to use SSH auth, but that is a dangerous thing to do, and not the way it should be fixed. SSH key forwarding is the answer, and turned on by default, it allows the hosts ssh key to be used inside the VM

**Comment by nikhilbansal97** [comment]
@xhiza Can you explain more on why did we have to do this??

**Comment by nontro** [comment]
@nikhilbansal97 
It was because was impossibile to change the permission on the key in the original position.

**Comment by tomjn** [comment]
I'd like to reiterate that there are no circumstances under which one should need to or want to touch or change things regarding SSH keys and the VM. If you can run `ssh` and connect on the host, it should work on the guest without changes via SSH forwarding. Any other method is dangerous, unsupported, unreliable, and could break your VM.

**If SSH forwarding is non-functional, upgrade to the latest VVV Vagrant and VirtualBox, reboot, reprovision, and if that does not fix the issue, create a _new_ issue here.**

**Comment by nontro** [comment]
ok there is just one circumstance where if you get this message :

> `The  private key to connect to this box via SSH has invalid permissions
set on it. The permissions of the private key should be set to 0600, otherwise SSH will
ignore the key. Vagrant tried to do this automatically for you but failed. Please set the
permissions on the following file to 0600 and then try running this command again:`

you can solve with a soft link and changing  the permission in the original file. 
It's a trick but it works

**Comment by metagrapher** [comment]
> I'd like to reiterate that there are no circumstances under which one should need to or want to touch or change things regarding SSH keys and the VM. 

No Circumstances Whatsoever? 
Are you 100% sure? 
What about in a WSL situation wherein literally nothing is able to set the proper permissions, thereby making Vagrant simply not work? 
it does seem like that might be more than "no circumstances".  

telling people not to use the solutions or to reinstall or upgrade, the latter of which is hard to do from the latest version of the software, is not really a workable solution/workaround.

Now, @tomjn since you are so certain that fixing this in this fashion is a terrible idea, and I do trust your expertise, I would be SUPER INTERESTED in a safe way to fix this, taking into consideration all the factors and implications of a Linux->WSL->Windows->VM workflow, please. 
In the current state, setting the permissions on this does not work.

**Comment by metagrapher** [comment]
Hrm. It looks like this may also be a solution for anyone coming across this issue...
https://github.com/hashicorp/vagrant/issues/8742#issuecomment-315137426

**Comment by tomjn** [comment]
@metagrapher I believe you've misread my comment addressing SSH port forwarding. It appears you've encountered edge cases in Vagrant itself, and you found a solution that doesn't involve messing with keys.

As I said, if you're able  to run `vagrant  ssh`  and enter the VM, then you should be able to SSH to all the things inside the VM that you can SSH to outside the VM, assuming SSH Agents are working correctly.
