### ISSUE TITLE
Xdebug advice

### ISSUE THREAD

**Issue by chris10an** [Varying-Vagrant-Vagrants/VVV#994]
I'm struggling to get Xdebug to work in Atom editor with plugins. So I'm wondering if you guys have some recommendations to free client? Is [phpdebug](http://pugdebug.com/) any good?

Or have you manage to it working with Atom, and is it worth the effort?

**Comment by btsimonh** [comment]
As a newbie, I chose netbeans, and it seems to work.  However, the xdebug config seems a bit of a pig in general.  see https://github.com/YellaUmbrella-tv/VVV for 3 commits i made today on top of VVV develop which i hope will help me.  
Basically, I found it difficult to change the xdebug max_execution_time, so wrote a script to copy the relevant .ini files from the local config folders into the right place in the VM; this enables you to play more easily with configs on the fly.... just open an ssh, and run 'copyxdebug' after a change to xdebug.ini or php-custom.ini.
I'm not confident enough to issue a pull request; as I'm so new to vagrant (and WP dev in general); so i'm not sure if there is already a way to do this easily (vagrant provision does it, but it takes some time to achieve a very simple operation....).

**Comment by cfoellmann** [comment]
Just open a PR so we can easily give feedback on the matter and on the code specifically

**Comment by btsimonh** [comment]
@cfoellmann :) still not got my head around github; can't find the PR anywhere....  I've been working with the results today (win 10 host), and so far, so good.  No timeouts, no ngnix errors;  just a couple of times when netbeans needed to be closed and re-opened in order to launch a browser (seems like if you don't hit stop on the debug session, it gets in a twist). All seems good. 
@mikromakro - netbeans is treating me well so far....

**Comment by cfoellmann** [comment]
@btsimonh just here: https://github.com/Varying-Vagrant-Vagrants/VVV/compare

**Comment by btsimonh** [comment]
ahh! no i completely miss-understood your first comment!  I thought you HAD opened a PR; but you're asking me to...  ok, no problem, will do.

**Comment by btsimonh** [comment]
done
