### ISSUE TITLE
Installation - can't use custom directory - shouldn't VVV be directory-name agnostic?

### ISSUE THREAD

**Issue by bhagerty** [Varying-Vagrant-Vagrants/VVV#997]
Because Vagrant names machines based on the directory they are in, I like to use unique directory names.

But VVV apparently doesn't work unless it's in a directory named "VVV." Specifically, when I cloned the repo into a differently named directory and ran Vagrant up, it failed. When I cloned the repo into a directory named "VVV," it worked fine.

Shouldn't VVV be directory-name agnostic? Shouldn't I be able to clone the repo into "VVV-v1" and have it work?

**Comment by LoreleiAurora** [comment]
VVV is directory agnostic, can you share logs?

**Comment by bhagerty** [comment]
So here is an exact record of a session in which I cloned VVV into a directory named "vvv-test" and ran Vagrant up. It fails with an attempt to rename the VM. The message about the machine already existing in VirtualBox is false, except to the extent that VVV has caused the problem. This is the first time I have ever used this particular directory name. I got the same errors repeatedly earlier (using various directory names, and making sure to destroy anything related to previous attempts). I was able to get VVV to create a box only when I cloned it into a subdirectory named VVV (which I let it create), not when I cloned it into an arbitrarily named directory.

```

bhage@BCH-win10-desktop MINGW64 /h/VirtualMachines/vvv-test
$ git clone https://github.com/Varying-Vagrant-Vagrants/VVV.git ./
Cloning into '.'...
remote: Counting objects: 6180, done.
remote: Total 6180 (delta 0), reused 0 (delta 0), pack-reused 6180
Receiving objects: 100% (6180/6180), 6.44 MiB | 2.72 MiB/s, done.
Resolving deltas: 100% (2269/2269), done.

bhage@BCH-win10-desktop MINGW64 /h/VirtualMachines/vvv-test (develop)
$ ls
CHANGELOG.md  CONTRIBUTING.md  LICENSE  provision/  Vagrantfile  www/
config/       database/        log/     README.md   wp-cli.yml

bhage@BCH-win10-desktop MINGW64 /h/VirtualMachines/vvv-test (develop)
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: vvv-test
The name of your virtual machine couldn't be set because VirtualBox
is reporting another VM with that name already exists. Most of the
time, this is because of an error with VirtualBox not cleaning up
properly. To fix this, verify that no VMs with that name do exist
(by opening the VirtualBox GUI). If they don't, then look at the
folder in the error message from VirtualBox below and remove it
if there isn't any information you need in there.

VirtualBox error:

VBoxManage.exe: error: Could not rename the directory 'H:\VirtualMachines\ubuntu
-cloudimg-trusty-vagrant-amd64_1475791453272_46702' to 'H:\VirtualMachines\vvv-test' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3052 of file VBoxManageModifyVM.cpp

bhage@BCH-win10-desktop MINGW64 /h/VirtualMachines/vvv-test (develop)
$

```

**Comment by LoreleiAurora** [comment]
Im struggling to reproduce this can you please give me your:
- Windows Version
- Virtualbox Version
- Vagrant Version

**Comment by bhagerty** [comment]
Windows 10, VirtualBox 5.1.6, Vagrant 1.8.6.

I have relocated VAGRANT_HOME to H:\VirtualMachines\vagrant-home, and I have set my default VirtualMachine folder in VirtualBox to H:\VirtualMachines. Perhaps this is related to the problem? (Though, as I said, it works fine if I clone VVV into a subdirectory named VVV rather than into a directory with a custom name. And, of course, VVV should not choke just because some default directories have been changed.)

**Comment by cfoellmann** [comment]
I am using Windows 10, VirtualBox 5.0.26, Vagrant 1.8.6
Downgraded the Virtualbox because I suspected some issues with the 5.1 branch. Seems to help

But I had a similar issue and I needed to delete an old (not automatically deleted) VM

**Comment by jeremyfelt** [comment]
> But I had a similar issue and I needed to delete an old (not automatically deleted) VM

@cfoellmann Did deleting this old VM solve the similar issue? @bhagerty is it possible that this is the cause? Are there any unaccounted for VMs running in VirtualBox?

Sorry, I realize this is months late. :) VVV should have no trouble working in a `non-vvv/` directory.

Possibly related: #809,

**Comment by glerner** [comment]
Same issue [https://github.com/Varying-Vagrant-Vagrants/VVV/issues/918](url) 
Windows 10, Oracle VirtualBox Version 5.1.12 r112440 (Qt5.6.2), Vagrant 1.9.1

Since Git clones into the VVV folder, why is VBoxManage trying to rename the Ubuntu folder to VVV ??? Should it be moving files into the VVV folder instead?

PS C:\home\glvagrant> git clone git://github.com/Varying-Vagrant-Vagrants/VVV.git
Cloning into 'VVV'...

PS C:\home\glvagrant> cd VVV
PS C:\home\glvagrant\VVV> vagrant up
VBoxManage.exe: error: Could not rename the directory 'C:\home\glvagrant\ubuntu-cloudimg-trusty-vagrant-amd64_1484445118192_15303' to 'C:\home\glvagrant\VVV' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3052 of file VBoxManageModifyVM.cpp
PS C:\home\glvagrant\VVV> vBoxManage list vms
>>
"glvagrant_default_1484436375783_13930" {00bf0642-0ddd-4ea5-97bd-da92795594f3}
"ubuntu-cloudimg-trusty-vagrant-amd64_1484437086858_77894" {e1ed6606-5054-44ae-813c-46dc47b91324}
"ubuntu-cloudimg-trusty-vagrant-amd64_1484445118192_15303" {d271b1b1-c791-4fa5-95ab-2246230471a2}

PS C:\home\glvagrant\VVV> vBoxManage unregistervm ubuntu-cloudimg-trusty-vagrant-amd64_1484445118192_15303

PS C:\home\glvagrant\VVV> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...

VBoxManage.exe: error: Could not rename the directory 'C:\home\glvagrant\ubuntu-cloudimg-trusty-vagrant-amd64_1484447659185_50981' to 'C:\home\glvagrant\VVV' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3052 of file VBoxManageModifyVM.cpp

**Comment by willboudle** [comment]
Also getting this issue, same versions as above
